### ISSUE TITLE
Can't install the plugin

### ISSUE THREAD

**Issue by CiquattroFPV** [sdesalve/hassio-addons#1]
These are error logs

> 
> 19-08-29 09:11:50 INFO (SyncWorker_8) [hassio.docker.addon] Start build 89275b70/armv7-addon-dss_voip:1.1.1
> 19-08-29 09:12:37 ERROR (SyncWorker_8) [hassio.docker.addon] Can't build 89275b70/armv7-addon-dss_voip:1.1.1: The command '/bin/ash -o pipefail -c set -o pipefail         && echo '@edge http://dl-cdn.alpinelinux.org/alpine/edge/main' >> /etc/apk/repositories     && echo '@edge http://dl-cdn.alpinelinux.org/alpine/edge/community' >> /etc/apk/repositories     && echo '@edge http://dl-cdn.alpinelinux.org/alpine/edge/testing' >> /etc/apk/repositories         && apk add --no-cache --virtual .build-dependencies         tar=1.32-r0         && apk add --no-cache         libcrypto1.1=1.1.1c-r0         libssl1.1=1.1.1c-r0         musl-utils=1.1.22-r2         musl=1.1.22-r2         && apk add --no-cache         bash=5.0.0-r0         curl=7.65.1-r0         jq=1.6-r0         tzdata=2019a-r0         && apk add --no-cache         sox=14.4.2-r5         pjsua=2.8-r0         screen=4.6.2-r0         && S6_ARCH="${BUILD_ARCH}"     && if [ "${BUILD_ARCH}" = "i386" ]; then S6_ARCH="x86"; fi     && if [ "${BUILD_ARCH}" = "armv7" ]; then S6_ARCH="arm"; fi         && curl -L -s "https://github.com/just-containers/s6-overlay/releases/download/v1.22.1.0/s6-overlay-${S6_ARCH}.tar.gz"         | tar zxvf - -C /         && mkdir -p /etc/fix-attrs.d     && mkdir -p /etc/services.d         && curl -J -L -o /tmp/bashio.tar.gz         "https://github.com/hassio-addons/bashio/archive/v0.3.2.tar.gz"     && mkdir /tmp/bashio     && tar zxvf         /tmp/bashio.tar.gz         --strip 1 -C /tmp/bashio         && mv /tmp/bashio/lib /usr/lib/bashio     && ln -s /usr/lib/bashio/bashio /usr/bin/bashio         && apk del --purge .build-dependencies     && rm -f -r         /tmp/*' returned a non-zero code: 1
> 19-08-29 09:14:43 INFO (SyncWorker_2) [hassio.docker.addon] Start build 89275b70/armv7-addon-dss_voip:1.1.1
> 19-08-29 09:15:01 ERROR (SyncWorker_2) [hassio.docker.addon] Can't build 89275b70/armv7-addon-dss_voip:1.1.1: The command '/bin/ash -o pipefail -c set -o pipefail         && echo '@edge http://dl-cdn.alpinelinux.org/alpine/edge/main' >> /etc/apk/repositories     && echo '@edge http://dl-cdn.alpinelinux.org/alpine/edge/community' >> /etc/apk/repositories     && echo '@edge http://dl-cdn.alpinelinux.org/alpine/edge/testing' >> /etc/apk/repositories         && apk add --no-cache --virtual .build-dependencies         tar=1.32-r0         && apk add --no-cache         libcrypto1.1=1.1.1c-r0         libssl1.1=1.1.1c-r0         musl-utils=1.1.22-r2         musl=1.1.22-r2         && apk add --no-cache         bash=5.0.0-r0         curl=7.65.1-r0         jq=1.6-r0         tzdata=2019a-r0         && apk add --no-cache         sox=14.4.2-r5         pjsua=2.8-r0         screen=4.6.2-r0         && S6_ARCH="${BUILD_ARCH}"     && if [ "${BUILD_ARCH}" = "i386" ]; then S6_ARCH="x86"; fi     && if [ "${BUILD_ARCH}" = "armv7" ]; then S6_ARCH="arm"; fi         && curl -L -s "https://github.com/just-containers/s6-overlay/releases/download/v1.22.1.0/s6-overlay-${S6_ARCH}.tar.gz"         | tar zxvf - -C /         && mkdir -p /etc/fix-attrs.d     && mkdir -p /etc/services.d         && curl -J -L -o /tmp/bashio.tar.gz         "https://github.com/hassio-addons/bashio/archive/v0.3.2.tar.gz"     && mkdir /tmp/bashio     && tar zxvf         /tmp/bashio.tar.gz         --strip 1 -C /tmp/bashio         && mv /tmp/bashio/lib /usr/lib/bashio     && ln -s /usr/lib/bashio/bashio /usr/bin/bashio         && apk del --purge .build-dependencies     && rm -f -r         /tmp/*' returned a non-zero code: 1
>

**Comment by sdesalve** [comment]
I've released a fix. Please upgrade and let me know if now it install...

bye

**Comment by CountParadox** [comment]
Working now on my AMD64 system!

**Comment by CiquattroFPV** [comment]
now it's working.. thank you
