### ISSUE TITLE
sip_parameters: not found when checking config

### ISSUE THREAD

**Issue by rlust** [sdesalve/hassio-addons#10]
I have installed the add-on, it starts but when I check config sip_parameters: not a valid config.

Here is my log info:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: DSS VoIP Notifier
 VoIP Notifier for HomeAssistant
-----------------------------------------------------------
 Add-on version: 3.3.2
 You are running the latest version of this add-on.
 System: HassOS 4.10  (amd64 / qemux86-64)
 Home Assistant Core: 0.111.2
 Home Assistant Supervisor: 227
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[Info] Starting addon...
[Error] Invalid config. Customize it!
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Comment by sdesalve** [comment]
Check your config. It's not my add-on that perform syntax check.

Copy from samples and be aware that in JSON spaces are important

**Comment by sdesalve** [comment]
Invalid config. Customize it!

Mean that you don't have customized your config. Read docs!

**Comment by rlust** [comment]
Sorry, I didn't see the config option in the add-on. my dumb mistake.

Good work here, Thanks!!
