### ISSUE TITLE
Audio is not starting from the begining DSS Voip

### ISSUE THREAD

**Issue by seederp2p** [sdesalve/hassio-addons#101]
Hello!

I'm testing this integration and want to thank you! I can now receive phone calls with urgent alerts, which is fantastic. :)

However, I have a question: When I pick up the call, the audio doesn't start from the beginning, it sounds as the message started before I picked up the call. I do catch the message eventually since it loops, but is there something I'm missing? :)

**Comment by seederp2p** [comment]
> Unfortunately audio it's not synced with phone call.

And that's something that you don't have in your roadmap I believe :)

**Comment by sdesalve** [comment]
isn't available this kind of feature.

should be available another custom component with pjsip python library that have other functions. Check if it will be suitable for your needs

**Comment by seederp2p** [comment]
Actually I didn't find any other integration that did the same as yours.

So I'll stick with it as it is ;)


> isn't available this kind of feature.
> 
> should be available another custom component with pjsip python library that have other functions. Check if it will be suitable for your needs
