### ISSUE TITLE
Crashing on conversion

### ISSUE THREAD

**Issue by kapkirk** [sdesalve/hassio-addons#102]
I have this error in my log:

[Info] Listening for messages via stdin service call...
[Info] Received messages {"call_sip_uri":"sip:+39xxxxx@voip.eutelia.it","message_tts":"Allarme"}
Converting audio file 'https://192.168.31.116:8123/api/tts_proxy/87c5e41b124d14da48609e9cceb52d5621f498cc_it_-_google_translate.mp3'...
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

The IP used for covnersion (https://192.168.31.116:8123) it's wrong.

I try to reinstall but I recive the same error.

Help me, please!

**Comment by sdesalve** [comment]
do you have TTS?
Have you tried to open Converting 'https://192.168.31.116:8123/api/tts_proxy/87c5e41b124d14da48609e9cceb52d5621f498cc_it_-_google_translate.mp3 ?

Have you opened SOX log files?

**Comment by sdesalve** [comment]
The IP used for covnersion (https://192.168.31.116:8123/) it's wrong.

It rely on you hassio config.... fix your TTS config and it will work
