### ISSUE TITLE
Configuration file in /share

### ISSUE THREAD

**Issue by Xoordak** [sdesalve/hassio-addons#103]
Is it correct that the configuration files automatically created by the addon are stored in the /share folder, accessible to everyone?"

Thank you

**Comment by sdesalve** [comment]
yes, In that folder /share  it will place all logs 

you can exclude some items within samba addon config

https://github.com/home-assistant/addons/blob/55fd0cb8ba90bdcaca3162e02c0ebdc176f50703/samba/DOCS.md#option-veto_files-optional

or exclude some hosts.

please refer to SMB addon config
