### ISSUE TITLE
Double phone line

### ISSUE THREAD

**Issue by bozzettaccio** [sdesalve/hassio-addons#104]
Hi, I have set up your app and everything works correctly. I have two apartments connected via VPN through FritzBox, and I first configured one phone (with its own user, password, and Fritz's IP) and then the other, and both work. Between the two, in the service call, only the FritzBox IP changes:

addon: 89275b70_dss_voip
input:
call_sip_uri: sip:+3XXXXXXXXX@192.168.178.1:5060

or

addon: 89275b70_dss_voip
input:
call_sip_uri: sip:+3XXXXXXXXX@192.168.179.1:5060

Is it possible to configure both so that I can choose from which phone number (Fritz) to make the call?

**Comment by sdesalve** [comment]
Have you tried to place call? Should work changing only IP in service call

If doesn't work you need to install a copy of my addon ad local addon and invoke that

**Comment by bozzettaccio** [comment]
How can I create a copy of your addon? It seems that I can install just a single version

**Comment by sdesalve** [comment]
download dss_voip 

adding them to the local add-on repository on a real device running Home Assistant. To access the local add-on repository on a remote device, install either the [Samba](https://my.home-assistant.io/redirect/supervisor_addon/?addon=core_samba) or the [SSH](https://my.home-assistant.io/redirect/supervisor_addon/?addon=core_ssh) add-ons and copy the add-on files to a subdirectory of /addons.
