### ISSUE TITLE
Looking for advice from logs

### ISSUE THREAD

**Issue by rlust** [sdesalve/hassio-addons#11]
Here is my log file:

-----------------------------------------------------------
 Add-on version: 3.3.2
 You are running the latest version of this add-on.
 System: HassOS 4.10  (amd64 / qemux86-64)
 Home Assistant Core: 0.111.2
 Home Assistant Supervisor: 227
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[Info] Starting addon...
[Info] Listening for messages via stdin service call...
[Info] Received messages {"call_sip_uri": "sip:17406415881@callcentric.com", "message_tts": "This is a test messsage from HA"}
Converting audio file 'http://192.168.1.165:8123/api/tts_proxy/dc04f29fa6ecf5e059fd7c0471d55cb8e2a107d7_en_-_google_translate.mp3'...
Audio succesfully converted...
Starting SIP Client and calling 'sip:17406415881@callcentric.com'...
This call will be terminated after '50' seconds.
21:14:08.883         os_core_unix.c !pjlib 2.9 for POSIX initialized
21:14:08.883         sip_endpoint.c  .Creating endpoint instance...
21:14:08.883                  pjlib  .select() I/O Queue created (0x562bbe7e0c90)
21:14:08.883         sip_endpoint.c  .Module "mod-msg-print" registered
21:14:08.883        sip_transport.c  .Transport manager created.
21:14:08.883           pjsua_core.c  .PJSUA state changed: NULL --> CREATED
21:14:08.889           pjsua_core.c  .pjsua version 2.9 for Linux-5.4.44/x86_64 initialized
21:14:08.890            pjsua_app.c  .Turning sound device -99 -99 ON
21:14:08.890                 main.c  Ready: Success
21:14:08.908            pjsua_app.c  .......Call 0 state changed to CALLING
>>>>
Account list:
  [ 0] <sip:172.30.33.17:5060>: does not register
       Online status: Online
  [ 1] <sip:172.30.33.17:5060;transport=TCP>: does not register
       Online status: Online
 *[ 2] sip:17772265044101@callcentric.com: does not register
       Online status: Online
Buddy list:
 [ 1] <?>  sip:17406415881@callcentric.com
+=============================================================================+
|       Call Commands:         |   Buddy, IM & Presence:  |     Account:      |
|                              |                          |                   |
|  m  Make new call            | +b  Add new buddy       .| +a  Add new accnt |
|  M  Make multiple calls      | -b  Delete buddy         | -a  Delete accnt. |
|  a  Answer call              |  i  Send IM              | !a  Modify accnt. |
|  h  Hangup call  (ha=all)    |  s  Subscribe presence   | rr  (Re-)register |
|  H  Hold call                |  u  Unsubscribe presence | ru  Unregister    |
|  v  re-inVite (release hold) |  t  ToGgle Online status |  >  Cycle next ac.|
|  U  send UPDATE              |  T  Set online status    |  <  Cycle prev ac.|
| ],[ Select next/prev call    +--------------------------+-------------------+
|  x  Xfer call                |      Media Commands:     |  Status & Config: |
|  X  Xfer with Replaces       |                          |                   |
|  #  Send RFC 2833 DTMF       | cl  List ports           |  d  Dump status   |
|  *  Send DTMF with INFO      | cc  Connect port         | dd  Dump detailed |
| dq  Dump curr. call quality  | cd  Disconnect port      | dc  Dump config   |
|                              |  V  Adjust audio Volume  |  f  Save config   |
|  S  Send arbitrary REQUEST   | Cp  Codec priorities     |                   |
+-----------------------------------------------------------------------------+
|  q  QUIT   L  ReLoad   sleep MS   echo [0|1|txt]     n: detect NAT type     |
+=============================================================================+
You have 1 active call
Current call id=0 to sip:17406415881@callcentric.com [CALLING]
>>> 21:14:09.890            pjsua_app.c  .Turning sound device -99 -99 OFF
21:14:40.956            pjsua_app.c  ....Call 0 is DISCONNECTED [reason=408 (Request Timeout)]
21:14:40.956     pjsua_app_common.c  ....
  [DISCONNCTD] To: sip:17406415881@callcentric.com

**Comment by sdesalve** [comment]
Please try to place same call with microsip.com
Then, if not works, try pjsua custom options that I've tested for others VoIP providers.

Let me know how you fix with your provider

**Comment by sdesalve** [comment]
Please update this issue or close it if you've finded correct setup.

I'll appreciate if you share with me your config so I can update docs, If you don't want, close this
