### ISSUE TITLE
Dss VOIP NOTIFIER Autostart on boot won't work

### ISSUE THREAD

**Issue by antoweb** [sdesalve/hassio-addons#16]
DSS VOIP NOTIFIER. Rebooting ha the add-ons won't start itself

**Comment by sdesalve** [comment]
Add-on's startup is configured as 'application'. See attached picture

Please post more information about your configuration to get help. Nobody other has reported this issue

![Screenshot_2020-08-18-08-43-30-105_com android chrome](https://user-images.githubusercontent.com/9841662/90479703-5f7d9680-e12f-11ea-8d44-9de6fbefa232.jpg)

**Comment by skycordellaa** [comment]
Hello,
here is my log of add-on
You have 1 active call
Current call id=0 to sip:+393496233667@sip.messagenet.it [CALLING]
./run: line 337: echo: write error: Broken pipe
./run: line 337:   959 Exit 1                  ( sleep $MAX_CALL_TIME_VALUE; echo h; sleep 0.5; echo q )
       960 Segmentation fault      (core dumped) | ( pjsua --app-log-level=3 --config-file '/share/dss_voip/dss_pjsua.conf' $CALL_SIP_URI_VALUE 2> /share/dss_voip/dss_pjsua.log )
s6-svscanctl: fatal: unable to control /var/run/s6/services: supervisor not listening
>>> [cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

Attached is the screen that explain the status
![Cattura](https://user-images.githubusercontent.com/69196489/90493560-cce6f280-e142-11ea-8849-84cd349ec461.PNG)

**Comment by skycordellaa** [comment]
MY conf is like this:

sip_parameters:
  caller_id_uri: 'sip:MYID@sip.messagenet.it'
  realm: '*'
  username: 'MY_USERNAME'
  password: MY_PWD
pjsua_custom_options: '--outbound=sip:sip.messagenet.it:5061;lr'

**Comment by sdesalve** [comment]
please post addon's logs

eg:

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: DSS VoIP Notifier
 VoIP Notifier for HomeAssistant
-----------------------------------------------------------
 Add-on version: 3.3.3
 You are running the latest version of this add-on.
 System: HassOS 4.12  (armv7 / raspberrypi3)
 Home Assistant Core: 0.114.1
 Home Assistant Supervisor: 234
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[Info] Starting addon...
PJSUA_CUSTOM_OPTIONS = '--no-tcp --ip-addr=192.168.178.136'
[Info] Listening for messages via stdin service call...`

**Comment by sdesalve** [comment]
and /share/dss_voip/dss_pjsua.log file... obliviously remove any personal data

**Comment by skycordellaa** [comment]
Hello,
here is my addon log (after started)

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: DSS VoIP Notifier
 VoIP Notifier for HomeAssistant
-----------------------------------------------------------
 Add-on version: 3.3.3
 You are running the latest version of this add-on.
 System: HassOS 4.12  (armv7 / raspberrypi3)
 Home Assistant Core: 0.114.2
 Home Assistant Supervisor: 234
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[Info] Starting addon...
PJSUA_CUSTOM_OPTIONS = '--outbound=sip:sip.messagenet.it:5061;lr'
[Info] Listening for messages via stdin service call...




Here is dss_pjsua.log

sip_parameters = '{"caller_id_uri":"sip:MY_ID@sip.messagenet.it","realm":"*","username":"MY_USER","password":"MY_PWD"}'

**Comment by antoweb** [comment]
SOrry removed old post because used wrong username:

Hello,
here is my addon log (after started)

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing...
Add-on: DSS VoIP Notifier
VoIP Notifier for HomeAssistant
Add-on version: 3.3.3
You are running the latest version of this add-on.
System: HassOS 4.12 (armv7 / raspberrypi3)
Home Assistant Core: 0.114.2
Home Assistant Supervisor: 234
Please, share the above information when looking for help
or support in, e.g., GitHub, forums or the Discord chat.
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing...
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[Info] Starting addon...
PJSUA_CUSTOM_OPTIONS = '--outbound=sip:sip.messagenet.it:5061;lr'
[Info] Listening for messages via stdin service call...

Here is dss_pjsua.log

sip_parameters = '{"caller_id_uri":"sip:MY_ID@sip.messagenet.it","realm":"*","username":"MY_USER","password":"MY_PWD"}'

**Comment by sdesalve** [comment]
avvialo e posta il log.
Mi scrivi su telegram? facciamo prima http://t.me/sdesalve 

;)
