### ISSUE TITLE
Error with new version 3.3.3

### ISSUE THREAD

**Issue by Groovit** [sdesalve/hassio-addons#17]
Hi.
I installed the new version 3.3.3 and the addon doesn't work.
Nothing happen in the Log but I can read this message : Failed to call service "hassio / addon_stdin". required key not provided @ data ['addon']
What about this key ?

Regards

Michel

**Comment by Groovit** [comment]
Hi again. I found the problem.
But I have this log : 
jq: error (at <stdin>:1): Cannot index number with string "url"
parse error: Invalid numeric literal at line 1, column 13
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

Can you help me ?

**Comment by sdesalve** [comment]
Hi,

are you sure that your YAML is correct

You must call any addon from a script/automation with this code:
 ...
    - service: hassio.addon_stdin
      data_template:
        **addon: 89275b70_dss_voip**
        input: {"call_sip_uri":"sip:+393334455667@sipserver.com","message_tts":"Write here your message"}
...

I think it's not related to this addon... I think you have some typo on your code.

Let me know if you solve

**Comment by sdesalve** [comment]
> Hi again. I found the problem.
> But I have this log :
> jq: error (at :1): Cannot index number with string "url"
> parse error: Invalid numeric literal at line 1, column 13
> [cont-finish.d] executing container finish scripts...
> [cont-finish.d] 99-message.sh: executing...
> [cont-finish.d] 99-message.sh: exited 0.
> [cont-finish.d] done.
> [s6-finish] waiting for services.
> [s6-finish] sending all processes the TERM signal.
> 
> Can you help me ?

this should fixed with base_url in google TTS configuration. 
There have been some breaking changes on latest HomeAssistant updates and you must update your configuration

**Comment by Groovit** [comment]
Hi, it's better.
But the Log doens't write : Audio succesfully converted...
See ...
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[Info] Starting addon...
PLATFORM_TTS = 'amazon_polly'
[Info] Listening for messages via stdin service call...
[Info] Received messages {"call_duration": 15, "call_sip_uri": "sip:00002@gggggg.3cx.be", "message_tts": "Veuillez introduire votre code "}
CALL_DURATION = '15'
Converting audio file 'https://ssssss.gggggg.be:8123/api/tts_proxy/0a02b51a2a41e62b758a626103f5ee3eb73d338a_fr-fr_042a777f70_amazon_polly.mp3'...

And the file MP3 is really in the config/tts directory

Where is the problem?

Thanks

**Comment by sdesalve** [comment]
Please publish full logs.
Also you can found other logs on /shares/dss_voip folder

**Comment by Groovit** [comment]
Here the Log pjsua
8123/api/tts_proxy/5f35271e7c0ddca993b367e4202f8508ead1742c_fr-fr_042a777f70_amazon_polly.mp3PLATFORM_TTS = 'amazon_polly'
sip_parameters = '{"caller_id_uri":"sip:00001@gggggg.3cx.be","realm":"*","username":"lOhi6L4y2g7","password":"0fhLAosNsI"}'
[Info] Received messages '{"call_duration": 15, "call_sip_uri": "sip:00002@gggggg.3cx.be", "message_tts": "Bonjour il fait quel temps ?"}'
CALL_SIP_URI_VALUE = 'sip:00002@gggggg.3cx.be'
MESSAGE_TTS_VALUE = 'Bonjour il fait quel temps ?'
DATA_JSON = '{
  "message": "Bonjour il fait quel temps ?",
  "platform": "amazon_polly"
}'
JSONGOOGLETTS = '{"url": "https://ssssss.gggggg.be:8123/api/tts_proxy/5f35271e7c0ddca993b367e4202f8508ead1742c_fr-fr_042a777f70_amazon_polly.mp3"}'
URLFILEMP3_VALUE = 'https://ssssss.gggggg.be:8123/api/tts_proxy/5f35271e7c0ddca993b367e4202f8508ead1742c_fr-fr_042a777f70_amazon_polly.mp3'


Here Log sox :
sox:      SoX v14.4.2

Earlier I read Can't open the file .....mp3 but now after restart, nothing

Regards

**Comment by Groovit** [comment]
Here the directories:
~ $ cd config
config $ ls
automations.yaml      custom_components     groups.yaml           home-assistant_v2.db  scenes.yaml           secrets.yaml
configuration.yaml    deps                  home-assistant.log    node-red              scripts.yaml          tts
config $ cd tts
tts $ ls
0a02b51a2a41e62b758a626103f5ee3eb73d338a_fr-fr_042a777f70_amazon_polly.mp3  6a842768573d0fd69ed533551f05a7b1e60d203c_fr-fr_042a777f70_amazon_polly.mp3
3bb4cd06a7898fc0a33665f241cb48f2f2a192ac_fr_-_google_translate.mp3          8f1a41cdfaa2fad9001801934110537ee6995f1e_en_-_google_translate.mp3
5f35271e7c0ddca993b367e4202f8508ead1742c_fr-fr_042a777f70_amazon_polly.mp3
tts $
cd



~ $ cd share
share $ ls
dss_voip
share $ cd dss_voip
dss_voip $ ls
dss_pjsua.conf  dss_pjsua.log   dss_sox.log     dss_voip.conf
dss_voip $ nano dss_sox.log
dss_voip $

**Comment by sdesalve** [comment]
Remove username and password from this issue

Then, if you click on link
https://ssssss.gggggg.be:8123/api/tts_proxy/5f35271e7c0ddca993b367e4202f8508ead1742c_fr-fr_042a777f70_amazon_polly.mp3

You can hear MP3 TTS?

**Comment by sdesalve** [comment]
if you publish Addon full log I can see your host machine and other info. I can't see if you use HassOS on Raspberry or other configurations

**Comment by Groovit** [comment]
Yes I hear very well

**Comment by Groovit** [comment]
Where is the full log?

**Comment by sdesalve** [comment]
![Screenshot_2020-09-19-19-36-38-901_com android chrome~2](https://user-images.githubusercontent.com/9841662/93684618-ae607800-faaf-11ea-893b-8be3e9cf7100.jpg)
![Screenshot_2020-09-19-19-36-45-936_com android chrome~2](https://user-images.githubusercontent.com/9841662/93684642-b02a3b80-faaf-11ea-8799-ea88d244baad.jpg)

**Comment by Groovit** [comment]
Sorry I didn't know you wanted this.
We are Using NUC with Proxmox

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: DSS VoIP Notifier
 VoIP Notifier for HomeAssistant
-----------------------------------------------------------
 Add-on version: 3.3.3
 You are running the latest version of this add-on.
 System: HassOS 4.13  (amd64 / qemux86-64)
 Home Assistant Core: 0.115.1
 Home Assistant Supervisor: 245
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[Info] Starting addon...
PLATFORM_TTS = 'amazon_polly'
[Info] Listening for messages via stdin service call...
[Info] Received messages {"call_duration": 15, "call_sip_uri": "sip:00002@groovit.3cx.be", "message_tts": "Bonjour il fait quel temps ?"}
CALL_DURATION = '15'
Converting audio file 'https://stvincent.groovit.be:8123/api/tts_proxy/5f35271e7c0ddca993b367e4202f8508ead1742c_fr-fr_042a777f70_amazon_polly.mp3'...

**Comment by Groovit** [comment]
I didnt Know you wanted this.
I'm using NUC and Proxmox

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: DSS VoIP Notifier
 VoIP Notifier for HomeAssistant
-----------------------------------------------------------
 Add-on version: 3.3.3
 You are running the latest version of this add-on.
 System: HassOS 4.13  (amd64 / qemux86-64)
 Home Assistant Core: 0.115.1
 Home Assistant Supervisor: 245
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[Info] Starting addon...
PLATFORM_TTS = 'amazon_polly'
[Info] Listening for messages via stdin service call...
[Info] Received messages {"call_duration": 15, "call_sip_uri": "sip:00002@ggggg.3cx.be", "message_tts": "Bonjour il fait quel temps ?"}
CALL_DURATION = '15'
Converting audio file 'https://ssssss.gggggg.be:8123/api/tts_proxy/5f35271e7c0ddca993b367e4202f8508ead1742c_fr-fr_042a777f70_amazon_polly.mp3'...

**Comment by sdesalve** [comment]
Now what's the problem with call?

Call was not placed? Or phone ring, you answer but can't hear anything?

**Comment by Groovit** [comment]
I think you answer to an old issue.
For the issue we talked nothing better.
I have the file but addon doesn't call.

The log is blocked at and wait ...
Nothin after the last line.

[Info] Received messages {"call_duration": 15, "call_sip_uri": "sip:00002@gggggg.3cx.be", "message_tts": "Bonjour Veuillez introduire votre code dactage"}
CALL_DURATION = '15'
Converting audio file 'https://ssssss.ggggggt.be:8123/api/tts_proxy/6a842768573d0fd69ed533551f05a7b1e60d203c_fr-fr_042a777f70_amazon_polly.mp3'...

**Comment by sdesalve** [comment]
If you place a call, after converting audio file add-on will stay on and running but hangs?

Can you try to use Google TTS?

**Comment by Groovit** [comment]
When I put another URL with a wav file, it's working fine.
Maybe I need to convert only in Wav and not mp3

**Comment by sdesalve** [comment]
As docs explain, Sox is used to convert Google TTS MP3 into wav files... How do you convert Amazon Polly MP3? Or maybe that Amazon Polly MP3 is not compatible with Sox or you must customize in file/out file parameters

**Comment by Groovit** [comment]
I tried Google TTS and the same issue.
I have another older system installed without Proxmox and it's working very well with Amazon Polly also after upgrade.
I think the problem come from Sox.

**Comment by sdesalve** [comment]
Can you post your full /share/dss_voip/dss_sox.log file?

It's strange because you stated that if you use an external file everything will work very well. I use SOX either for TTS synthetized mp3 and for each **audio_file_url** 

Do you have any error in your /config/homeassistant.log files when you place a call?

**Comment by sdesalve** [comment]
Also seems that HomeAssistant 0.115.1 have many troubles... Please try also to downgrade

**Comment by Groovit** [comment]
We continue to try ...
We fond these in the Log of Home Assistant:

Logger: aiohttp.server
Source: components/tts/__init__.py:299
First occurred: 11:04:21 (1 occurrences)
Last logged: 11:04:21

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/tts/__init__.py", line 574, in post
    url = await self.tts.async_get_url(
  File "/usr/src/homeassistant/homeassistant/components/tts/__init__.py", line 299, in async_get_url
    provider = self.providers[engine]
KeyError: 'google_translate'

**Comment by sdesalve** [comment]
Please downgrade you HomeAssistant.
0.115.1 have many bugs for now...
