### ISSUE TITLE
max_call_time

### ISSUE THREAD

**Issue by dborsnich** [sdesalve/hassio-addons#19]
Great, great, addon, thanks!
I link with elastix pbx and works well
I have only a problem in max_call_time. It always have a duration of 50 seconds.
This is my config

sip_parameters:
  max_call_time: '10'
  caller_id_uri: 'sip:29@192.168.157.18'
  realm: '*'
  username: '29'
  password: XXXXXXXXXX

Thanks again!

**Comment by dborsnich** [comment]
Sorry, My hassio version   0.115.4 inside a proxmox virtual machine
HassOS 4.13

**Comment by sdesalve** [comment]
max_call_time must not be inserted as child of sip_parameters.

https://github.com/sdesalve/hassio-addons/tree/master/dss_voip#option-max_call_time-optional

Move it at the end of configuration without leading spaces at beginning

**Comment by dborsnich** [comment]
Thanks!

 

Now its working

 

 

 

Diego Borsnich          Director de Tecnologia         <http://www.diex.com.ar/> www.diex.com.ar

San Blas 1718    -    CABA  Tel. 3221-4321     -     Cel: 1540433132                   

  

                                     

 

 

 

De: sdesalve [mailto:notifications@github.com] 
Enviado el: Tuesday, September 29, 2020 9:00 AM
Para: sdesalve/hassio-addons <hassio-addons@noreply.github.com>
CC: dborsnich <diego@diex.com.ar>; Author <author@noreply.github.com>
Asunto: Re: [sdesalve/hassio-addons] max_call_time (#19)

 

max_call_time must not be inserted as child of sip_parameters.

https://github.com/sdesalve/hassio-addons/tree/master/dss_voip#option-max_call_time-optional

Move it at the end of configuration without leading spaces at beginning

**Comment by sdesalve** [comment]
PS: Please respect Creative Commons Attribution-NonCommercial licence...
If you will resell this work or any of their parts, you need my authorization

PS2: If you like my work and time I spent to help you...
![image](https://user-images.githubusercontent.com/9841662/77524769-3579be00-6e88-11ea-85ab-bf7d4aa5ddc2.png)


bye
SDeSalve

**Comment by dborsnich** [comment]
Yes, of course

 

Now i am testing in my hassio house, reporting alarm by phone

 

 

I am trying to find, a plus solution to manage hassio mqtt alarm by phone

 

Regards

 

Diego Borsnich          Director de Tecnologia         <http://www.diex.com.ar/> www.diex.com.ar

San Blas 1718    -    CABA  Tel. 3221-4321     -     Cel: 1540433132                   

  

                                     

 

 

 

De: sdesalve [mailto:notifications@github.com] 
Enviado el: Tuesday, September 29, 2020 11:13 AM
Para: sdesalve/hassio-addons <hassio-addons@noreply.github.com>
CC: dborsnich <diego@diex.com.ar>; Author <author@noreply.github.com>
Asunto: Re: [sdesalve/hassio-addons] max_call_time (#19)

 

PS: Please respect Creative Commons Attribution-NonCommercial licence...
If you will resell this work or any of their parts, you need my authorization

PS2: If you like my work and time I spent to help you...
 <https://user-images.githubusercontent.com/9841662/77524769-3579be00-6e88-11ea-85ab-bf7d4aa5ddc2.png> 

bye
SDeSalve
