### ISSUE TITLE
Docker version request

### ISSUE THREAD

**Issue by pippo73** [sdesalve/hassio-addons#22]
Hi Salvatore.
Could you implement a docker version of your add-on? 
Tnx

**Comment by sdesalve** [comment]
Unfortunately I’m not able to developing a Docker version. And afterwards it will not simple to invoke and make data check as it is with Hassio add-on.

But you can install and launch pjsua from within a bash script and place a call using as inspiration the “run” file from add-on’s GitHub

Bye
