### ISSUE TITLE
More of a feature request..

### ISSUE THREAD

**Issue by MIBmusic** [sdesalve/hassio-addons#23]
Hi, I am very happy with the DSS Voip Notifier, but is it possible to ignore invites? I am using the same SIP account as my SIP phone and the Voip Notifier answers all the calls.

**Comment by sdesalve** [comment]
Don't set sip_server_uri parameter


Option sip_parameters: sip_server_uri (Optional)
Set the URL of the registrar server. If set, addon will auto-answer to call and play a dummy audio so you can check system's status. An example of URL: "sip:sipserver.com"

**Comment by MIBmusic** [comment]
Thank you so much and I'm sorry for this. I totally overlooked it!
