### ISSUE TITLE
[Error] pjsua Exit code: 139

### ISSUE THREAD

**Issue by MNagler01** [sdesalve/hassio-addons#25]
Dear Salvatore,

Thank you for your great add-on. It works most of the time. But sometimes the above error appears.

I am attaching the relevant information:
[DSS_VoIP_Notifier_Log.txt](https://github.com/sdesalve/hassio-addons/files/5516410/DSS_VoIP_Notifier_Log.txt)
[DSS_VoIP_Notifier_Configuration..txt](https://github.com/sdesalve/hassio-addons/files/5516416/DSS_VoIP_Notifier_Configuration.txt)
[DSS_VoIP_Notifier_Script..txt](https://github.com/sdesalve/hassio-addons/files/5516417/DSS_VoIP_Notifier_Script.txt)

Thank you for your support
Michael

**Comment by sdesalve** [comment]
Hi, 
Should be related to pjsua compatibility with your sip server.

What kind of pbx do you have?
Can you share
/share/dss_voip/dss_pjsua.log file?

**Comment by MNagler01** [comment]
Dear Salvatore,

I have not installed any SIP servers. I use your ADD-on to make a phone call with the help of a LAN/WLAN device defined in my  FRITZ!Box 7590 with FRITZ!OS: 07.21.
How can I access the file /share/dss_voip/dss_pjsua.log? I was only able to look into the file with "sudo su nano" under Raspbian Buster. It contains 65 lines with error messages related to ALSA.

Michael

**Comment by sdesalve** [comment]
There must be a /share folder. I'm using Samba add-on to access /share folder.

Have you checked if error will raise if phone line is busy or other replicable circumstances?

**Comment by MNagler01** [comment]
Dear Salvatore,

unfortunately, I cannot reproduce the error message at the moment. I add the file /share/dss_voip/dss_pjsua.log:
[dss_pjsua.log](https://github.com/sdesalve/hassio-addons/files/5517830/dss_pjsua.log)
If the error occurs again, I'll back up this file immediately.

Michael
