### ISSUE TITLE
Monocle add on

### ISSUE THREAD

**Issue by thomasgregg** [sdesalve/hassio-addons#27]
Installed it and entered the token. But when I start the add on I get the following error message:

`[Info] Starting addon...
[Info] monocle.token file was successfully created...
[Info] Starting Monocle Gateway service...
/run.sh: line 24: /usr/local/bin/monocle-gateway: cannot execute binary file: Exec format error
`

**Comment by sdesalve** [comment]
Host machine?

**Comment by thomasgregg** [comment]
I am running Home Assistant OS 64bit on a Raspberry Pi 4 Model B.

**Comment by sdesalve** [comment]
Unfortunately monocle executables was not available for ARM processor.

https://community.home-assistant.io/t/new-addon-dss-monocle-gateway/251651/5

Sorry
