### ISSUE TITLE
How to call home assistant?

### ISSUE THREAD

**Issue by art2802** [sdesalve/hassio-addons#29]
Can I call the Home Assistant from my mobile phone?
And get into an interactive menu that will be controlled by voice?
In the current version, the call takes place without registering on the server. I would like to establish two-way communication.

**Comment by sdesalve** [comment]
The Addon will register to SIP server and will answer to  incoming calls with sip_server_uri option:

https://github.com/sdesalve/hassio-addons/tree/master/dss_voip#option-sip_parameters-sip_server_uri-optional

But you can't use it to control Home Assistant , neither recognise incoming calls and neither create any IVR or interactive menues. Pjsua executable is not suitable for this kind of use
