### ISSUE TITLE
The Add-on restarts on every outgoing call with Messagenet

### ISSUE THREAD

**Issue by systemiii** [sdesalve/hassio-addons#30]
When I run the service to make an outgoing call, the call don't start and I read that a TERM signal has been sent in the log.

![Immagine](https://user-images.githubusercontent.com/57064524/102672383-ecddff80-4190-11eb-8e4a-26ab936d69b3.jpg)

**Comment by sdesalve** [comment]
Please post full log. So I can read SO.

Also post Sox and pjsua logs that you will find in /shares folder

**Comment by systemiii** [comment]
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: DSS VoIP Notifier
 VoIP Notifier for Home Assistant
-----------------------------------------------------------
 Add-on version: 3.4.3
 You are running the latest version of this add-on.
 System: Home Assistant OS 5.8  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2020.12.1
 Home Assistant Supervisor: 2020.12.7
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[Info] Starting addon...
PJSUA_CUSTOM_OPTIONS = '--outbound=sip:sip.messagenet.it:5061;lr'
[Info] Listening for messages via stdin service call...
[Info] Received messages {"call_sip_uri": "sip:+39XXXXXXXXXX@sipserver.com", "message_tts": "Write here your message"}
Converting audio file 'http://192.168.253.1/api/tts_proxy/3bb4cd06a7898fc0a33665f241cb48f2f2a192ac_it_-_google_translate.mp3'...
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[dss_pjsua.log](https://github.com/sdesalve/hassio-addons/files/5719118/dss_pjsua.log)
[dss_sox.log](https://github.com/sdesalve/hassio-addons/files/5719119/dss_sox.log)

**Comment by sdesalve** [comment]
Obviously if you click on MP3 file URL you can't hear anything, it's true?

http://192.168.253.1/api/tts_proxy/3bb4cd06a7898fc0a33665f241cb48f2f2a192ac_it_-_google_translate.mp3


I think you must add on Google TTS configuration the base_url parameter

**Comment by sdesalve** [comment]
![Screenshot_2020-12-19-10-37-21-303_com android chrome](https://user-images.githubusercontent.com/9841662/102686852-b3d27900-41ea-11eb-8483-bb8f0556a5b2.jpg)

**Comment by systemiii** [comment]
Thanks for the great tip. I had installed the NGINX add-on a few days ago, so the "base_url" parameter is now very important.
Now your add-on works perfectly.
