### ISSUE TITLE
Wont start on Hassos 5.10 logs filling up with execlineb: usage: execlineb

### ISSUE THREAD

**Issue by rubkec** [sdesalve/hassio-addons#33]
Hassos 5.10

wont start, filling up log with `execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args`

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: DSS VoIP Notifier
 VoIP Notifier for Home Assistant
-----------------------------------------------------------
 Add-on version: 3.5.3
 You are running the latest version of this add-on.
 System: Home Assistant OS 5.10  (amd64 / qemux86-64)
 Home Assistant Core: 2021.1.5
 Home Assistant Supervisor: 2021.01.7
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
exec: fatal: unable to exec bashio
: No such file or directory
execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
[services.d] done.
exec: fatal: unable to exec bashio
: No such file or directory
execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
```

tried to reset, and rebuild
also the logo is not displayed at the add-on store.

**Comment by sdesalve** [comment]
did you have downloaded my addon and trying to run it from your /addons folder?

Don't seems to be relate to my addon but to an corrupted installation of Hassio

**Comment by rubkec** [comment]
no just from the add-on store... the other logo of the addon is displayed fine
![image](https://user-images.githubusercontent.com/56980377/105839779-462c2080-5fd2-11eb-92ee-f71fa5c0eba9.png)


is there something that i can do to completly remove the addon from the hassos cli?

**Comment by sdesalve** [comment]
> is there something that i can do to completly remove the addon from the hassos cli?
Uninstall it and restart host machine

> could there be any problem
I've experienced issue after restoring HomeAssistant snapshot from a ResinOS setup to a HassOS setup. 
Try to unistall addon and restart host machine

**Comment by rubkec** [comment]
![image](https://user-images.githubusercontent.com/56980377/105841451-e5eaae00-5fd4-11eb-8258-1eb5b2995cb4.png)

same error, supervisor log looks clear

**Comment by rubkec** [comment]
did a clean install of Hassos 5.10

no restore, added the repository
no logo for the voip add-on

![image](https://user-images.githubusercontent.com/56980377/105842369-5645ff00-5fd6-11eb-9b04-2dcb8848d224.png)

same error, no add-ons installed no empry config of hass-os

**Comment by rubkec** [comment]
also mentioned by a user on the hass community 
https://community.home-assistant.io/t/new-addon-dss-voip-notifier-hassio-makes-phone-calls-to-you/130993/226

**Comment by Lemming16** [comment]
Having the same issue. 
I tried to run it as local Addon as well as from the store, same issue.

**Comment by sdesalve** [comment]
would you try to install old version?

https://github.com/sdesalve/hassio-addons/tree/master/dss_voip34

You'll find in my addon repository

![image](https://user-images.githubusercontent.com/9841662/105878431-560f2900-6001-11eb-9828-d90f9e2048e9.png)

**Comment by rubkec** [comment]
works, starts correctly!

**Comment by rubkec** [comment]
3.5.5 works
