### ISSUE TITLE
Unable to install on HA on docker

### ISSUE THREAD

**Issue by fedepupo** [sdesalve/hassio-addons#34]
OrangePi PC+ with armbian buster
Docker version 20.10.2, build 2291f61
Home Assistant 2021.1.5
Supervisor 2021.01.7

> `21-02-01 16:06:48 INFO (SyncWorker_0) [supervisor.docker.addon] Starting build for 89275b70/armv7-addon-dss_voip:3.5.5
> 21-02-01 16:06:57 ERROR (SyncWorker_0) [supervisor.docker.addon] Can't build 89275b70/armv7-addon-dss_voip:3.5.5: The command '/bin/ash -o pipefail -c apk add --no-cache     coreutils=8.32-r2     wget=1.21.1-r1     sox     pjsua     screen     bc' returned a non-zero code: 6
> 21-02-01 16:06:57 ERROR (SyncWorker_0) [supervisor.docker.addon] Build log: 
> Step 1/20 : ARG BUILD_FROM=ghcr.io/hassio-addons/base/amd64:9.1.1
> 
> 
> Step 2/20 : FROM ${BUILD_FROM}
> 
> 
>  ---> b1eeb69a4c14
> 
> Step 3/20 : ENV     S6_BEHAVIOUR_IF_STAGE2_FAILS=2     S6_CMD_WAIT_FOR_SERVICES=1     TERM="xterm-256color"
> 
> 
>  ---> Using cache
> 
>  ---> 1f8ed3a0f9f2
> 
> Step 4/20 : ENV LANG C.UTF-8
> 
> 
>  ---> Using cache
> 
>  ---> 8419eccf1d1a
> 
> Step 5/20 : COPY rootfs /
> 
> 
>  ---> Using cache
> 
>  ---> 92870261416f
> 
> Step 6/20 : RUN apk add --no-cache     coreutils=8.32-r2     wget=1.21.1-r1     sox     pjsua     screen     bc
> 
> 
>  ---> Running in 2e325135f874
> 
> fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/armv7/APKINDEX.tar.gz
> 
> 3070006160:error:0D0D90AD:asn1 encoding routines:ASN1_TIME_adj:error getting time:crypto/asn1/a_time.c:330:
> 3070006160:error:0D0D90AD:asn1 encoding routines:ASN1_TIME_adj:error getting time:crypto/asn1/a_time.c:330:
> 3070006160:error:0D0D90AD:asn1 encoding routines:ASN1_TIME_adj:error getting time:crypto/asn1/a_time.c:330:
> 3070006160:error:0D0D90AD:asn1 encoding routines:ASN1_TIME_adj:error getting time:crypto/asn1/a_time.c:330:
> 
> 3070006160:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1913:
> 
> WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/main: Permission denied
> 
> fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/armv7/APKINDEX.tar.gz
> 
> WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/community: temporary error (try again later)
> 
> ERROR: unable to select packages:
> 
>   bc (no such package):
>     required by: world[bc]
>   coreutils (no such package):
>     required by: world[coreutils=8.32-r2]
>   pjsua (no such package):
>     required by: world[pjsua]
>   screen (no such package):
>     required by: world[screen]
>   sox (no such package):
>     required by: world[sox]
>   wget (no such package):
>     required by: world[wget=1.21.1-r1]
> 
> Removing intermediate container 2e325135f874`

**Comment by sdesalve** [comment]
bc (no such package):
required by: world[bc]
coreutils (no such package):
required by: world[coreutils=8.32-r2]
pjsua (no such package):
required by: world[pjsua]
screen (no such package):
required by: world[screen]
sox (no such package):
required by: world[sox]
wget (no such package):
required by: world[wget=1.21.1-r1]

Seems that your hassio cannot install successfully any bin package. It's a big issue that your docker cannot install wget, coreutils and other hassio standard APK

Do you have ever installed previous version? Can you successfully install hassio add-on example?

**Comment by fedepupo** [comment]
i've installed others add-on (ex. Dropbox Sync, ZeroTier One, Zigbee2mqtt)

**Comment by MNagler01** [comment]
Dear Salvatore,

I have the same issues:

Raspberry Pi 3 B
Raspbian GNU/Linux 10 (buster)
Docker 20.10.3 
Home Assistant: 2021.1.5
Supervisor 2021.01.7

[Supervisor_Log.txt](https://github.com/sdesalve/hassio-addons/files/5918066/Supervisor_Log.txt)

Thank you for your support.
Mike

**Comment by sdesalve** [comment]
install this version

https://github.com/sdesalve/hassio-addons/tree/master/dss_voip34

**Comment by fedepupo** [comment]
> install this version
> 
> https://github.com/sdesalve/hassio-addons/tree/master/dss_voip34

with this version i've this error exec: 
```
fatal: unable to exec bashio: No such file or directory
execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
```

**Comment by sdesalve** [comment]
```
21-02-03 18:31:00 INFO (MainThread) [supervisor.addons] Creating Home Assistant add-on data folder /data/addons/data/89275b70_dss_voip34
21-02-03 18:31:00 INFO (SyncWorker_3) [supervisor.docker.addon] Starting build for 89275b70/amd64-addon-dss_voip34:3.4.3
21-02-03 18:31:30 INFO (SyncWorker_3) [supervisor.docker.addon] Build 89275b70/amd64-addon-dss_voip34:3.4.3 done
21-02-03 18:31:30 INFO (MainThread) [supervisor.addons] Add-on '89275b70_dss_voip34' successfully installed
```

@fedepupo could you try now?

**Comment by fedepupo** [comment]
Thanks man
Now it's work

**Comment by sdesalve** [comment]
Until I don't understand what's the issue with new add-on configuration you can use this version
