### ISSUE TITLE
Pass states as message

### ISSUE THREAD

**Issue by oalbaf** [sdesalve/hassio-addons#35]
Hi,

Congratulations on your work.

Is it possible to send the status of a sensor by tts message in DSS VoIP?

Thank you very much!

**Comment by sdesalve** [comment]
obviously!

   ...
    - service: hassio.addon_stdin
      data_template:
        addon: 89275b70_dss_voip
        input: {"call_sip_uri":"sip:+393334455667@sipserver.com","message_tts":"Sensor value is {{ states('sensor.your_sensor_entity_id') }}"}
   ...
   
are the basic Hassio procedures!
