### ISSUE TITLE
use plugin with security alarm

### ISSUE THREAD

**Issue by monsterciattolo** [sdesalve/hassio-addons#37]
Hello,
I'd like to use this plugin to call security alarm system and use number (tones) active or deactivate the programs.
I use the same system on iPhone adding , (as 2 seconds time) or # (to hang up).
do you know if there is a way to do that?

Thanks

**Comment by sdesalve** [comment]
You can play an MP3 file with DTMF tones but it's not reliable because you can't know when alarm system pickup call
