### ISSUE TITLE
DSS Monocle Gateway not installing

### ISSUE THREAD

**Issue by leopold005** [sdesalve/hassio-addons#38]
I'm interested in this add-on as I've got a Monocle gateway running and would like to see how this interacts with HA.  Unfortunately, every time I try to install it, I get this message in the system log:

> 21-04-13 19:53:08 INFO (SyncWorker_4) [supervisor.docker.addon] Starting build for 89275b70/amd64-addon-dss_monocle-gateway:0.13.0
> 21-04-13 19:53:19 ERROR (SyncWorker_4) [supervisor.docker.addon] Can't build 89275b70/amd64-addon-dss_monocle-gateway:0.13.0: Head https://registry-1.docker.io/v2/hassioaddons/base-amd64/manifests/8.0.3: dial tcp: lookup registry-1.docker.io on 90.255.255.90:53: read udp 192.168.1.5:58768->90.255.255.90:53: i/o timeout
> 21-04-13 19:53:19 ERROR (SyncWorker_4) [supervisor.docker.addon] Build log: 
> Step 1/19 : ARG BUILD_FROM=hassioaddons/base:8.0.3
> Step 2/19 : FROM ${BUILD_FROM}

I'm not sure why this won't work.  Any ideas?

HASS version 2021.3.4 (supervised)
Debian Buster 20.14 (AMD64 version) running on Intel thin client
Docker version 20.10.5

**Comment by sdesalve** [comment]
https://forums.docker.com/t/docker-login-dial-tcp-lookup-index-docker-io-read-udp-i-o-timeout/14844/20


![Screenshot_2021-04-13-22-22-06-796_com android chrome](https://user-images.githubusercontent.com/9841662/114616190-df500680-9ca6-11eb-80b4-c9a07333b910.jpg)


I think that is a problem of your host machine. Try add to your host file a record or reset your docker

**Comment by leopold005** [comment]
I rebooted my HA box a couple of times just now and it's worked.  Must've been a glitch.  Thanks for the quick response :)
