### ISSUE TITLE
Problem with telecomitalia parameters

### ISSUE THREAD

**Issue by edilorenzo88** [sdesalve/hassio-addons#40]
hi,
I have installed the add-on but ihave the problem with del isp parameters

this is my parameters:

SIP Domain : telecomitalia.it
Outbound Proxy: d91s2.co.imsw.telecomitalia.it
SIP Protocol : UDP Port 5060
Username: +39XXXmytelnumber
Sipkey: xxxxxxxx ( is the password)

when I start the scriptm recived thi error in the log;

15:48:41.340        tsx0x7f903c2bc8  ....Failed to send Request msg INVITE/cseq=18699 (tdta0x7f903bca58)! err=70018 (gethostbyname() has returned error (PJ_ERESOLVE))
15:48:41.341            pjsua_app.c  .......Call 0 is DISCONNECTED [reason=502 (gethostbyname() has returned error (PJ_ERESOLVE))]
15:48:41.341     pjsua_app_common.c  .......
  [DISCONNCTD] To: sip:+39xxxxxxxxxx@d91s2.co.imsw.telecomitalia.it
    Call time: 00h:00m:00s, 1st res in 5005 ms, conn in 0ms
15:48:41.341            pjsua_app.c !.Turning sound device -99 -99 OFF
>>>>
Account list:
  [ 0] <sip:172.30.33.12:5060>: does not register
       Online status: Online
 *[ 1] sip:+39xxxxxxxxx@telecomitalia.it: does not register
       Online status: Online
Buddy list:
 [ 1] <?>  sip:+39xxxxxxxxxx@d91s2.co.imsw.telecomitalia.it

i tried to reverse the outbound proxy and the sip domain in the script and in the addon's configuration.

can you help me?

**Comment by sdesalve** [comment]
[reason=502 (gethostbyname() has returned error (PJ_ERESOLVE))]

Your HassiOS can't resolve "telecomitalia.it"

It's TIM and their DNS weird VOIP's configuration. You MUST use DNS provided by TIM and set outbound proxy returned by theirs systems.

I don't own a TIM line so I can't try. But you must try to set one of the following 

--proxy="sip:proxy.example.com;lr"
--outbound="sip:proxy.example.com;lr"

**Comment by sdesalve** [comment]
I suggest you to try configuration with microsip.org and then copy working parameters to this addon.

Otherwise use a FritzBox or other local pbx configured to use your line
