### ISSUE TITLE
Problem during installation on 

### ISSUE THREAD

**Issue by maframan** [sdesalve/hassio-addons#41]
I receive below error during first installation via Home Assistant webgui:

The command '/bin/ash -o pipefail -c apk add --no-cache coreutils=8.32-r2 wget=1.21.1-r1 sox pjsua screen bc' returned a non-zero code: 6

Home assistant component version:
- core: core-2021.7.3
- supervisor: supervisor-2021.06.8

Home assistant running on debian versione 10.10 (Raspbian GNU/Linux 10 bluster) with kernel 5.10.17-v7l+ 

Thanks and regards
Francesco

**Comment by sdesalve** [comment]
Hi Francesco,
Your home assistant setup is not supported from HA development team... Like they stated in their blog "Result are not predictable and support will not be granted"

Anyway could you try to install any other add-on to check your system is fully functionally?
Try to install this https://github.com/hassio-addons/addon-example

Have you tried to restart home assistant and your host system?
