### ISSUE TITLE
Cannot perform any call

### ISSUE THREAD

**Issue by matfil92** [sdesalve/hassio-addons#42]
Hi,
when I try to make some call with this code:

`service: hassio.addon_stdin
data:
  addon: 89275b70_dss_voip
  input: {'call_sip_uri':'sip:00393NUMBER@sip.discountvoip.co.uk','message_tts':'Write here your message'}
`

In the log I've this error: "jq: error (at <stdin>:1): Cannot index number with string "url"
parse error: Invalid numeric literal at line 1, column 13"

And full log is

`-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[Info] Starting addon...
PJSUA_CUSTOM_OPTIONS = '--no-tcp'
[Info] Listening for messages via stdin service call...
[Info] Received messages {"call_sip_uri": "sip:0039392NUMBER@sip.discountvoip.co.uk", "message_tts": "Write here your message"}
jq: error (at <stdin>:1): Cannot index number with string "url"
parse error: Invalid numeric literal at line 1, column 13
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.`

**Comment by sdesalve** [comment]
Please post full logs.

I fear it's a trouble with your incorrect TTS config

**Comment by matfil92** [comment]
This is the full log of the DSS component

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: DSS VoIP Notifier
 VoIP Notifier for Home Assistant
-----------------------------------------------------------
 Add-on version: 3.5.9
 You are running the latest version of this add-on.
 System: Home Assistant OS 6.4  (amd64 / qemux86-64)
 Home Assistant Core: 2021.9.7
 Home Assistant Supervisor: 2021.09.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[Info] Starting addon...
PJSUA_CUSTOM_OPTIONS = '--no-tcp'
[Info] Listening for messages via stdin service call...
[Info] Received messages {"call_sip_uri": "sip:+393926980654@sip.discountvoip.co.uk", "message_tts": "Prova messaggio"}
jq: error (at <stdin>:1): Cannot index number with string "url"
parse error: Invalid numeric literal at line 1, column 13
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.`

**Comment by matfil92** [comment]
> Please post full logs.
> 
> I fear it's a trouble with your incorrect TTS config

Why have you closed?

**Comment by sdesalve** [comment]
Have you setup Google TTS like stated in docs?
Could you post your Google TTS config, info about your HA like if you have a third level duckdns domain, SSL, add-ons for duckdns and letsencrypt?
Could you post add-on configuration?

Otherwise I'm not able to trace and resolve you problems

**Comment by sdesalve** [comment]
And please also post your /share/dss_voip/dss_pjsua.log file

Obviously censorw your private info

**Comment by sdesalve** [comment]
do you need help anymore?

**Comment by matfil92** [comment]
No please close it

Il giorno mer 29 set 2021 alle ore 20:11 sdesalve ***@***.***>
ha scritto:

**Comment by sdesalve** [comment]
Can I ask you what's the problem with your configuration?

**Comment by matfil92** [comment]
I haven't solved I'm not able

Il giorno ven 1 ott 2021 alle 07:26 sdesalve ***@***.***> ha
scritto:

**Comment by sdesalve** [comment]
If you want to solve please post your logs, add-on configuration and TTS setup... 
Otherwise I'm not able to help you...
