### ISSUE TITLE
SIP does not register with FreeVoipDeal

### ISSUE THREAD

**Issue by jarlesb** [sdesalve/hassio-addons#45]
Hi,

I have an issue with the addon and FreeVoipDeal.com. It seems that my user does not register... Any advice?

Version | core-2021.12.8
-- | --
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.9.7
Operating System Family | Linux
Operating System Version | 5.10.88
CPU Architecture | aarch64
Timezone | Europe/Oslo

Here is my code and config:

```
sip_parameters:
  caller_id_uri: sip:+xxxx@sip.freevoipdeal.com
  realm: '*'
  username: xxxxx
  password: xxxxx
pjsua_custom_options: '--no-tcp'

```

```
tts:
  - platform: google_translate
    language: "no"
```

```
service: hassio.addon_stdin
data:
  addon: 89275b70_dss_voip
  input: {"call_sip_uri":"sip:xxxx@sip.freevoipdeal.com","message_tts":"Test alarm"}   
```

And logs after call:

```
[Info] Received messages {"call_sip_uri": "sip:XXXXXX@sip.freevoipdeal.com", "message_tts": "Test alarm"}
Converting audio file 'https://XXXXXX:8123/api/tts_proxy/8fc433812a81ce0f10ff053da94783f9b849fb84_no_-_google_translate.mp3'...
Audio succesfully converted...
Starting SIP Client and calling 'sip:XXXXXX@sip.freevoipdeal.com'...
This call will be terminated after '50' seconds.
22:51:33.085         os_core_unix.c !pjlib 2.11.1 for POSIX initialized
22:51:33.085         sip_endpoint.c  .Creating endpoint instance...
22:51:33.085                  pjlib  .select() I/O Queue created (0xffffb2506100)
22:51:33.085         sip_endpoint.c  .Module "mod-msg-print" registered
22:51:33.085        sip_transport.c  .Transport manager created.
22:51:33.085           pjsua_core.c  .PJSUA state changed: NULL --> CREATED
22:51:33.095           pjsua_core.c  .pjsua version 2.11.1 for Linux-5.10.88/aarch64 initialized
22:51:33.098            pjsua_app.c  .Turning sound device -99 -99 ON
22:51:33.099                 main.c  Ready: Success
22:51:33.100            pjsua_app.c  .......Call 0 state changed to CALLING
>>>>
Account list:
  [ 0] <sip:172.30.33.8:5060>: does not register
       Online status: Online
 *[ 1] sip:XXXXXX@sip.freevoipdeal.com: does not register
       Online status: Online
Buddy list:
 [ 1] <?>  sip:XXXXXX@sip.freevoipdeal.com
+=============================================================================+
|       Call Commands:         |   Buddy, IM & Presence:  |     Account:      |
|                              |                          |                   |
|  m  Make new call            | +b  Add new buddy       .| +a  Add new accnt |
|  M  Make multiple calls      | -b  Delete buddy         | -a  Delete accnt. |
|  a  Answer call              |  i  Send IM              | !a  Modify accnt. |
|  h  Hangup call  (ha=all)    |  s  Subscribe presence   | rr  (Re-)register |
|  H  Hold call                |  u  Unsubscribe presence | ru  Unregister    |
|  v  re-inVite (release hold) |  t  ToGgle Online status |  >  Cycle next ac.|
|  U  send UPDATE              |  T  Set online status    |  <  Cycle prev ac.|
| ],[ Select next/prev call    +--------------------------+-------------------+
|  x  Xfer call                |      Media Commands:     |  Status & Config: |
|  X  Xfer with Replaces       |                          |                   |
|  #  Send RFC 2833 DTMF       | cl  List ports           |  d  Dump status   |
|  *  Send DTMF with INFO      | cc  Connect port         | dd  Dump detailed |
| dq  Dump curr. call quality  | cd  Disconnect port      | dc  Dump config   |
|                              |  V  Adjust audio Volume  |  f  Save config   |
|  S  Send arbitrary REQUEST   | Cp  Codec priorities     |                   |
+-----------------------------------------------------------------------------+
|  q  QUIT   L  ReLoad   sleep MS   echo [0|1|txt]     n: detect NAT type     |
+=============================================================================+
You have 1 active call
Current call id=0 to sip:XXXXXX@sip.freevoipdeal.com [CALLING]
>>> 22:51:33.125      tsx0xffffb179c6d8  .......Temporary failure in sending Request msg INVITE/cseq=10361 (tdta0xffffb1795aa8), will try next server: Unsupported transport (PJSIP_EUNSUPTRANSPORT)
22:51:34.099            pjsua_app.c  .Turning sound device -99 -99 OFF
22:52:05.125            pjsua_app.c  ....Call 0 is DISCONNECTED [reason=408 (Request Timeout)]
No current call
>>> 22:52:24.604                timer.c  .Dumping timer heap:
22:52:24.604                timer.c  .  Cur size: 0 entries, max: 3070
[Info] Call ended...
[Info] Listening for messages via stdin service call...
```

**Comment by sdesalve** [comment]
>TTS

Add base config with your duckdns domain

Then try to enable sip call within freevoipdeal
![Screenshot_2022-01-18-23-39-36-151_com android chrome](https://user-images.githubusercontent.com/9841662/150030514-c69d1b47-0ba8-4b71-8902-6d16e6e3171a.jpg)

**Comment by sdesalve** [comment]
Logs while addon starting?

**Comment by jarlesb** [comment]
Thanks a lot for quick reply!!

SIP was already enabled at FreeVoipDeal. I have now also added to my Google TTS config. However still does not work...

Please see below for config and logs:

```
sip_parameters:
  caller_id_uri: sip:+xxxx@sip.freevoipdeal.com
  realm: '*'
  username: xxxxx
  password: xxxxx
pjsua_custom_options: '--no-tcp'
```

```
tts:
  - platform: google_translate
    service_name: google_translate_say
    language: "no"
    base_url: https://XXXX.duckdns.org
```

```
service: hassio.addon_stdin
data:
  addon: 89275b70_dss_voip
  input: {"call_sip_uri":"sip:xxxx@sip.freevoipdeal.com","message_tts":"Test alarm"}
```

Addon startup:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: DSS VoIP Notifier
 VoIP Notifier for Home Assistant
-----------------------------------------------------------
 Add-on version: 3.5.9
 You are running the latest version of this add-on.
 System: Home Assistant OS 7.1  (aarch64 / odroid-n2)
 Home Assistant Core: 2021.12.10
 Home Assistant Supervisor: 2021.12.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[Info] Starting addon...
PJSUA_CUSTOM_OPTIONS = '--no-tcp'
[Info] Listening for messages via stdin service call...
```

For call:
```
[Info] Received messages {"call_sip_uri": "sip:XXXX@sip.freevoipdeal.com", "message_tts": "Tester alarmen"}
Converting audio file 'https://XXXX/api/tts_proxy/21f2c8b9ae58eaa9657e29158eb6133f23f3a755_no_-_google_translate.mp3'...
Audio succesfully converted...
Starting SIP Client and calling 'sip:XXXX@sip.freevoipdeal.com'...
This call will be terminated after '50' seconds.
15:41:24.346         os_core_unix.c !pjlib 2.11.1 for POSIX initialized
15:41:24.347         sip_endpoint.c  .Creating endpoint instance...
15:41:24.347                  pjlib  .select() I/O Queue created (0xffff8d3d4100)
15:41:24.347         sip_endpoint.c  .Module "mod-msg-print" registered
15:41:24.347        sip_transport.c  .Transport manager created.
15:41:24.347           pjsua_core.c  .PJSUA state changed: NULL --> CREATED
15:41:24.357           pjsua_core.c  .pjsua version 2.11.1 for Linux-5.10.88/aarch64 initialized
15:41:24.360            pjsua_app.c  .Turning sound device -99 -99 ON
15:41:24.360                 main.c  Ready: Success
15:41:24.392            pjsua_app.c  .......Call 0 state changed to CALLING
>>>>
Account list:
  [ 0] <sip:172.30.33.8:5060>: does not register
       Online status: Online
 *[ 1] sip:+XXXX@sip.freevoipdeal.com: does not register
       Online status: Online
Buddy list:
 [ 1] <?>  sip:XXXX@sip.freevoipdeal.com
+=============================================================================+
|       Call Commands:         |   Buddy, IM & Presence:  |     Account:      |
|                              |                          |                   |
|  m  Make new call            | +b  Add new buddy       .| +a  Add new accnt |
|  M  Make multiple calls      | -b  Delete buddy         | -a  Delete accnt. |
|  a  Answer call              |  i  Send IM              | !a  Modify accnt. |
|  h  Hangup call  (ha=all)    |  s  Subscribe presence   | rr  (Re-)register |
|  H  Hold call                |  u  Unsubscribe presence | ru  Unregister    |
|  v  re-inVite (release hold) |  t  ToGgle Online status |  >  Cycle next ac.|
|  U  send UPDATE              |  T  Set online status    |  <  Cycle prev ac.|
| ],[ Select next/prev call    +--------------------------+-------------------+
|  x  Xfer call                |      Media Commands:     |  Status & Config: |
|  X  Xfer with Replaces       |                          |                   |
|  #  Send RFC 2833 DTMF       | cl  List ports           |  d  Dump status   |
|  *  Send DTMF with INFO      | cc  Connect port         | dd  Dump detailed |
| dq  Dump curr. call quality  | cd  Disconnect port      | dc  Dump config   |
|                              |  V  Adjust audio Volume  |  f  Save config   |
|  S  Send arbitrary REQUEST   | Cp  Codec priorities     |                   |
+-----------------------------------------------------------------------------+
|  q  QUIT   L  ReLoad   sleep MS   echo [0|1|txt]     n: detect NAT type     |
+=============================================================================+
You have 1 active call
Current call id=0 to sip:XXXX@sip.freevoipdeal.com [CALLING]

>>> 15:41:24.421            pjsua_app.c  .....Call 0 is DISCONNECTED [reason=404 (User not found)]
15:41:25.360            pjsua_app.c  .Turning sound device -99 -99 OFF
No current call
>>> 15:42:15.865                timer.c  .Dumping timer heap:
15:42:15.865                timer.c  .  Cur size: 0 entries, max: 3070
[Info] Call ended...
[Info] Listening for messages via stdin service call...
```

**Comment by sdesalve** [comment]
reason=404 (User not found)]


Check freevoipdeal deal data

**Comment by sdesalve** [comment]
Sorry

call_sip_uri":"sip:xxxx@sip.freevoipdeal.com...

Here you must write a landline/mobile phone number

Eg.+3933333333
Check what numbers format will require freevoipdeal from addon docs

**Comment by jarlesb** [comment]
the XXXX was just removed for privacy. I used a normal number with +47 first. Now I got the following error:

reason=408 (Request Timeout)

**Comment by jarlesb** [comment]
Can it be that the firewall blocks SIP communication?

**Comment by jarlesb** [comment]
But what is strange is that I still get the caller_id does not register....

**Comment by sdesalve** [comment]
It's Normal that it will not register as a client. It will place only calls...

The --no-tcp option is mandatory as docs and is correctly recognised... 

Do you have a Fritz box? Is there an option to block sip traffic...

**Comment by jarlesb** [comment]
No, I have an Asus zenwifi router

**Comment by sdesalve** [comment]
Is there a firewall?
Do you have enough credit balance for this call?
Have you tried another sip client within your LAN with same sip parameters?

**Comment by sdesalve** [comment]
Dss_voipnotifier34

I see now that you use an odroid-m2 host machine. Please try the other version

**Comment by jarlesb** [comment]
> Is there a firewall? Do you have enough credit balance for this call? Have you tried another sip client within your LAN with same sip parameters?

Hi,
Again and sorry about some delay in testing out more...

I have credit on my account, and installed Sip client on my computer and that worked without problems. So no router issues at least. Seems to be hassio, addon or some other settings...

**Comment by jarlesb** [comment]
> Dss_voipnotifier34
> 
> I see now that you use an odroid-m2 host machine. Please try the other version

What do you mean try other version? Another raspberry pi installation? I have the standard hassio installation on my home assistant blue/odroid.

**Comment by jarlesb** [comment]
I keep getting the 408 error...

**Comment by sdesalve** [comment]
https://github.com/sdesalve/hassio-addons/tree/master/dss_voip34

**Comment by jarlesb** [comment]
> https://github.com/sdesalve/hassio-addons/tree/master/dss_voip34

Cool! That worked, thanks a lot 🙂

**Comment by havivi86** [comment]
> > https://github.com/sdesalve/hassio-addons/tree/master/dss_voip34
> 
> Cool! That worked, thanks a lot 🙂

I don't get it. what did you do to make it work? The link brings to the instructions. I have the exact same issue... :(

**Comment by sdesalve** [comment]
> > > https://github.com/sdesalve/hassio-addons/tree/master/dss_voip34
> > 
> > 
> > Cool! That worked, thanks a lot 🙂
> 
> I don't get it. what did you do to make it work? The link brings to the instructions. I have the exact same issue... :(

Do you have a Raspberry/ARM processor?

Use https://github.com/sdesalve/hassio-addons/tree/master/dss_voip34

**Comment by jarlesb** [comment]
Thanks a lot for the support sdesalve!

Is there a specific reason why I have to use version 3.4 to get it to work on my Odroid n2/Home assistant blue?

And does it say in the readme? If not, maybe it would be good to add it? Or did I miss it? 🙂

For me this could be closed since there is a workaround, however you may want to keep it if you want a permanent fix also for version 3.5.

**Comment by sdesalve** [comment]
The 3.5 version is using new "dokerfile" syntax from addon example.
Unfortunately it might have some problems within some instances.

I don't know why and I've asked Frenk what can be, but he haven't any clue on what's the problem. So I've retained old version for compatibility with this special cases issues

**Comment by jarlesb** [comment]
> The 3.5 version is using new "dokerfile" syntax from addon example. Unfortunately it might have some problems within some instances.
> 
> I don't know why and I've asked Frenk what can be, but he haven't any clue on what's the problem. So I've retained old version for compatibility with this special cases issues

OK, thanks for the explanation. Let me know if you need someone to test a solution if you find it :)

**Comment by havivi86** [comment]
> > > > https://github.com/sdesalve/hassio-addons/tree/master/dss_voip34
> > > 
> > > 
> > > Cool! That worked, thanks a lot 🙂
> > 
> > 
> > I don't get it. what did you do to make it work? The link brings to the instructions. I have the exact same issue... :(
> 
> Do you have a Raspberry/ARM processor?
> 
> Use https://github.com/sdesalve/hassio-addons/tree/master/dss_voip34

missed the 34 version. Tried it and it works for me as well. BTW, I'm running on VMWare VM with Windows host (not ARM).
@sdesalve , this is amazing addon. Thank you very much for it!

**Comment by sdesalve** [comment]
> > > > > https://github.com/sdesalve/hassio-addons/tree/master/dss_voip34
> > > > 
> > > > 
> > > > Cool! That worked, thanks a lot 🙂
> > > 
> > > 
> > > I don't get it. what did you do to make it work? The link brings to the instructions. I have the exact same issue... :(
> > 
> > 
> > Do you have a Raspberry/ARM processor?
> > Use https://github.com/sdesalve/hassio-addons/tree/master/dss_voip34
> 
> missed the 34 version. Tried it and it works for me as well. BTW, I'm running on VMWare VM with Windows host (not ARM). @sdesalve , this is amazing addon. Thank you very much for it!

It's based on old addo-example... With 3.5 I've updated addon to the latest Hassio image. I don't know why sometimes not work on some system. Sorry
