### ISSUE TITLE
service addon_stdin no longer working with 2021.12

### ISSUE THREAD

**Issue by guiumb** [sdesalve/hassio-addons#47]
dear All,

as described in this article stdin service was removed from HomeAssiant:
[https://community.home-assistant.io/t/hassio-addon-stdin-no-longer-working-with-2021-12/375099](url)

Is there a way to use anymore this great add-on?

Many thanks in advance

**Comment by sdesalve** [comment]
???

Have you read and understood this?
https://community.home-assistant.io/t/hassio-addon-stdin-no-longer-working-with-2021-12/375099/2?u=sdesalve


Sdin was removed from SSH addon, not from HA
