### ISSUE TITLE
Vodafone configuration 

### ISSUE THREAD

**Issue by tiziano3b** [sdesalve/hassio-addons#49]
Hi Salvatore,
first of all thanks for making the addon. 

Unfortunately, I have been trying to configure the addon with the parameters provided by vodafone. I think there is some problem with the auth_username authentication of the outbound proxy in the addon configuration. 

These are my **voip credentials:**

Username : +390643428***
Password : **************************
SIP Outbound Proxy : Voip3.fixed.vodafone.it
SIP Domain: ims.vodafone.it
SIP Port: 5060

This is my **addon configuration**:

sip_parameters:
  caller_id_uri: sip:+390643428***@ims.vodafone.it
  realm: '*'
  username: '+390643428****'
  password: **************************
pjsua_custom_options: '--outbound=sip:Voip3.fixed.vodafone.it;lr'

This is my **Zoiper configuration**:
![image](https://user-images.githubusercontent.com/64270128/163884694-800d6635-1494-43d9-b9d7-817ee4da811b.png)

Putting the voip credentials in Zoiper as shown in the image everything works perfectly, but instead invoking the service from the **following automation**:
service: hassio.addon_stdin
data:
  addon: 7afdaac7_dss_voip
  input:
    call_sip_uri: sip:+39328*******@ims.vodafone.it
    message_tts: Prova

I get this reply message from the addon log (408 request timeout) and the phone does not ring. :(
This is the log file:
[Log.txt](https://github.com/sdesalve/hassio-addons/files/8508446/Log.txt)

I realized that the "auth. username" shown in optional sip credential of zoiper  ( +390643428***@ims.vodafone.it)  is different from the username +390643428****. I tried to change the "auth username" with username (+390643428****) in zoiper and it does not work.

In my addon configuration there is nowhere the option "use auth_username" for the outbound proxy
I think maybe I need to specify some additional options related to "outbound proxy authentication" in pjsua custom option?
Something like: use different auth. username for outbound proxy?

Thanks in advance for the support
Regards Tiziano

**Comment by sdesalve** [comment]
Use https://github.com/sdesalve/hassio-addons/tree/master/dss_voip34 for raspberry

**Comment by tiziano3b** [comment]
Hi Salvatore, I tried with dss voip 34 but the error is now [reason = 403 (Forbidden)] 
Here the log file:
[txt log.txt](https://github.com/sdesalve/hassio-addons/files/8511276/txt.log.txt)

**Comment by sdesalve** [comment]
Remove your personal info from your uploaded logs.

Try to disable TCP transport and double check your login parameters.

403 means that authentication was not successful

**Comment by tiziano3b** [comment]
**> Remove your personal info from your uploaded logs.**
> Done! Thanks

**> Try to disable TCP transport and double check your login parameters.**
> Done! This is the configuration:
sip_parameters:
  caller_id_uri: sip:+390643428***@ims.vodafone.it
  realm: '*'
  username: '+390643428***'
  password: **********************************
  sip_server_uri: sip:ims.vodafone.it
pjsua_custom_options: '--outbound=sip:Voip3.fixed.vodafone.it;lr --no-tcp'

**> 403 means that authentication was not successful**
>I think the problem is that I have to somehow specify within pjsua_custom_options the OTIONAL SIP CREDENTIALS as illustrated in my zoiper screenshot. Than my question is if  there is a way to specify these parameters in the addon.... (Use auth. Username and than specify this) 

>I also tried looking at [PJSua man page](https://www.pjsip.org/pjsua.htm#cmdline) and found something like this:
>$ ./pjsua --id sip:alice@example.com --registrar sip:example.com \
          --proxy outbound.home.com \
          --realm example.com --username alice --password secret --next-cred \
          --realm outbound.home.com --username blah --password blahblah
>But I'm not sure if I write it well in the addon and what parameters to put in.

Thanks Tiziano

**Comment by sdesalve** [comment]
You can use pjsua_custom_options to pass any pjsua options that you need

**Comment by sdesalve** [comment]
You can use pjsua_custom_options to pass any pjsua options that you need

**Comment by sdesalve** [comment]
try to remove this parameters because they are already added by addon config
--id=sip:+390643428***@ims.vodafone.it --registrar=sip:ims.vodafone.it
--realm=sip:ims.vodafone.it

so try 
``
--proxy=sip:Voip3.fixed.vodafone.it;lr --next-cred --realm=sip:Voip3.fixed.vodafone.it --username=+390643428***@ims.vodafone.it --password=****************************
```

please take note of ;lr 

try to use also microsip.org to place a test call so you can check correct config of pjsip
