### ISSUE TITLE
Failed to install add-on error

### ISSUE THREAD

**Issue by ShelbyDodgeGuy** [sdesalve/hassio-addons#53]
Currently trying to install the Monocle Gateway and I'm getting the error :  "The command '/bin/ash -o pipefail -c apk update && apk add --no-cache wget curl libstdc++ nano net-tools openssl ca-certificates' returned a non-zero code: 3" 

Running Home Assistant OS 8.4 x86_64 in a VM.

**Comment by sdesalve** [comment]
Try to install, one at time, this from a terminal

https://github.com/sdesalve/hassio-addons/blob/53582f1b78ffeaa83dab30ce6a61f03309c6a22a/dss_monocle-gateway/Dockerfile#L20

And post error logs.

**Comment by ShelbyDodgeGuy** [comment]
First set of commands ran fine.  Second one returns : 

wget can't open  '/tmp/monocle/monocle-gateway.tar.gz': No such file or directory

**Comment by sdesalve** [comment]
Run this commands one at time

mkdir -p /tmp/monocle

wget -c https://files.monoclecam.com/monocle-gateway/linux/monocle-gateway-alpine-x64-v0.0.4.tar.gz -O /tmp/monocle/monocle-gateway.tar.gz 

cd /usr/local/bin/ 

tar xvzf /tmp/monocle/monocle-gateway.tar.gz monocle-gateway

tar xvzf /tmp/monocle/monocle-gateway.tar.gz monocle-proxy

rm -Rf /tmp/monocle/

**Comment by monomolecular** [comment]
I'd really like to use your Monocle Add-On, but I'm having the same problem. I was able to runn all the commands in your last post.

**Comment by sdesalve** [comment]
What error you get during setup? Post logs

**Comment by itsabitnutty** [comment]
Hi, 
I hope you are well?

I had the error 

Failed to install add-on
The command '/bin/ash -o pipefail -c apk update && apk add --no-cache wget curl libstdc++ nano net-tools openssl ca-certificates' returned a non-zero code: 3

I then ran the commands you posted earlier 5 Aug, and they worked without error, I then tried the add-on again and got the same error, is it because you have /bin/ash not bin/bash ?

**Comment by sdesalve** [comment]
> is it because you have /bin/ash not bin/bash ?

That commands is in dockerfile and don't are related to Hassio shell.

Please provide some info about your Hassio setup:

Host machine
Hassio setup type
Full logs of installation

**Comment by sdesalve** [comment]
For monocle try this commands one at time and report here if you'll get error

apk update 
apk add --no-cache wget 
apk add --no-cache curl 
apk add --no-cache libstdc++ 
apk add --no-cache nano 
apk add --no-cache net-tools 
apk add --no-cache  openssl 
apk add --no-cache ca-certificates

**Comment by itsabitnutty** [comment]
thanks for replying

I am running on a Lenovo tiny pc (x86)
Home assistant was installed as OS using Balena Etcher

I've attached some logs, let me know if I've attached the correct ones

I ran the commands one at a time, with no errors
[home-assistant.log](https://github.com/sdesalve/hassio-addons/files/10178366/home-assistant.log)

**Comment by sdesalve** [comment]
> thanks for replying
> 
> I am running on a Lenovo tiny pc (x86) Home assistant was installed as OS using Balena Etcher
> 
> I've attached some logs, let me know if I've attached the correct ones
> 
> I ran the commands one at a time, with no errors [home-assistant.log](https://github.com/sdesalve/hassio-addons/files/10178366/home-assistant.log)

Try to install now. I've edited dockerfile and splitted RUN command to install all dependencies 

Restart, try to install and then Post same logs

**Comment by itsabitnutty** [comment]
Hi, thanks.

I removed your repo
restarted
added the repo
restarted
tried to install and same error
Failed to install add-on
The command '/bin/ash -o pipefail -c apk update' returned a non-zero code: 3

[home-assistant.log](https://github.com/sdesalve/hassio-addons/files/10179323/home-assistant.log)

**Comment by itsabitnutty** [comment]
do I need to install docker?

**Comment by sdesalve** [comment]
The second...

Hassio is runned in a docker container.

Do you have internet connection? and a properly configured DNS in your Hassio setup/DHCP server (your modem/router)?

**Comment by itsabitnutty** [comment]
Hi, that worked, thanks for your help, greatly appreciated 

what was the issue?

**Comment by itsabitnutty** [comment]
Spoke to soon 

after entering my token and starting 
I get this error in the logs

s6-overlay-suexec: fatal: can only run as pid 1

I’ve also restarted
