### ISSUE TITLE
HACS compatible

### ISSUE THREAD

**Issue by AlfredoCubitos** [sdesalve/hassio-addons#54]
Hi,

could you please make your addon [HACS](https://github.com/hacs) compatible?
I'm using a container installation and  hacs makes it easier to install addons in a container environment.

I tried to install your plugin via hacs but it throws this error message:
`<Plugin sdesalve/hassio-addons> Repository structure for master is not compliant`

Thanks in advanced :-)

**Comment by sdesalve** [comment]
https://hacs.xyz/docs/faq/addons/#:~:text=Add%2Dons%20and%20HACS%20has%20nothing%20to%20do%20with%20each%20other%2C%20they%20are%20completely%20different.

**Comment by sdesalve** [comment]
If I'm wrong, please link here an addon that can be installed with HACS...

**Comment by AlfredoCubitos** [comment]
hm, at least there is a docu how to publish to HACS https://hacs.xyz/docs/publish/start
I hope that helps :-)

**Comment by sdesalve** [comment]
Add-ons cannot be installed with Hacs. I've made other custom components (that's not same thing) compatible with Hacs.
Please read this official answer

https://hacs.xyz/docs/faq/addons/#:~:text=Add%2Dons%20and%20HACS%20has%20nothing%20to%20do%20with%20each%20other%2C%20they%20are%20completely%20different

**Comment by AlfredoCubitos** [comment]
sorry, know I understand HACS is only for integrations and you wrote an add on.
Do you know a way to integrate an add on into a docker environment?

**Comment by sdesalve** [comment]
There isn't any way to use dss VoIP addon without supervisor. It rely on supervisor add-on stdin communication system.

You can rewrite it to use as a bash script... But bash coding it's not related to this repository and I will not do. Sorry

**Comment by AlfredoCubitos** [comment]
for all that, thank you for your patient  conversation. :+1: 
So I will look for a solution which works with a container installation. 
Currently I'm testing `baresip` which includes also `mqtt` features.
