### ISSUE TITLE
Cmd('git') failed due to: exit code(128) cmdline: git clone -v --recursive --depth=1 --shallow-submodules https://github.com/sdesalve/hassio-addons/tree/master/dss_monocle-gateway /data/addons/git/83279deb stderr: 'Cloning into '/data/addons/git/83279deb'... fatal: repository 'https://github.com/sdesalve/hassio-addons/tree/master/dss_monocle-gateway/' not found '

### ISSUE THREAD

**Issue by fabiobrolo** [sdesalve/hassio-addons#55]
I´m getting the following error while trying to add the addon repository

Cmd('git') failed due to: exit code(128) cmdline: git clone -v --recursive --depth=1 --shallow-submodules https://github.com/sdesalve/hassio-addons/tree/master/dss_monocle-gateway /data/addons/git/83279deb stderr: 'Cloning into '/data/addons/git/83279deb'... fatal: repository 'https://github.com/sdesalve/hassio-addons/tree/master/dss_monocle-gateway/' not found '

Besides that, now monocle has a version form ARM64. Is it possible to include it?

**Comment by sdesalve** [comment]
Is for alpine Linux? Has the author recompiled as I've requested some years ago?

Try to fork from website

**Comment by sdesalve** [comment]
There isn't any build for alpine Linux arm64 processors

![Screenshot_2022-09-12-22-46-59-912_com android chrome](https://user-images.githubusercontent.com/9841662/189755867-f64d4abf-c1c7-4fe3-9f16-0bb66df6f577.jpg)

Try to solicitate Monocle to make a build for arm64
https://forum.monoclecam.com/topic/478/monocle-gateway-no-such-file-or-directory

**Comment by sdesalve** [comment]
> I´m getting the following error while trying to add the addon repository
> 
> Cmd('git') failed due to: exit code(128) cmdline: git clone -v --recursive --depth=1 --shallow-submodules https://github.com/sdesalve/hassio-addons/tree/master/dss_monocle-gateway /data/addons/git/83279deb stderr: 'Cloning into '/data/addons/git/83279deb'... fatal: repository 'https://github.com/sdesalve/hassio-addons/tree/master/dss_monocle-gateway/' not found '
> 
> Besides that, now monocle has a version form ARM64. Is it possible to include it?

Could you try to install this?
https://github.com/sdesalve/hassio-addons/tree/master/dss_monocle-gateway-beta
