### ISSUE TITLE
No calls after update fritzbox to 7.5 release

### ISSUE THREAD

**Issue by guiumb** [sdesalve/hassio-addons#59]
Hi,

yesterday I have updated my fritzbox router (IP 10.0.0.1) from 7.2 release to 7.5 and I have noticed that DSS Voip Component on my HA (IP 10.0.0.150) was not able to make calls.
When I try to make call I can see mp3 file tath contain my msg in config/tts folder and if I play it was ok, but no calls was completed and DSS VoIP addon stops itself.
HA is up and running and web service is correctly exposed on internet with duckdns.

This is my TTS config:

```
tts:
  - platform: google_translate
    service_name: google_say
    cache: true
    cache_dir: /config/tts
    time_memory: 300
    language: 'it'
```

This is my DSS Voip config:

```
sip parameters:
caller_id_uri: sip:ZZZZ@fritz.box:5060
realm: "*"
username: ZZZZ
password: XXXX
sip_server_uri: sip:10.0.0.1:5060
max_call_times: 20
pjsua_custom_options: --no-tcp --ip-addr=10.0.0.150
```
where ZZZZ is the username defined on Fritzbox and XXXX is the password.

This is the log that I collect after call attempt:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: DSS VoIP Notifier
 VoIP Notifier for Home Assistant
-----------------------------------------------------------
 Add-on version: 4.0.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.4  (amd64 / qemux86-64)
 Home Assistant Core: 2022.12.6
 Home Assistant Supervisor: 2022.11.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[Info] Starting addon...
PJSUA_CUSTOM_OPTIONS = '--no-tcp --ip-addr=10.0.0.150'
[Info] Registering as SIP Client...
PJSUA_CUSTOM_OPTIONS = '--no-tcp --ip-addr=10.0.0.150'
-----------------------------------------------------------
                  SIP Client registered.

 Call <sip:homeassistant@fritz.box:5060>/VoIP phone number
 to check system status.
 You'll find logs in /share/dss_voip/dss_autoanswer.log
-----------------------------------------------------------
MAX_CALL_TIME = '20'
[Info] Listening for messages via stdin service call...
[Info] Received messages {"call_sip_uri":"sip:3357750640@10.0.0.1:5060","message_tts":"test"}
jq: error (at <stdin>:1): Cannot index number with string "url"
parse error: Invalid numeric literal at line 1, column 13
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

```

This is the dss_pjsua.log file:

```
MAX_CALL_TIME =              '20'
sip_parameters = '{"caller_id_uri":"sip:ZZZZ@fritz.box:5060","realm":"*","username":"ZZZZ","password":"XXX","sip_server_uri":"sip:10.0.0.1:5060"}'
[Info] Received messages '{"call_sip_uri":"sip:NNNN@10.0.0.1:5060","message_tts":"test"}'
CALL_SIP_URI_VALUE = 'sip:NNNN@10.0.0.1:5060'
MESSAGE_TTS_VALUE = 'test'
DATA_JSON = '{
  "message": "test",
  "platform": "google_translate"
}'
JSONGOOGLETTS = '500 Internal Server Error

Server got itself in trouble'
```

Where NNNN is mobile italian number that I try to call.

Could you please support me?

Many thanks in advance

**Comment by sdesalve** [comment]
First remove your phone number 335... From original post

After that, there are some problems with your TTS configuration... JSON errors are related to Hassio TTS module. Have you set base_url in TTS configuration? Your TTS configuration is not as stated in Docs...

You can check that addon is running calling from another extension 

Call <sip:homeassistant@fritz.box:5060>/VoIP phone number to check system status.

**Comment by sdesalve** [comment]
https://github.com/sdesalve/hassio-addons/tree/master/dss_voip#features

**Comment by guiumb** [comment]
Sorry for number ! 

I will try to investigate more on TTS config.

many thanks

**Comment by sdesalve** [comment]
tts:
  - platform: google_translate
    service_name: **google_translate_say** <-------- correct name is that
    language: 'it'
    base_url: **Please provide a valid base url for Google TTS** <----- customize here with your duckdns address

**Comment by guiumb** [comment]
Ok !

Calls works great.

many thanks

**Comment by guiumb** [comment]
During a reboot HA logs a message that says: base_url was deprecated.

It is necessary to delete base_url from yaml config file and setting URL in network settings from web interface: more infos on https://www.home-assistant.io/docs/configuration/basic/

Bye
