### ISSUE TITLE
Set max_call_time per call?

### ISSUE THREAD

**Issue by breti** [sdesalve/hassio-addons#6]
Thanks a lot for creating this add-on! It's working fine here with FRITZ!Box PBX.

Are there any plans to make the max_call_time configurable per call?

Use case:
* All telephones should ring for 10 seconds when someone rings at the front door.
* If the smoke detectors are triggered, a regular call with announcement text should be made.

So I can't just set max_call_time to 10 seconds...

**Comment by sdesalve** [comment]
thank you.
maybe on some future release...

**Comment by sdesalve** [comment]
https://github.com/sdesalve/hassio-addons/issues/8#issuecomment-610528069
