### ISSUE TITLE
Bump Monocle Gateway to 0.0.6

### ISSUE THREAD

**Issue by jb123567** [sdesalve/hassio-addons#60]
Is it possible to bump this to version 0.0.6, the latest beta release in July has added support for UniFi Cameras that have two audio streams following an upgrade.

https://archive.monoclecam.com/monocle-gateway/monocle-gateway-0.0.6-beta/

**Comment by sdesalve** [comment]
I'll make a version to test this beta. Where I can find info about its reliability and bugs?

**Comment by jb123567** [comment]
Here, https://forum.monoclecam.com/topic/1242/unifi-camera-update-fix-available-for-testing-now/2, :)

**Comment by sdesalve** [comment]
Try this
https://github.com/sdesalve/hassio-addons/tree/master/dss_monocle-gateway-beta
Download and put in your /addons folder and restart Hassio

I'll publish after my first tests... Now I can't

**Comment by jb123567** [comment]
Have downloaded the folder, placed it in the add-one folder and restarted (both OS and host), nothing appears in the add-on store under local add-ons? Am I missing something.

**Comment by sdesalve** [comment]
I'll check later.

**Comment by sdesalve** [comment]
now it shoud install and run. I'm going to check if it works

https://github.com/sdesalve/hassio-addons/tree/master/dss_monocle-gateway-beta

**Comment by jb123567** [comment]
Working perfectly, thank you!!

**Comment by sdesalve** [comment]
Do you use a x64 system?

**Comment by jb123567** [comment]
> Do you use a x64 system?

I do indeed

**Comment by sdesalve** [comment]
since this beta version I've added support to ARM processors... 
Thanks for send me that repository

**Comment by jb123567** [comment]
Thank you for being so quick, not having Unifi support was annoying,.
