### ISSUE TITLE
Multiple Phone Calls?

### ISSUE THREAD

**Issue by OmegaLeaderP12** [sdesalve/hassio-addons#62]
Is it possible to send a group call/pair multiple voip sub accounts in order to send message to more than one number at once? As the integration currently works, it calls the first number and then the second.

**Comment by sdesalve** [comment]
You can place a call at once from any phone/SIP client... 

But you can setup a virtual PBX using pbxes.com and make a ring strategy to make all extension at same time. But it's not this the place to explain how you can do
