### ISSUE TITLE
200 sec call disconnect

### ISSUE THREAD

**Issue by kayaliabd** [sdesalve/hassio-addons#63]
first of all I would like to thank you for the nice job you have don!
well,
I am using local SIP server (Asterisk) and I am trying to automate a paging call to all users and use.
everything is configured and work just fine but my mp3 file duration aount 250 sec and the call disconnesting on 120 sec

my configuration:
caller_id_uri: sip:3003@192.168.1.20:5060
realm: "*"
username: "3003"
password: c9e********

script:

  - service: hassio.addon_stdin
    data:
      addon: 89275b70_dss_voip
      input:
        call_sip_uri: sip:555@192.168.1.20:5060
        audio_file_url: http://mainserver/media/x8787_001.mp3
        call_duration: "-1"

**Comment by sdesalve** [comment]
https://github.com/sdesalve/hassio-addons/tree/master/dss_voip#option-audio_file_url-required-if-message_tts-is-not-specified

![image](https://user-images.githubusercontent.com/9841662/213388964-e5851db3-7238-497f-b29d-da0aa4f512e2.png)

It's related to pjSua and I can't fix
