### ISSUE TITLE
Not really a bug, better a question

### ISSUE THREAD

**Issue by kangaroo72** [sdesalve/hassio-addons#67]
Hi all,

it's an amazing addon, but sadly I'm unable to get it working.
Does anyone has a config with Provider "Deutsche Telekom / Germany" to dial?
Thanks a lot

**Comment by sdesalve** [comment]
Do you have parameters for your provider? 
Have you tried to use them successfully with other sip clients?

What kind of error do you get?
Could you please post here 

Your config
Full addon logs

**Comment by kangaroo72** [comment]
Hi and thanks for reply.
Yeah - the data are working.
I'm not an expert with these configs, so I think that's the problem...

Here my config

`caller_id_uri: sip:hass-ipp@fritz.box:5060
realm: "*"
username: hass-ipp-user
password: hass-ipp-pass
sip_server_uri: sip:fritz.box`

Here my automation (not sure if right at all...)

`alias: Neue Automatisierung
description: ""
trigger:
  - device_id: 34b1c8fbd9e782bcdaaddee6f28452d9
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: button_1
condition: []
action:
  - service: hassio.addon_stdin
    data:
      addon: 89275b70-dss-voip
      input:
        call_sip_uri: sip:**620@fritz.box:5060
mode: single`

Thanks so much,

-Tom-

**Comment by sdesalve** [comment]
![Screenshot_2023-01-31-09-53-00-139_io homeassistant companion android](https://user-images.githubusercontent.com/9841662/215713309-bb022485-274e-4abb-9dcd-0d854edc04ee.jpg)
```
   ...
    - service: hassio.addon_stdin
      data_template:
        addon: 89275b70_dss_voip
        input: {"call_sip_uri":"sip:+393334455667@sipserver.com","message_tts":"Write here your message"}
   ...
```

Disable Fritz box sip firewall

**Comment by kangaroo72** [comment]
what's 192.168.178.136 in your setup? Home Assistant?

**Comment by kangaroo72** [comment]
This is my actual log-file... it seems to be calling, but it's not ringing on my phone...

[Link](https://paste.escher.cc/?e209ac4d2a34199a#7ZyEUC5qGvGiNTkorMN67ASuJpzvRKVicSJYDexFSGaW)

**Comment by sdesalve** [comment]
> what's 192.168.178.136 in your setup? Home Assistant?

Yes

**Comment by kangaroo72** [comment]
It's already disabled...
![image](https://user-images.githubusercontent.com/6906390/215775699-c1906a43-116f-4dde-805b-1a66eb28b844.png)

**Comment by sdesalve** [comment]
Full logs?

**Comment by kangaroo72** [comment]
```
[Info] Starting addon...
PJSUA_CUSTOM_OPTIONS = '--no-tcp --ip-addr=192.168.200.6'
[Info] Listening for messages via stdin service call...
[Info] Received messages {"call_sip_uri":"sip:+4916097627100@fritz.box:5060","message_tts":"Write here your message"}
Converting audio file 'http://192.168.200.6:8123/api/tts_proxy/3bb4cd06a7898fc0a33665f241cb48f2f2a192ac_en_-_google_translate.mp3'...
Audio succesfully converted...
Starting SIP Client and calling 'sip:+4916097627100@fritz.box:5060'...
This call will be terminated after '50' seconds.
06:06:38.262 os_core_unix.c !pjlib 2.11.1 for POSIX initialized
12:34:54.263 sip_endpoint.c  .Creating endpoint instance...
19:03:10.264          pjlib  .select() I/O Queue created (0xb66f30c8)
19:03:10.264 sip_endpoint.c  .Module "mod-msg-print" registered
19:03:10.264 sip_transport.  .Transport manager created.
19:03:10.264   pjsua_core.c  .PJSUA state changed: NULL --> CREATED
20:18:06.290   pjsua_core.c  .pjsua version 2.11.1 for Linux-5.15.84/armv7l initialized
13:00:46.300    pjsua_app.c  .Turning sound device -99 -99 ON
19:29:02.301         main.c  Ready: Success
10:18:38.307    pjsua_app.c  .......Call 0 state changed to CALLING
>>>>
Account list:
  [ 0] <sip:192.168.200.6:5060>: does not register
       Online status: Online
 *[ 1] sip:hass-ipp@fritz.box:5060: does not register
       Online status: Online
Buddy list:
 [ 1] <?>  sip:+4916097627100@fritz.box:5060
+=============================================================================+
|       Call Commands:         |   Buddy, IM & Presence:  |     Account:      |
|                              |                          |                   |
|  m  Make new call            | +b  Add new buddy       .| +a  Add new accnt |
|  M  Make multiple calls      | -b  Delete buddy         | -a  Delete accnt. |
|  a  Answer call              |  i  Send IM              | !a  Modify accnt. |
|  h  Hangup call  (ha=all)    |  s  Subscribe presence   | rr  (Re-)register |
|  H  Hold call                |  u  Unsubscribe presence | ru  Unregister    |
|  v  re-inVite (release hold) |  t  ToGgle Online status |  >  Cycle next ac.|
|  U  send UPDATE              |  T  Set online status    |  <  Cycle prev ac.|
| ],[ Select next/prev call    +--------------------------+-------------------+
|  x  Xfer call                |      Media Commands:     |  Status & Config: |
|  X  Xfer with Replaces       |                          |                   |
|  #  Send RFC 2833 DTMF       | cl  List ports           |  d  Dump status   |
|  *  Send DTMF with INFO      | cc  Connect port         | dd  Dump detailed |
| dq  Dump curr. call quality  | cd  Disconnect port      | dc  Dump config   |
|                              |  V  Adjust audio Volume  |  f  Save config   |
|  S  Send arbitrary REQUEST   | Cp  Codec priorities     |                   |
+-----------------------------------------------------------------------------+
|  q  QUIT   L  ReLoad   sleep MS   echo [0|1|txt]     n: detect NAT type     |
+=============================================================================+
You have 1 active call
Current call id=0 to sip:+4916097627100@fritz.box:5060 [CALLING]```

**Comment by sdesalve** [comment]
After that?

**Comment by kangaroo72** [comment]
That's all logging

**Comment by sdesalve** [comment]
> username: hass-ipp-user
> password: hass-ipp-pass

this are login data for a IP phone created in Telephony >  Phone devices > add ip phone?

![image](https://user-images.githubusercontent.com/9841662/215802319-931229c0-2483-4518-bad8-2706a7024184.png)

**Comment by kangaroo72** [comment]
I will test other credentials....

**Comment by kangaroo72** [comment]
tried credentials and name w/o special-characters - same problem - no further log.

**Comment by sdesalve** [comment]
post a screenshot of this page of your fritz

![image](https://user-images.githubusercontent.com/9841662/215806464-5c10958c-0b50-443b-b335-40589fef4d0d.png)

**Comment by sdesalve** [comment]
is this >

> +49xxxxxxxxxx100 another phone number? or your fritz mobile number?

**Comment by kangaroo72** [comment]
![image](https://user-images.githubusercontent.com/6906390/215807963-4f4d728b-62f7-435e-be4d-343cb36240b4.png)

the number xxx1600 is my smartphone

**Comment by sdesalve** [comment]
if you install microsip.org on your computer, could succesfully place a call with same credential and same config?

**Comment by sdesalve** [comment]
![image](https://user-images.githubusercontent.com/9841662/215809332-14620e45-d6db-4382-821e-4d7dfe1175c0.png)


here I have my Voip phone landline number because it's my fritz that will register on my provider and act as a PBX. Is your fritz configured to allow call?

**Comment by kangaroo72** [comment]
Yeah - I'm using the C6's below for outgoing Call's and the Yealink T54W

**Comment by sdesalve** [comment]
ok. please install microsip.org and use same log in data to place a call

**Comment by bru-u-kno** [comment]
Below my working config for FRITZ!Box 7590 with latest FRITZ!OS 7.50, HA on Debian Bullseye virtual machine, tts via google translate and Node-RED


**FRITZ!Box**

![grafik](https://user-images.githubusercontent.com/64802617/215885459-099c3cd1-180a-4e77-ac2e-22bc5afab9c9.png)

![grafik](https://user-images.githubusercontent.com/64802617/215885688-1504fec6-e55e-4e80-bac8-ae48d4b4e1e8.png)


**HA > /config/configuration.yaml**

![grafik](https://user-images.githubusercontent.com/64802617/215888742-61ce9c5f-a6ed-4baa-8270-ca52b538dfc4.png)


**DSS VoIP Notifier Add-On**

![grafik](https://user-images.githubusercontent.com/64802617/215884880-3524aa9b-1514-47b0-a4c7-2b5bb47b71df.png)


**Node-RED**

![grafik](https://user-images.githubusercontent.com/64802617/215886053-0bdf60b5-6eaf-49cb-b68d-9aeebe61747a.png)

![grafik](https://user-images.githubusercontent.com/64802617/215886261-94fb1acd-9a80-4b16-b43a-668a7f1b2611.png)

data > call service JSON-Editor

`{
    "addon": "89275b70_dss_voip",
    "input": {
        "call_sip_uri": "sip:+49358@fritz.box:5060",
        "message_tts": "Thanks for this great add-on"
    }
}`

**Comment by kangaroo72** [comment]
Holy... it works!! Woohooooo. The usual thing... RTFM... Read the f******* manual....

I had   caller_id_uri: 'sip:username@sipserver.com'
But not with the username as mentioned, but the title of the virtual device... ***FACEPALM***

Thanks so much for your patience.
