### ISSUE TITLE
How do you specify what voice to use in google_translate

### ISSUE THREAD

**Issue by wptracy** [sdesalve/hassio-addons#68]
How do you specify what voice to use in configuration.yaml for google_translate.

The voice I want to use is en-US-Neural2-D 

I've tried:
language: en-US-Neural2-D 

https://cloud.google.com/text-to-speech
https://cloud.google.com/text-to-speech/docs/voices
```
# Text to speech
tts:
  - platform: google_translate
```

**Comment by wptracy** [comment]
I discovered that en-US-Neural2-D is a Google Cloud voice.
I installed Google Cloud TTS, so now I can call google translate and google cloud say.

Is it possible for your message_tts to call google_cloud instead of google_translate to create the mp3 file?

service: tts.google_cloud_say
service: tts.google_translate_say

service: hassio.addon_stdin
data:
  addon: 89275b70_dss_voip
  input:
    call_sip_uri: sip:5341@pbxes.com
    message_tts: >-
      Your Home Assistant Water Heater device detected water at {{ now().hour }}
      {{ now().minute }}
enabled: true

**Comment by sdesalve** [comment]
You can use any supported tts engine

https://github.com/sdesalve/hassio-addons/tree/master/dss_voip#option-platform_tts-optional

Sorry for delay

**Comment by wptracy** [comment]
Now I see.  Thanks!!  I should have read the directions.
It works great.

sip_parameters:
  caller_id_uri: sip:wpt-xxxxx@pbxes.com
  realm: "*"
  username: wpt-xxxxx
  password: yyyyyy!#
pjsua_custom_options: "--no-tcp "
platform_tts: edge_tts

configuration.yaml
# Text to speech
tts:
  - platform: google_translate
  - platform: edge_tts
    language: en-US-EricNeural # Default language or voice (Optional)
  - platform: google_cloud
