### ISSUE TITLE
Hassio Addon Voip

### ISSUE THREAD

**Issue by Groovit** [sdesalve/hassio-addons#7]
Hi, we are testing your solution : hassio-addons/dss_voip, and it's work well.
But we are disappointed  with the quality of Google translate and we would like to use Amazon Polly.
We try to change some settings, but it doesn't work.

Did you test your addon with Polly ?
Can we change some specific settings or lines of code or only you can do this ?

Thank's to following us.

Michel

**Comment by sdesalve** [comment]
Hi, 

have you tried with option-platform_tts-optional: 'amazon_polly'

https://github.com/sdesalve/hassio-addons/tree/master/dss_voip#option-platform_tts-optional


SDeSalve

**Comment by Groovit** [comment]
Yes we tried to put : option-platform_tts-optional: 'amazon_polly' *or
*platform_tts-optional:
'amazon_polly' *or *option-platform_tts: 'amazon_polly'
The same result the Addon stop and the log is : jq: error (at <stdin>:1):
Cannot index number with string "url"

See attach



Michel Verhaeghe
Groovit sprl

Tel : +32 69 60 12 24
Mail : info@groovit.be
Web : www.groovit.be <http://groovit.be/>
*L'information transmise est seulement destinée à la personne ou la société
à laquelle elle est adressée et peut contenir une information
confidentielle et/ou privilégiée. N'importe quel réexamen, retransmission,
ou toute autre utilisation de cette information par des personnes ou
entités autres que le destinataire désigné est interdit. Si vous receviez
ce courriel par erreur, entrez s'il vous plaît en contact avec son
expéditeur et effacez-le à partir de n'importe quel ordinateur.*

**Comment by sdesalve** [comment]
this should be how your config must looks like
```
sip_parameters:
  caller_id_uri: xxxxxxxxxxx
  realm: '*'
  username: 'username'
  password: 'password'
platform_tts: 'amazon_polly'
```
second, please stop and restart addon and then attach here addon's logs without your personal data

**Comment by sdesalve** [comment]
obviously you know that Amazon Polly is a PAID service and is not related to Amazon Echo devices and their's TTS?

You MUST subscribe an account entering you credit card for getting a 12 months free thier and you MUST configure your Hassio as stated in https://www.home-assistant.io/integrations/amazon_polly

**Comment by Groovit** [comment]
Yes we have an account and it work with mediaplayer for example.







Michel Verhaeghe
Groovit sprl

Tel : +32 69 60 12 24
Mail : info@groovit.be
Web : www.groovit.be <http://groovit.be/>
*L'information transmise est seulement destinée à la personne ou la société
à laquelle elle est adressée et peut contenir une information
confidentielle et/ou privilégiée. N'importe quel réexamen, retransmission,
ou toute autre utilisation de cette information par des personnes ou
entités autres que le destinataire désigné est interdit. Si vous receviez
ce courriel par erreur, entrez s'il vous plaît en contact avec son
expéditeur et effacez-le à partir de n'importe quel ordinateur.*

**Comment by Groovit** [comment]
Yes but doesn't work.

Did you see the attachments I sent you with my config and my log ?







Michel Verhaeghe
Groovit sprl

Tel : +32 69 60 12 24
Mail : info@groovit.be
Web : www.groovit.be <http://groovit.be/>
*L'information transmise est seulement destinée à la personne ou la société
à laquelle elle est adressée et peut contenir une information
confidentielle et/ou privilégiée. N'importe quel réexamen, retransmission,
ou toute autre utilisation de cette information par des personnes ou
entités autres que le destinataire désigné est interdit. Si vous receviez
ce courriel par erreur, entrez s'il vous plaît en contact avec son
expéditeur et effacez-le à partir de n'importe quel ordinateur.*

**Comment by sdesalve** [comment]
Attachment was not present. I think was stripped out because you reply to GitHub notification mail

**Comment by sdesalve** [comment]
Can you show

- Your Amazon Polly configuration,
- Your DSS VoIP notifier add-on configuration and logs
- response JSONGOOGLETTS in /share/dss_voip/dss_pjsua.log
- An example of how you use Amazon Polly

Please be exhaustive and check your reply. Help me to help you!

**Comment by Groovit** [comment]
I sent you attached photos to your personal mail






Benoît Verhaeghe
Gérant - Groovit sprl

Tel : +32 69 60 12 24
Mail : info@groovit.be
Web : www.groovit.be <http://groovit.be/>
*L'information transmise est seulement destinée à la personne ou la société
à laquelle elle est adressée et peut contenir une information
confidentielle et/ou privilégiée. N'importe quel réexamen, retransmission,
ou toute autre utilisation de cette information par des personnes ou
entités autres que le destinataire désigné est interdit. Si vous receviez
ce courriel par erreur, entrez s'il vous plaît en contact avec son
expéditeur et effacez-le à partir de n'importe quel ordinateur.*

**Comment by sdesalve** [comment]
> I sent you attached photos to your personal mail

I've not received anything. Please reply here if you need help

**Comment by Groovit** [comment]
I found the log file :

sip_parameters = '{"caller_id_uri":"sip:00005@myipbx.3cx.com
","realm":"*","user>

[Info] Received messages '{"call_sip_uri": "sip:00002@myipbx.3cx.com",
"message>

CALL_SIP_URI_VALUE = 'sip:00002@myipbx.3cx.com'

MESSAGE_TTS_VALUE = 'intrusion'

DATA_JSON = '{

  "message": "intrusion",

  "platform": "google_translate"

}'

JSONGOOGLETTS = '500 Internal Server Error


Server got itself in trouble'


Seems the system doesn't change and keep google_translate



Benoît Verhaeghe
Gérant - Groovit sprl

Tel : +32 69 60 12 24
Mail : info@groovit.be
Web : www.groovit.be <http://groovit.be/>
*L'information transmise est seulement destinée à la personne ou la société
à laquelle elle est adressée et peut contenir une information
confidentielle et/ou privilégiée. N'importe quel réexamen, retransmission,
ou toute autre utilisation de cette information par des personnes ou
entités autres que le destinataire désigné est interdit. Si vous receviez
ce courriel par erreur, entrez s'il vous plaît en contact avec son
expéditeur et effacez-le à partir de n'importe quel ordinateur.*

**Comment by sdesalve** [comment]
IF you reply to ALL my request I'll try to help you.

**Comment by Groovit** [comment]
*And config dss_pjsua.conf*

--null-audio

--auto-play

--play-file /share/dss_voip/dss_message_tts.wav

--id sip:00005@myipbx.3cx.com

--realm *

--username TjRgitkUR8

--password VqBJttqo7b

--duration 50


*my configuration.yalm*
tts:
   #platform: google_translate
   #language: 'fr'
    platform: amazon_polly
    aws_access_key_id: AKIOPYRBD7GW7VZ3KGM6Z
    aws_secret_access_key: rjpN0dddOtH5fwZnHetByrn8NjO/0om8AmkYIgmx
    region_name: eu-west-3
    voice: Lea


*The Log of Addon :*

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing...
----------------------------------------------------------- Add-on:
DSS VoIP Notifier VoIP Notifier for
HomeAssistant-----------------------------------------------------------
Add-on version: 3.2.1 You are running the latest version of this
add-on. System: Ubuntu 19.10  (amd64 / intel-nuc) Home Assistant Core:
0.107.5 Home Assistant Supervisor:
209----------------------------------------------------------- Please,
share the above information when looking for help or support in, e.g.,
GitHub, forums or the Discord
chat.-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing...
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.[Info] Starting addon...[Info] Listening for
messages via stdin service call...[Info] Received messages
{"call_sip_uri": "sip:00002@myipbx.3cx.com", "message_tts":
"intrusion"}
jq: error (at <stdin>:1): Cannot index number with string "url"
parse error: Invalid numeric literal at line 1, column 13
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing...
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.



*And our Automation :*
data:
  addon: 89275b70_dss_voip
  input:
    call_sip_uri: 'sip:00002@groovit.3cx.be'
    message_tts: intrusion
service: hassio.addon_stdin

It seem the change of config doen't work.
We tried also to put 10 second and not 50 and in the file config it stay 50




Benoît Verhaeghe
Gérant - Groovit sprl

Tel : +32 69 60 12 24
Mail : info@groovit.be
Web : www.groovit.be <http://groovit.be/>
*L'information transmise est seulement destinée à la personne ou la société
à laquelle elle est adressée et peut contenir une information
confidentielle et/ou privilégiée. N'importe quel réexamen, retransmission,
ou toute autre utilisation de cette information par des personnes ou
entités autres que le destinataire désigné est interdit. Si vous receviez
ce courriel par erreur, entrez s'il vous plaît en contact avec son
expéditeur et effacez-le à partir de n'importe quel ordinateur.*

**Comment by Groovit** [comment]
Ok
Sorry
I did right now






Benoît Verhaeghe
Gérant - Groovit sprl

Tel : +32 69 60 12 24
Mail : info@groovit.be
Web : www.groovit.be <http://groovit.be/>
*L'information transmise est seulement destinée à la personne ou la société
à laquelle elle est adressée et peut contenir une information
confidentielle et/ou privilégiée. N'importe quel réexamen, retransmission,
ou toute autre utilisation de cette information par des personnes ou
entités autres que le destinataire désigné est interdit. Si vous receviez
ce courriel par erreur, entrez s'il vous plaît en contact avec son
expéditeur et effacez-le à partir de n'importe quel ordinateur.*

**Comment by sdesalve** [comment]
I've deleted your comment with your personal data

**Comment by sdesalve** [comment]
please post addon configuration... In logs I don't see option warning that identifies use of *platform_tts*

REMOVE private info

**Comment by Groovit** [comment]
The file dss_voip.conf is empty

**Comment by sdesalve** [comment]
![image](https://user-images.githubusercontent.com/9841662/77522636-d5354d00-6e84-11ea-9c18-2236f3975750.png)

**Comment by sdesalve** [comment]
If you write correct options, you MUST see yellow warning about use Amazon Polly

![image](https://user-images.githubusercontent.com/9841662/77522841-2cd3b880-6e85-11ea-9179-55ba6590ee0d.png)

**Comment by Groovit** [comment]
Great !
It's working now, also for 10 sec config.
Need to put platform-tts at column 1.

Thanks very much

**Comment by sdesalve** [comment]
> Need to put platform-tts at column 1.

https://github.com/sdesalve/hassio-addons/issues/7#issuecomment-603338040

PS: Please respect Creative Commons Attribution-NonCommercial licence...
If you will resell this work or any of their parts, you need my authorization

PS2: If you like my work and time I spent to help you...
![image](https://user-images.githubusercontent.com/9841662/77524769-3579be00-6e88-11ea-85ab-bf7d4aa5ddc2.png)


bye
SDeSalve
