### ISSUE TITLE
Expose rtsp.port and rtsp.proxy.port in configuration

### ISSUE THREAD

**Issue by fabiobrolo** [sdesalve/hassio-addons#70]
Is it possible to expose rtsp.port and rtsp.proxy.port in configuration flow together with the token?
I have installed go2rtc add-on, that already used the standard ports and it is producing port conflicts.

**Comment by sdesalve** [comment]
What add-on are you referring to?

**Comment by fabiobrolo** [comment]
dss_monocle-gateway-beta

**Comment by sdesalve** [comment]
I'll try to manage all monocle.properties options. But I don't have many time for that in next few months... So I can't assure you a solution 

Have you already tried to change go2rtc options?
https://github.com/AlexxIT/go2rtc#security

**Comment by fabiobrolo** [comment]
I will have to change a lot of other config files over my system to change it in go2rtc.

**Comment by DannyFeliz** [comment]
I'm here because I have the same problem, I have go2rtc running too.

**Comment by sdesalve** [comment]
> I'm here because I have the same problem, I have go2rtc running too.

Neither you can change go2rtc settings?
No change is expected soon to this add-on 

https://github.com/AlexxIT/go2rtc#security

**Comment by DannyFeliz** [comment]
> > I'm here because I have the same problem, I have go2rtc running too.
> 
> Neither you can change go2rtc settings? No change is expected soon to this add-on
> 
> [AlexxIT/go2rtc#security](https://github.com/AlexxIT/go2rtc#security)

Later I ended up doing that, and same as @fabiobrolo I had to change a lot of stuff just because of this. But yeah, thanks for pointing to a solution 👍🏻
