### ISSUE TITLE
Can I configure it with Telecom Italia sip?

### ISSUE THREAD

**Issue by areknames96** [sdesalve/hassio-addons#71]
HI! I would like to know if it is possible to make it work with the voip parameters of telecom italia, I tried but I didn’t succeed.
I also tried with a grandstream ht503 gateway on another non-natively voip phone line, again without success

**Comment by sdesalve** [comment]
https://github.com/sdesalve/hassio-addons/issues?q=tim

Non è facile. Se riesci a far funzionare il grandstream puoi copiare gli stessi parametri...
Io ho abbandonato ed ho configurato un FritzBox per usare il VoIP di Telecom
