### ISSUE TITLE
Call without Audio on fritzbox

### ISSUE THREAD

**Issue by fireport** [sdesalve/hassio-addons#73]
I installed your addon but, unfortunately, I can start a call but I have no audio.
These are my configuration and log
192.168.1.1 is fritzbox IP
192.168.1.20 is the IP of home assistant VM

Can you help me?

`sip_parameters:
  caller_id_uri: sip:homeassistant@192.168.1.1:5060
  realm: "*"
  username: homeassistant
  password: [Redacted]
  pjsua_custom_options: "--no-tcp --ip-addr=192.168.1.1"
`

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: DSS VoIP Notifier
 VoIP Notifier for Home Assistant
-----------------------------------------------------------
 Add-on version: 4.0.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.1  (amd64 / qemux86-64)
 Home Assistant Core: 2023.5.4
 Home Assistant Supervisor: 2023.04.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[Info] Starting addon...
[Info] Listening for messages via stdin service call...
[Info] Received messages {"call_sip_uri":"sip:+39[Number called]@192.168.1.1:5060","message_tts":"ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp"}
Converting audio file 'http://192.168.1.20:8123/api/tts_proxy/0ba676c12f90bffcd34afa38daf26921359cdbd8_it_-_google_translate.mp3'...
Audio succesfully converted...
Starting SIP Client and calling 'sip:+39[Redacted]@192.168.1.1:5060'...
This call will be terminated after '50' seconds.
11:19:33.753         os_core_unix.c !pjlib 2.11.1 for POSIX initialized
11:19:33.753         sip_endpoint.c  .Creating endpoint instance...
11:19:33.754                  pjlib  .select() I/O Queue created (0x7f3535918100)
11:19:33.754         sip_endpoint.c  .Module "mod-msg-print" registered
11:19:33.754        sip_transport.c  .Transport manager created.
11:19:33.754           pjsua_core.c  .PJSUA state changed: NULL --> CREATED
11:19:33.783           pjsua_core.c  .pjsua version 2.11.1 for Linux-6.1.25/x86_64 initialized
11:19:33.788            pjsua_app.c  .Turning sound device -99 -99 ON
11:19:33.789                 main.c  Ready: Success
11:19:33.790            pjsua_app.c  .......Call 0 state changed to CALLING
>>>>
Account list:
  [ 0] <sip:172.30.33.13:5060>: does not register
       Online status: Online
  [ 1] <sip:172.30.33.13:5060;transport=TCP>: does not register
       Online status: Online
 *[ 2] sip:homeassistant@192.168.1.1:5060: does not register
       Online status: Online
Buddy list:
 [ 1] <?>  sip:+39[number called]@192.168.1.1:5060
+=============================================================================+
|       Call Commands:         |   Buddy, IM & Presence:  |     Account:      |
|                              |                          |                   |
|  m  Make new call            | +b  Add new buddy       .| +a  Add new accnt |
|  M  Make multiple calls      | -b  Delete buddy         | -a  Delete accnt. |
|  a  Answer call              |  i  Send IM              | !a  Modify accnt. |
|  h  Hangup call  (ha=all)    |  s  Subscribe presence   | rr  (Re-)register |
|  H  Hold call                |  u  Unsubscribe presence | ru  Unregister    |
|  v  re-inVite (release hold) |  t  ToGgle Online status |  >  Cycle next ac.|
|  U  send UPDATE              |  T  Set online status    |  <  Cycle prev ac.|
| ],[ Select next/prev call    +--------------------------+-------------------+
|  x  Xfer call                |      Media Commands:     |  Status & Config: |
|  X  Xfer with Replaces       |                          |                   |
|  #  Send RFC 2833 DTMF       | cl  List ports           |  d  Dump status   |
|  *  Send DTMF with INFO      | cc  Connect port         | dd  Dump detailed |
| dq  Dump curr. call quality  | cd  Disconnect port      | dc  Dump config   |
|                              |  V  Adjust audio Volume  |  f  Save config   |
|  S  Send arbitrary REQUEST   | Cp  Codec priorities     |                   |
+-----------------------------------------------------------------------------+
You have 1 active call
Current call id=0 to sip:+39[Number called]@192.168.1.1:5060 [CALLING]
`

**Comment by sdesalve** [comment]
Seems to be a NAT problem

> sip_parameters: caller_id_uri: sip:homeassistant@192.168.1.1:5060 realm: "*" username: homeassistant password: [Redacted] pjsua_custom_options: "--no-tcp --ip-addr=192.168.1.1"

--ip-addr=192.168.1.20

**Comment by sdesalve** [comment]
> 'http://192.168.1.20:8123/api/tts_proxy/0ba676c12f90bffcd34afa38daf26921359cdbd8_it_-_google_translate.mp3

If you click this link, can you hear anything?

**Comment by fireport** [comment]
Yes, I can confirm that I hear the audio

**Comment by sdesalve** [comment]
> home assistant VM

what kind of VM?

**Comment by fireport** [comment]
OVA

Il giorno gio 25 mag 2023 alle ore 14:43 sdesalve ***@***.***>
ha scritto:

**Comment by fireport** [comment]
caller_id_uri: sip:homeassistant@192.168.1.1:5060
realm: "*"
username: homeassistant
password: "Redacted"
pjsua_custom_options: "--ip-addr=192.168.1.20"

**Comment by fireport** [comment]
![immagine](https://github.com/sdesalve/hassio-addons/assets/3115120/51dc2b04-00ec-4028-a70b-5d293e321f31)

**Comment by sdesalve** [comment]
![image](https://github.com/sdesalve/hassio-addons/assets/9841662/198f349d-a27f-43e2-8d08-025ac2094cd5)

**Comment by fireport** [comment]
![immagine](https://github.com/sdesalve/hassio-addons/assets/3115120/c67d36bd-155c-40d2-9cb1-e5c22ab68315)
Nothing change :-(

**Comment by sdesalve** [comment]
Please compare my screenshot and yours...
Have you see and enabled this switch?
![Screenshot_2023-05-25-16-05-44-705_com android chrome-edit](https://github.com/sdesalve/hassio-addons/assets/9841662/5fb88da1-6144-401d-84a1-85748468067f)


You have filled wrong field and pjsua options are not recognized

When you'll do, It will works

**Comment by fireport** [comment]
You are right !!! Now it works !!!
Grazieeeee
