### ISSUE TITLE
WindTre

### ISSUE THREAD

**Issue by gianlucaromito** [sdesalve/hassio-addons#75]
Hi to all. Does someone have the right parameters to use this plugin with the italian WindTre provider? I've a home FTTH connection and the modem/router is a VOIP device. I've called the provider to have the voip password and I have it. I tried the parameters via a simple voip software (https://www.microsip.org/) and it seems to work.
Thanks for help.
Ciao!

**Comment by sdesalve** [comment]
Se hai i parametri, usali per configurare l'addon...

**Comment by gianlucaromito** [comment]
Si li ho ma credimi le sto provando tutte e non riesco a capire il problema. Pensavo che gia qualcuno avesse avuto l'opportunità di usare DSS con windtre.
Grazie. Buona giornata 😊

**Comment by sdesalve** [comment]
Magari inizia a

mettere screenshot della configurazione
spiegare topologia LAN ed IP degli apparati
screenshot script che invoca la chiamata
mettere LOG completo dall'avvio al termine della chiamata dell'addon

e vediamo...

**Comment by sdesalve** [comment]
user e password sono corretti?

non è che il proxy richiede un'altra autenticazione?

https://www.pjsip.org/pjsua.htm#:~:text=To%20register%20to,%2D%2Dpassword%20blahblah

**Comment by sdesalve** [comment]
metti 

realm: *
