### ISSUE TITLE
Failed to install ARM addon

### ISSUE THREAD

**Issue by danielbouman** [sdesalve/hassio-addons#79]
Hi,

I am trying to install the addon on a raspberry pi. When I click Install, the message "('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))" pops up.

Thanks in advance!

Screenshot:
![image](https://github.com/sdesalve/hassio-addons/assets/1293939/612d27fa-0560-4c20-97f2-74428aa2614a)

**Comment by sdesalve** [comment]
Try ti restart host and the reinstall. Pleose provide hassio addon install logs

**Comment by danielbouman** [comment]
I did a reboot and tried installing again. Got the same error message. This is from the log:
`2023-08-05 10:47:56.565 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /addons/89275b70_dss_voipARM/install - ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))`

**Comment by danielbouman** [comment]
System info:
Home Assistant 2023.7.3
Supervisor 2023.07.1
Operating System 10.3
Frontend 20230705.1 - latest

**Comment by sdesalve** [comment]
Updated. Now should work
