### ISSUE TITLE
Max Call Time

### ISSUE THREAD

**Issue by Groovit** [sdesalve/hassio-addons#8]
Hi Salvatore.
Is it possible to put the setting max_call_time not in the config of the Add-On but in the script ?
I would like to play prerecorded message dependent on the event.
The text of the message and the duration of the call can be variable.

Thank's

**Comment by sdesalve** [comment]
Try this new option: 

https://github.com/sdesalve/hassio-addons/tree/master/dss_voip#option-call_duration-optional

Be aware that **timer** starts running after a call is initiated and **is not related to the call status**

**Comment by Groovit** [comment]
Great it's working

Thank's
