### ISSUE TITLE
fastweb sip not working

### ISSUE THREAD

**Issue by Shiroe93** [sdesalve/hassio-addons#82]
Hi i have been try to configure the add-on with fastweb sip but with no luck
(i have it working with microsip perfectly)

here's full log

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: DSS VoIP Notifier
 VoIP Notifier for Home Assistant
-----------------------------------------------------------
 Add-on version: 4.0.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.5  (amd64 / generic-x86-64)
 Home Assistant Core: 2023.9.2
 Home Assistant Supervisor: 2023.09.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[Info] Starting addon...
PJSUA_CUSTOM_OPTIONS = '--stun-srv=stun.l.google.com:19302'
[Info] Listening for messages via stdin service call...
[Info] Received messages {"call_sip_uri":"sip:+39XXXXXXXX@voip.fastwebnet.it","message_tts":"ciao"}
Converting audio file 'http://home assistant ip (one subnet network):8123/api/tts_proxy/1e4e888ac66f8dd41e00c5a7ac36a32a9950d271_it_-_google_translate.mp3'...
Audio succesfully converted...
Starting SIP Client and calling 'sip:+39XXXXXXX@voip.fastwebnet.it'...
This call will be terminated after '50' seconds.
16:28:22.160         os_core_unix.c !pjlib 2.11.1 for POSIX initialized
16:28:22.160         sip_endpoint.c  .Creating endpoint instance...
16:28:22.160                  pjlib  .select() I/O Queue created (0x7f1cc5429100)
16:28:22.160         sip_endpoint.c  .Module "mod-msg-print" registered
16:28:22.160        sip_transport.c  .Transport manager created.
16:28:22.160           pjsua_core.c  .PJSUA state changed: NULL --> CREATED
16:28:22.191           pjsua_core.c  .pjsua version 2.11.1 for Linux-6.1.45/x86_64 initialized
16:28:22.237            pjsua_app.c  .Turning sound device -99 -99 ON
16:28:22.237                 main.c  Ready: Success
16:28:22.267            pjsua_app.c  .......Call 0 state changed to CALLING
>>>>
Account list:
  [ 0] <sip:mypubblicip49179>: does not register
       Online status: Online
  [ 1] <sip:172.30.33.12:5060;transport=TCP>: does not register
       Online status: Online
 *[ 2] sip:XXXXXXX@voip.fastwebnet.it: does not register
       Online status: Online
Buddy list:
 [ 1] <?>  sip:+39XXXXXXX@voip.fastwebnet.it
+=============================================================================+
|       Call Commands:         |   Buddy, IM & Presence:  |     Account:      |
|                              |                          |                   |
|  m  Make new call            | +b  Add new buddy       .| +a  Add new accnt |
|  M  Make multiple calls      | -b  Delete buddy         | -a  Delete accnt. |
|  a  Answer call              |  i  Send IM              | !a  Modify accnt. |
|  h  Hangup call  (ha=all)    |  s  Subscribe presence   | rr  (Re-)register |
|  H  Hold call                |  u  Unsubscribe presence | ru  Unregister    |
|  v  re-inVite (release hold) |  t  ToGgle Online status |  >  Cycle next ac.|
|  U  send UPDATE              |  T  Set online status    |  <  Cycle prev ac.|
| ],[ Select next/prev call    +--------------------------+-------------------+
|  x  Xfer call                |      Media Commands:     |  Status & Config: |
|  X  Xfer with Replaces       |                          |                   |
|  #  Send RFC 2833 DTMF       | cl  List ports           |  d  Dump status   |
|  *  Send DTMF with INFO      | cc  Connect port         | dd  Dump detailed |
| dq  Dump curr. call quality  | cd  Disconnect port      | dc  Dump config   |
|                              |  V  Adjust audio Volume  |  f  Save config   |
|  S  Send arbitrary REQUEST   | Cp  Codec priorities     |                   |
+-----------------------------------------------------------------------------+
|  q  QUIT   L  ReLoad   sleep MS   echo [0|1|txt]     n: detect NAT type     |
+=============================================================================+
You have 1 active call
Current call id=0 to sip:+39XXXXX@voip.fastwebnet.it [CALLING]
>>> 16:28:22.281            pjsua_app.c  .....Call 0 is DISCONNECTED [reason=403 (Forbidden)]
16:28:22.331            pjsua_app.c  .NAT detection failed: Server Error [status=370500]
16:28:23.238            pjsua_app.c  .Turning sound device -99 -99 OFF
No current call
>>> 16:29:13.705                timer.c  .Dumping timer heap:
16:29:13.705                timer.c  .  Cur size: 0 entries, max: 3070
[Info] Call ended...
[Info] Listening for messages via stdin service call...`

**Comment by sdesalve** [comment]
addon config?

**Comment by Shiroe93** [comment]
> addon config?

`sip_parameters:
  caller_id_uri: sip:username@voip.fastwebnet.it:5060
  realm: "*"
  username: "****"
  password: *****
pjsua_custom_options: "--stun-srv=stun.l.google.com:19302"

Tried with and without port
`

**Comment by sdesalve** [comment]
Try to add --no-tcp to pjsua_custom_options

**Comment by Shiroe93** [comment]
> Try to add --no-tcp to pjsua_custom_options

Since I already have one how I add a second opinion? (formatwise I mean)

**Comment by sdesalve** [comment]
Leave a blank space between the options. You can also remove stun to test call. Stun will solve audio issues behind a NAT

**Comment by Shiroe93** [comment]
> Leave a blank space between the options. You can also remove stun to test call. Stun will solve audio issues behind a NAT

Microsip won't start any call without the stun option though
Anyway I Wil try

**Comment by Shiroe93** [comment]
> Leave a blank space between the options. You can also remove stun to test call. Stun will solve audio issues behind a NAT

Tried with both options and only with tcp
No dice

**Comment by Shiroe93** [comment]
Why you marked it as completed? Am I missed something?
