### ISSUE TITLE
addon crash every call

### ISSUE THREAD

**Issue by mastrandrealuca** [sdesalve/hassio-addons#84]
Hi Salvatore,
I'm trying to configure the addon with messagenet, as per your guide, but every time I invoke a very normal call as per your example the addon restarts completely. I'll paste the log for you.
and obviously the log file is reset.

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: DSS VoIP Notifier
 VoIP Notifier for Home Assistant
-----------------------------------------------------------
 Add-on version: 4.0.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.5  (amd64 / qemux86-64)
 Home Assistant Core: 2023.9.3
 Home Assistant Supervisor: 2023.09.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[Info] Starting addon...
PJSUA_CUSTOM_OPTIONS = '--outbound=sip:sip.messagenet.it:5061;lr'
[Info] Registering as SIP Client...
PJSUA_CUSTOM_OPTIONS = '--outbound=sip:sip.messagenet.it:5061;lr'

[core-ssh dss_voip]$ tail -f dss_pjsua.log
sip_parameters = '{"caller_id_uri":"sip:xxxxxxx@sip.messagenet.it","realm":"*","username":"xxxxxx@sip.messagenet.it","password":"xxxxxx","sip_server_uri":"sip:sip.messagenet.it:5061"}'
[Info] Received messages '{"call_sip_uri":"sip:+39xxxxxx@sip.messagenet.it","message_tts":"e che cazzo!"}'
CALL_SIP_URI_VALUE = 'sip:+39xxxxxx@sip.messagenet.it'
MESSAGE_TTS_VALUE = 'e che cazzo!'
DATA_JSON = '{
  "message": "e che cazzo!",
  "platform": "google_translate"
}'
JSONGOOGLETTS = '{"url":"https://xxxxxx.ddns.net/api/tts_proxy/be0343649138483efae0477d2c03a7e5d849365a_it_-_google_translate.mp3","path":"/api/tts_proxy/be0343649138483efae0477d2c03a7e5d849365a_it_-_google_translate.mp3"}'
URLFILEMP3_VALUE = 'https://xxxxxxx.ddns.net/api/tts_proxy/be0343649138483efae0477d2c03a7e5d849365a_it_-_google_translate.mp3'

**Comment by sdesalve** [comment]
log del core... oltre all'imprecazione c'è l'errore

**Comment by sdesalve** [comment]
xxxxxxx.duckdns.org/config/logs

core
supervisior
dss voip...

**Comment by mastrandrealuca** [comment]
[supervisor_2023-09-29T17-41-03.505Z.log](https://github.com/sdesalve/hassio-addons/files/12769791/supervisor_2023-09-29T17-41-03.505Z.log)
[supervisor_2023-09-29T17-41-03.505Z.log](https://github.com/sdesalve/hassio-addons/files/12769796/supervisor_2023-09-29T17-41-03.505Z.log)
[89275b70_dss_voip_2023-09-29T17-42-45.730Z.log](https://github.com/sdesalve/hassio-addons/files/12769805/89275b70_dss_voip_2023-09-29T17-42-45.730Z.log)

mah, io non ho trovato molto. ho setacciato anche un pò anche nei vari forum per capire se fosse qualcosa sul TTS tipo il base_url (che ora è deprecato). ti incollo anche la conf del tts


tts:
  - platform: google_translate
    service_name: google_say
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
    language: 'it'

**Comment by sdesalve** [comment]
service_name: google_translate_say

**Comment by mastrandrealuca** [comment]
Scusa salvatore, ho provato a cambiare con service_name: google_translate_say
ma non è cambiato nulla ed il componente crasha lo stesso , e nello stesso modo e con lo stesso log che ti riporto

[core-ssh dss_voip]$ tail -f dss_pjsua.log
sip_parameters = '{"caller_id_uri":"sip:xxxxx@sip.messagenet.it","realm":"*","username":"xxxxx@sip.messagenet.it","password":"xxxxx","sip_server_uri":"sip:sip.messagenet.it:5061"}'
[Info] Received messages '{"call_sip_uri":"sip:+39xxxxx@sip.messagenet.it","message_tts":"e che cazzo!"}'
CALL_SIP_URI_VALUE = 'sip:+39xxxxx@sip.messagenet.it'
MESSAGE_TTS_VALUE = 'e che cazzo!'
DATA_JSON = '{
  "message": "e che cazzo!",
  "platform": "google_translate"
}'
JSONGOOGLETTS = '{"url":"https://xxxxx.ddns.net/api/tts_proxy/be0343649138483efae0477d2c03a7e5d849365a_it_-_google_translate.mp3","path":"/api/tts_proxy/be0343649138483efae0477d2c03a7e5d849365a_it_-_google_translate.mp3"}'
URLFILEMP3_VALUE = 'https://xxxx.ddns.net/api/tts_proxy/be0343649138483efae0477d2c03a7e5d849365a_it_-_google_translate.mp3'

**Comment by mastrandrealuca** [comment]
mi sono accorto che avevo il watchdog attivo e quindi al riavvio spazzava i log.. ora nella cartella ho trovato anche questo log

[core-ssh dss_voip]$ cat dss_sox.log
sox:      SoX v14.4.2
sox FAIL formats: can't open input file URL `https://xxxx.ddns.net/api/tts_proxy/3d8553e1b3f5c5baf0b2f5917ef561516fe1e264_it_-_google_translate.mp3':

**Comment by mastrandrealuca** [comment]
ok a posto sistemato... era un problema di risoluzione DNS. 
grazie.
