### ISSUE TITLE
Unsupported transport (PJSIP_EUNSUPTRANSPORT)

### ISSUE THREAD

**Issue by jbltpcblt** [sdesalve/hassio-addons#85]
I can't find the reason for the error... help

log:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
[34m-----------------------------------------------------------[0m
[34m Add-on: DSS VoIP Notifier[0m
[34m VoIP Notifier for Home Assistant[0m
[34m-----------------------------------------------------------[0m
[34m Add-on version: 4.0.0[0m
[32m You are running the latest version of this add-on.[0m
[34m System: Home Assistant OS 10.5  (amd64 / qemux86-64)[0m
[34m Home Assistant Core: 2023.9.3[0m
[34m Home Assistant Supervisor: 2023.09.2[0m
[34m-----------------------------------------------------------[0m
[34m Please, share the above information when looking for help[0m
[34m or support in, e.g., GitHub, forums or the Discord chat.[0m
[34m-----------------------------------------------------------[0m
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[32m[Info] Starting addon...[0m
[33mPJSUA_CUSTOM_OPTIONS = '--no-tcp'[0m
[32m[Info] Listening for messages via stdin service call...[0m
[32m[Info] Received messages {"call_sip_uri":"sip:xxxxxxxxxx@sip.voipblazer.com","message_tts":"Testing VOIP"}[0m
[32mConverting audio file 'http://xxx.xxx.xxx.xxx:8123/api/tts_proxy/10b3601bfc416de0b9d90445ac935c9213e54ecf_fr_-_google_translate.mp3'...[0m
[32mAudio succesfully converted...[0m
[32mStarting SIP Client and calling 'sip:xxxxxxxxxx@sip.voipblazer.com'...[0m
[32mThis call will be terminated after '50' seconds.[0m
19:24:26.619         os_core_unix.c !pjlib 2.11.1 for POSIX initialized
19:24:26.619         sip_endpoint.c  .Creating endpoint instance...
19:24:26.620                  pjlib  .select() I/O Queue created (0x7fdd4bdc6100)
19:24:26.620         sip_endpoint.c  .Module "mod-msg-print" registered
19:24:26.620        sip_transport.c  .Transport manager created.
19:24:26.620           pjsua_core.c  .PJSUA state changed: NULL --> CREATED
19:24:26.633           pjsua_core.c  .pjsua version 2.11.1 for Linux-6.1.45/x86_64 initialized
19:24:26.635            pjsua_app.c  .Turning sound device -99 -99 ON
19:24:26.635                 main.c  Ready: Success
19:24:26.636            pjsua_app.c  .......Call 0 state changed to CALLING
>>>>
Account list:
  [ 0] <sip:172.30.33.2:5060>: does not register
       Online status: Online
 *[ 1] sip:xxxxxxxxxx@sip.voipblazer.com: does not register
       Online status: Online
Buddy list:
 [ 1] <?>  sip:xxxxxxxxxx@sip.voipblazer.com
+=============================================================================+
|       Call Commands:         |   Buddy, IM & Presence:  |     Account:      |
|                              |                          |                   |
|  m  Make new call            | +b  Add new buddy       .| +a  Add new accnt |
|  M  Make multiple calls      | -b  Delete buddy         | -a  Delete accnt. |
|  a  Answer call              |  i  Send IM              | !a  Modify accnt. |
|  h  Hangup call  (ha=all)    |  s  Subscribe presence   | rr  (Re-)register |
|  H  Hold call                |  u  Unsubscribe presence | ru  Unregister    |
|  v  re-inVite (release hold) |  t  ToGgle Online status |  >  Cycle next ac.|
|  U  send UPDATE              |  T  Set online status    |  <  Cycle prev ac.|
| ],[ Select next/prev call    +--------------------------+-------------------+
|  x  Xfer call                |      Media Commands:     |  Status & Config: |
|  X  Xfer with Replaces       |                          |                   |
|  #  Send RFC 2833 DTMF       | cl  List ports           |  d  Dump status   |
|  *  Send DTMF with INFO      | cc  Connect port         | dd  Dump detailed |
| dq  Dump curr. call quality  | cd  Disconnect port      | dc  Dump config   |
|                              |  V  Adjust audio Volume  |  f  Save config   |
|  S  Send arbitrary REQUEST   | Cp  Codec priorities     |                   |
+-----------------------------------------------------------------------------+
|  q  QUIT   L  ReLoad   sleep MS   echo [0|1|txt]     n: detect NAT type     |
+=============================================================================+
You have 1 active call
Current call id=0 to sip:+xxxxxxxxxx@sip.voipblazer.com [CALLING]
>>> 19:24:26.662      tsx0x7fdd4bc356d8  .......Temporary failure in sending Request msg INVITE/cseq=639 (tdta0x7fdd4bc2eaa8), will try next server: Unsupported transport (PJSIP_EUNSUPTRANSPORT)
19:24:27.636            pjsua_app.c  .Turning sound device -99 -99 OFF
19:24:58.663            pjsua_app.c  ....Call 0 is DISCONNECTED [reason=408 (Request Timeout)]
No current call
>>> 19:25:18.148                timer.c  .Dumping timer heap:
19:25:18.148                timer.c  .  Cur size: 0 entries, max: 3070
[32m[Info] Call ended...[0m
[32m[Info] Listening for messages via stdin service call...[0m

config:
sip_parameters:
  caller_id_uri: sip:xxxxxxxxxx@sip.voipblazer.com
  realm: "*"
  username: xxxxxxxxx
  password: xxxxxxxxxx
pjsua_custom_options: "--no-tcp"

talk:
service: hassio.addon_stdin
data_template:
  addon: 89275b70_dss_voip
  input: {"call_sip_uri":"sip:xxxxxxxx@sip.voipblazer.com","message_tts":"Testing VOIP"}

thanks in advance

**Comment by sdesalve** [comment]
try this 

```
sip_parameters:
   caller_id_uri: sip:xxxxxxxxxx@sip.voipblazer.com
   realm: "*"
   username: xxxxxxxxx
   password: xxxxxxxxxx
pjsua_custom_options: "--no-tcp --outbound=sip:sip.voipblazer.com;lr"
```

**Comment by jbltpcblt** [comment]
unfortunately still the same error,    Unsupported transport (PJSIP_EUNSUPTRANSPORT)

**Comment by sdesalve** [comment]
19:24:58.663 pjsua_app.c ....Call 0 is DISCONNECTED [reason=408 (Request Timeout)]

this is most relevant error description...

Hassio seems that cannot reach sip server. Could you open terminal and ping sip.voipblazer.com?

**Comment by jbltpcblt** [comment]
This is the situation,
I align myself with the idea of ​​"sdesalve" of port problem (PS: sorry, forgot on my part to point out that my HAOS runs on proxmox via a Virtual Machine). I did tests on a rasperry pi 3 and Dss voip OK, config transferred to a new Promox VM and pfffff doesn't work. Everything that concerns Firewall on proxmox cut, I tried everything, port forwarding, DMZ etc...
So the problem comes from my HAOS configuration on VM Promox. If anyone has an idea?, otherwise I would look for another solution (Docker asterisk etc...). THANKS

**Comment by sdesalve** [comment]
I run Hassio on proxmox... So this is not the problem. On past someone has encountered this problem on Raspberry so I've made another version for ARM processor with old HASSIO base image. Don't ask me what's the difference... 

It might be related to pjsip lib version installed from Hassio.

Could you try to unistall addon, reboot and reinstall it?
Try to add --ip option to pjsua custom options...

**Comment by jbltpcblt** [comment]
Weird .....

-) DSS VoIP uninstallation, Haos restart, DSS VOIP reinstallation, configuration
-> Same Problem

-) All possible configurations DSS received, seen in the forums, etc.
-> Same Problem

AND

Basic configuration with changing sip settings sip:username@voipblazer. (Betamax Supplier)
by caller_id_uri: sip:sip.voipblazer.com

AND Functional !.
