### ISSUE TITLE
3cx not work

### ISSUE THREAD

**Issue by sergiobrzs** [sdesalve/hassio-addons#87]
ho il 3cx, ho creato un nuovo utente chiamato "antifurto" con l'interno 402, abilitato alle chiamate in uscita sulle regole in uscita (provato ad accedere con questo interno tramite interfaccia web per un test).
Con il tuo addons non esegue alcuna chiama sia verso l'esterno che verso altri interni registrati. ti allego la configurazione.

![Screenshot 2023-10-30 alle 10 41 51](https://github.com/sdesalve/hassio-addons/assets/81012064/5d67b06d-d972-4bc1-b595-509b174e0b7c)

Questo è lo script di avvio

![Screenshot 2023-10-30 alle 10 44 24](https://github.com/sdesalve/hassio-addons/assets/81012064/2cc1f5c7-b381-4b31-b56d-0287cafee11e)

questo è log quando avviato lo script:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Add-on: DSS VoIP Notifier
 VoIP Notifier for Home Assistant
-----------------------------------------------------------
 Add-on version: 4.0.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.0  (amd64 / qemux86-64)
 Home Assistant Core: 2023.10.5
 Home Assistant Supervisor: 2023.10.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[Info] Starting addon...
[Info] Listening for messages via stdin service call...
[Info] Received messages {"call_sip_uri":"sip:400@sergio.my3cx.it","message_tts":"Write here your message"}
Converting audio file 'http://192.168.107.77:8123/api/tts_proxy/3bb4cd06a7898fc0a33665f241cb48f2f2a192ac_en_-_google_translate.mp3'...
Audio succesfully converted...
Starting SIP Client and calling 'sip:400@sergio.my3cx.it'...
This call will be terminated after '50' seconds.
10:46:02.882         os_core_unix.c !pjlib 2.11.1 for POSIX initialized
10:46:02.882         sip_endpoint.c  .Creating endpoint instance...
10:46:02.883                  pjlib  .select() I/O Queue created (0x7fd70c896100)
10:46:02.883         sip_endpoint.c  .Module "mod-msg-print" registered
10:46:02.883        sip_transport.c  .Transport manager created.
10:46:02.883           pjsua_core.c  .PJSUA state changed: NULL --> CREATED
10:46:02.896           pjsua_core.c  .pjsua version 2.11.1 for Linux-6.1.56/x86_64 initialized
10:46:02.899            pjsua_app.c  .Turning sound device -99 -99 ON
10:46:02.899                 main.c  Ready: Success
10:46:02.921            pjsua_app.c  .......Call 0 state changed to CALLING
>>>>
Account list:
  [ 0] <sip:172.30.33.8:5060>: does not register
       Online status: Online
  [ 1] <sip:172.30.33.8:5060;transport=TCP>: does not register
       Online status: Online
 *[ 2] sip:402@sergio.my3cx.it: does not register
       Online status: Online
Buddy list:
 [ 1] <?>  sip:400@sergio.my3cx.it

+=============================================================================+
|       Call Commands:         |   Buddy, IM & Presence:  |     Account:      |
|                              |                          |                   |
|  m  Make new call            | +b  Add new buddy       .| +a  Add new accnt |
|  M  Make multiple calls      | -b  Delete buddy         | -a  Delete accnt. |
|  a  Answer call              |  i  Send IM              | !a  Modify accnt. |
|  h  Hangup call  (ha=all)    |  s  Subscribe presence   | rr  (Re-)register |
|  H  Hold call                |  u  Unsubscribe presence | ru  Unregister    |
|  v  re-inVite (release hold) |  t  ToGgle Online status |  >  Cycle next ac.|
|  U  send UPDATE              |  T  Set online status    |  <  Cycle prev ac.|
| ],[ Select next/prev call    +--------------------------+-------------------+
|  x  Xfer call                |      Media Commands:     |  Status & Config: |
|  X  Xfer with Replaces       |                          |                   |
|  #  Send RFC 2833 DTMF       | cl  List ports           |  d  Dump status   |
|  *  Send DTMF with INFO      | cc  Connect port         | dd  Dump detailed |
| dq  Dump curr. call quality  | cd  Disconnect port      | dc  Dump config   |
|                              |  V  Adjust audio Volume  |  f  Save config   |
|  S  Send arbitrary REQUEST   | Cp  Codec priorities     |                   |
+-----------------------------------------------------------------------------+
|  q  QUIT   L  ReLoad   sleep MS   echo [0|1|txt]     n: detect NAT type     |
+=============================================================================+
You have 1 active call
Current call id=0 to sip:400@sergio.my3cx.it [CALLING]
>>> 10:46:03.899            pjsua_app.c  .Turning sound device -99 -99 OFF
10:46:34.922            pjsua_app.c  ....Call 0 is DISCONNECTED [reason=408 (Request Timeout)]
No current call
>>> 10:46:54.416                timer.c  .Dumping timer heap:
10:46:54.416                timer.c  .  Cur size: 0 entries, max: 3070
[Info] Call ended...
[Info] Listening for messages via stdin service call...

------------------------

Hai qualche idea su dove sto sbagliando?

Grazie

**Comment by sdesalve** [comment]
Non sta rilevando l'opzione --no-tcp

Va messa nelle opzioni aggiuntive non nella configurazione SIP parameters

**Comment by sergiobrzs** [comment]
Grazie per la risposta,
ho visto solo adesso che era una questione di spazio nella configurazione. Ora ho corretto, ma comunque non esegue la chiamata.

Configurazione:

sip_parameters:
  caller_id_uri: sip:402@sergio.my3cx.it
  realm: "*"
  username: xxxx
  password: xxxxx
pjsua_custom_options: "--no-tcp"



Script:
service: hassio.addon_stdin
data:
  addon: 89275b70_dss_voip
  input:
    call_sip_uri: sip:400@sergio.my3cx.it
    message_tts: Write here your message



Log:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Add-on: DSS VoIP Notifier
 VoIP Notifier for Home Assistant
-----------------------------------------------------------
 Add-on version: 4.0.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.1  (amd64 / qemux86-64)
 Home Assistant Core: 2023.10.5
 Home Assistant Supervisor: 2023.10.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[Info] Starting addon...
PJSUA_CUSTOM_OPTIONS = '--no-tcp'
[Info] Listening for messages via stdin service call...
[Info] Received messages {"call_sip_uri":"sip:400@sergio.my3cx.it","message_tts":"Write here your message"}
Converting audio file 'http://192.168.107.77:8123/api/tts_proxy/3bb4cd06a7898fc0a33665f241cb48f2f2a192ac_en_-_google_translate.mp3'...
Audio succesfully converted...
Starting SIP Client and calling 'sip:400@sergio.my3cx.it'...
This call will be terminated after '50' seconds.
20:37:38.598         os_core_unix.c !pjlib 2.11.1 for POSIX initialized
20:37:38.599         sip_endpoint.c  .Creating endpoint instance...
20:37:38.599                  pjlib  .select() I/O Queue created (0x7efd2c122100)
20:37:38.599         sip_endpoint.c  .Module "mod-msg-print" registered
20:37:38.599        sip_transport.c  .Transport manager created.
20:37:38.599           pjsua_core.c  .PJSUA state changed: NULL --> CREATED
20:37:38.613           pjsua_core.c  .pjsua version 2.11.1 for Linux-6.1.59/x86_64 initialized
20:37:38.616            pjsua_app.c  .Turning sound device -99 -99 ON
20:37:38.616                 main.c  Ready: Success
20:37:38.618            pjsua_app.c  .......Call 0 state changed to CALLING
>>>>
Account list:
  [ 0] <sip:172.30.33.8:5060>: does not register
       Online status: Online
 *[ 1] sip:402@sergio.my3cx.it: does not register
       Online status: Online
Buddy list:
 [ 1] <?>  sip:400@sergio.my3cx.it

+=============================================================================+
|       Call Commands:         |   Buddy, IM & Presence:  |     Account:      |
|                              |                          |                   |
|  m  Make new call            | +b  Add new buddy       .| +a  Add new accnt |
|  M  Make multiple calls      | -b  Delete buddy         | -a  Delete accnt. |
|  a  Answer call              |  i  Send IM              | !a  Modify accnt. |
|  h  Hangup call  (ha=all)    |  s  Subscribe presence   | rr  (Re-)register |
|  H  Hold call                |  u  Unsubscribe presence | ru  Unregister    |
|  v  re-inVite (release hold) |  t  ToGgle Online status |  >  Cycle next ac.|
|  U  send UPDATE              |  T  Set online status    |  <  Cycle prev ac.|
| ],[ Select next/prev call    +--------------------------+-------------------+
|  x  Xfer call                |      Media Commands:     |  Status & Config: |
|  X  Xfer with Replaces       |                          |                   |
|  #  Send RFC 2833 DTMF       | cl  List ports           |  d  Dump status   |
|  *  Send DTMF with INFO      | cc  Connect port         | dd  Dump detailed |
| dq  Dump curr. call quality  | cd  Disconnect port      | dc  Dump config   |
|                              |  V  Adjust audio Volume  |  f  Save config   |
|  S  Send arbitrary REQUEST   | Cp  Codec priorities     |                   |
+-----------------------------------------------------------------------------+
|  q  QUIT   L  ReLoad   sleep MS   echo [0|1|txt]     n: detect NAT type     |
+=============================================================================+
You have 1 active call
Current call id=0 to sip:400@sergio.my3cx.it [CALLING]
>>> 20:37:39.616            pjsua_app.c  .Turning sound device -99 -99 OFF
20:38:10.618            pjsua_app.c  ....Call 0 is DISCONNECTED [reason=408 (Request Timeout)]
No current call
>>> 20:38:30.137                timer.c  .Dumping timer heap:
20:38:30.137                timer.c  .  Cur size: 0 entries, max: 3070
[Info] Call ended...
[Info] Listening for messages via stdin service call...


Cosa potrebbe essere?
Grazie

**Comment by sdesalve** [comment]
Prova ad aggiungere :5060 dopo ogni *****.my3cx.it

Il dominio è corretto?
Hai firewall/fritzbox nella rete?

**Comment by sdesalve** [comment]
Con microsip.org su PC riesci a chiamare con le stesse credenziali/configurazione di 3cx?

**Comment by sergiobrzs** [comment]
Ho fatto alcune prove.
Per farlo funzionare con microsip devo inserire questi parametri.

![Screenshot 2023-11-01 alle 21 41 21](https://github.com/sdesalve/hassio-addons/assets/81012064/c80c050f-a799-485b-9eb6-4bfaaa515ce8)

Nel file di configurazione ho quindi inserito la porta 5062 e anche nello script, senza risultato. Ho provato anche a rimuovere la porta dallo script ma nulla. Dovrei inserire quindi quello che microsip considera dominio con la relativa porta. Solo aggiungendo la porta sul dominio sono riuscito a farlo funzionare. Senza la porta sul dominio, la connessione avveniva ma non effettuava la chiamata che andava in timeout (come avviene con il tuo addons). Quindi penso che sia proprio il dominio il problema.


sip_parameters:
  caller_id_uri: sip:402@sergio.my3cx.it:5062
  realm: "*"
  username: kGYf6wQqOk
  password: rm45VlgxiH
pjsua_custom_options: "--no-tcp"


service: hassio.addon_stdin
data:
  addon: 89275b70_dss_voip
  input:
    call_sip_uri: sip:400@sergio.my3cx.it:5062
    message_tts: Write here your message


grazie ancora per la tua disponibilità

**Comment by sdesalve** [comment]
Cancella user e password

**Comment by sdesalve** [comment]
E prova a mettere l'IP del server al posto del nome

**Comment by sdesalve** [comment]
Comunque se cerchi 3cx pjsip o 3cx pjsip trovi tante info. A prima vista pare che non siano compatibili in quanto 3cx (leggo) non è un vero server SIP... 

Prova a vedere se trovi info aggiuntive

**Comment by sergiobrzs** [comment]
già provato più volte, ma nulla... Microsip si trova nella stessa sottorete di homeassistant e il server 3cx si trova in altra rete con impostazione del firewall corrette. Infatti Microsip funziona. Per le prove ho abilitato tutto il traffico dalla sottorete di homeassistant verso il 3cx.

**Comment by sergiobrzs** [comment]
> Comunque se cerchi 3cx pjsip o 3cx pjsip trovi tante info. A prima vista pare che non siano compatibili in quanto 3cx (leggo) non è un vero server SIP...
> 
> Prova a vedere se trovi info aggiuntive

Adesso faccio un po di ricerche... Penso che si possa in quanto appunto l'applicazione che mi hai dato funziona. Se trovo la soluzione ti farò sapere. 

Grazia ancora per il tuo aiuto

**Comment by sdesalve** [comment]
comunque una ricerchina tra le issue a vole aiuta...

https://github.com/sdesalve/hassio-addons/issues/66#issuecomment-1407432922

**Comment by sdesalve** [comment]
https://github.com/sdesalve/hassio-addons/tree/master/dss_voip#:~:text=Note%3A%20To%20call%20external%20PTSN%20numbers%2C%20use%20the%20number%20in%20the%20SIP%20URI%20accounting%20for%20your%20dialer%20settings.%20For%20example%20for%203CX%20you%20may%20use%20%22sip%3A0412345678%40domain.3cx.com.au%22%20and%20this%20will%20call%20the%20PTSN%20number%20if%20accessible%20from%20your%20PBX%20/%20VoIP%20provider.

**Comment by sergiobrzs** [comment]
> comunque una ricerchina tra le issue a volte aiuta...
> 
> [#66 (comment)](https://github.com/sdesalve/hassio-addons/issues/66#issuecomment-1407432922)

intendi inserire --local-port=5062? già provato, come anche il --no-tcp --stun-srv=192.168.4.109 --local-port=5062

ma nulla

**Comment by sergiobrzs** [comment]
trovato e risolto...


sip_parameters:
  caller_id_uri: sip:402@192.168.4.109
  realm: "*"
  username: xxxxx
  password: xxxxx
pjsua_custom_options: "--no-tcp --proxy=sip:ipserver/nameserver:port;lr"


Sullo script non è necessario inserire il numero di porta

Io ho come porta sul server la 5062. 

Grazie ancora per il tuo aiuto.

**Comment by nicojmb** [comment]
> trovato e risolto...
> 
> sip_parameters: caller_id_uri: sip:402@192.168.4.109 realm: "*" username: xxxxx password: xxxxx pjsua_custom_options: "--no-tcp --proxy=sip:ipserver/nameserver:port;lr"
> 
> Sullo script non è necessario inserire il numero di porta
> 
> Io ho come porta sul server la 5062.
> 
> Grazie ancora per il tuo aiuto.

I've the same problem, but adding:

`"--no-tcp --proxy=sip:ipserver/nameserver:port;lr"`

Do not work, can you share your full config and sample script?

**Comment by nicojmb** [comment]
> > Do not work, can you share your full config and sample script?
> 
> Share your full addon logs

Just edited and added.

**Comment by sergiobrzs** [comment]
Hi,
I solved it with this configuration:

sip_parameters:
  caller_id_uri: sip:402@XXXXXX.my3cx.XX
  realm: "*"
  username: username
  password: password
pjsua_custom_options: "--no-tcp --proxy=sip:XXXXXX.my3cx.XX:5062;lr"

where:
402 is the internal number
XXXXXX.my3cx.XX :  pubblic IP address my 3cx server
username e password --> In Phone Provisioning, tab Authentication (ID and Password)
5062 is my "SIP port used by PBX" on Settings --> Network settings


In automation:

service: hassio.addon_stdin
data:
  addon: 89275b70_dss_voip
  input:
    call_sip_uri: sip:400@XXXXX.my3cx.XX
    message_tts: Attivazione antifurto


where:
400 is the number to call

**Comment by nicojmb** [comment]
> > Just edited and added.
> 
> As replied on hassio forum, I need FULL addon logs... Please reply only at 1 thread. Choose if you want to write here on on hassio forum. I will not reply twice

i write here to get full config from @sergiobrzs to campare.

we continue in hassio forum.

@sergiobrzs thanks for share, but do not work for me :(
