### ISSUE TITLE
 Integration error not found

### ISSUE THREAD

**Issue by osmaterdca** [sdesalve/hassio-addons#88]
Hello, 

sorry to bother you with this issue but i'm trying to place a call from HA to my 3CX server but I encountered an issue.
I added the repository to install the add-on.
I installed Text-To-Speech 
I started the DSS add-on
I include the following lines in configuration.yaml  to match your 3cx example :
sip_parameters:
  caller_id_uri: 'sip:310@mylocal3cx'
  realm: '*'
  username: '310'
  password: 'thepassword'
pjsua_custom_options: '-–no-tcp'

But when I try to check the config it raises the error :
Integration error: pjsua_custom_options - Integration 'pjsua_custom_options' not found.
Integration error: sip_parameters - Integration 'sip_parameters' not found.

For sure I know I missed something, but could you please help me ?

Thanks a lot.
David

**Comment by sdesalve** [comment]
![image](https://github.com/sdesalve/hassio-addons/assets/9841662/1a11f1eb-4fb3-46e0-90a9-1a0f3a5d0df3)

**Comment by osmaterdca** [comment]
Oh what an id**t I am.
Thank you !

**Comment by osmaterdca** [comment]
Now all is configured, but i get this error in the log after script execution :

[Info] Starting addon...
PJSUA_CUSTOM_OPTIONS = '-–no-tcp'
[Info] Listening for messages via stdin service call...
[Info] Received messages {"call_sip_uri":"sip:308@voip.XXXXX","message_tts":"Prova segnalazione allarme"}
Converting audio file 'http://192.168.XXXX:8123/api/tts_proxy/d622ce2af2a501b2f2d236bdb35178058db3ed5d_en_-_google_translate.mp3'...
Audio succesfully converted...
Starting SIP Client and calling 'sip:308@vvoip.XXXXX'...
This call will be terminated after '50' seconds.
18:25:33.812         os_core_unix.c !pjlib 2.11.1 for POSIX initialized
18:25:33.812         sip_endpoint.c  .Creating endpoint instance...
18:25:33.813                  pjlib  .select() I/O Queue created (0x7ff9e53be100)
18:25:33.813         sip_endpoint.c  .Module "mod-msg-print" registered
18:25:33.813        sip_transport.c  .Transport manager created.
18:25:33.813           pjsua_core.c  .PJSUA state changed: NULL --> CREATED
18:25:33.813     pjsua_app_config.c  Argument "310" is not valid. Use --help to see help
18:25:33.813           pjsua_core.c  Shutting down, flags=0...
18:25:33.813           pjsua_core.c  PJSUA state changed: CREATED --> CLOSING
18:25:33.813           pjsua_call.c  .Hangup all calls..
18:25:33.813          pjsua_media.c  .Call 0: deinitializing media..
18:25:33.813          pjsua_media.c  .Call 1: deinitializing media..
18:25:33.813          pjsua_media.c  .Call 2: deinitializing media..
18:25:33.813          pjsua_media.c  .Call 3: deinitializing media..
18:25:33.813           pjsua_pres.c  .Shutting down presence..
18:25:34.822           pjsua_core.c  .Destroying...
18:25:34.822          pjsua_media.c  .Shutting down media..
18:25:34.822         sip_endpoint.c  .Destroying endpoint instance..
18:25:34.822         sip_endpoint.c  .Module "mod-msg-print" unregistered
18:25:34.822        sip_transport.c  .Destroying transport manager
18:25:34.822                timer.c  .Dumping timer heap:
18:25:34.822                timer.c  .  Cur size: 0 entries, max: 3070
18:25:34.822         sip_endpoint.c  .Endpoint 0x7ff9e54030e8 destroyed
18:25:34.822           pjsua_core.c  .PJSUA state changed: CLOSING --> NULL
18:25:34.822           pjsua_core.c  .PJSUA destroyed...

The line extension use for HA is 310 (line number and user name is the same)
The line extension i'd like to receive the message is 308

Any idea ?

Thank you.

David

**Comment by sdesalve** [comment]
> 18:25:33.813 pjsua_app_config.c Argument "310" is not valid. Use --help to see help

please put here a screenshot of your addon config. remove password and any other sensitive info

**Comment by osmaterdca** [comment]
Please find the printscreen bellow :
![image](https://github.com/sdesalve/hassio-addons/assets/133154466/2795decc-b6b0-4212-8122-d940c490c13d)

**Comment by sdesalve** [comment]
try to remove double quotes from username & password.

**Comment by osmaterdca** [comment]
I tried and I got these error  when saving :
![image](https://github.com/sdesalve/hassio-addons/assets/133154466/37cbe653-0b63-41cb-b728-276a5565c664)

**Comment by sdesalve** [comment]
![image](https://github.com/sdesalve/hassio-addons/assets/9841662/fd3b976e-f2fe-4ab9-81b7-516bdbd12e1c)


Sorry, double quotes are mandatory...


Please try this config and post addon logs:

```
caller_id_uri: sip:111@voipxxxxxxxxxxx 
realm: "*"
username: "222"
password: "333"
```

I want to see what number is not recognized. please fix caller_id_uri

**Comment by osmaterdca** [comment]
here is the log with the config you ask me to set :
![image](https://github.com/sdesalve/hassio-addons/assets/133154466/46c176ed-46ee-4016-bcbb-c4db8001a17c)

**Comment by sdesalve** [comment]
Could you change password to be alphanumeric string in your PBX settings? Eg: 123abc

**Comment by osmaterdca** [comment]
Here the log :
![image](https://github.com/sdesalve/hassio-addons/assets/133154466/2d08660c-cff2-4288-bc4d-b3f752159e39)


As you can see bellow, after editing the line : password: "123abc" , when the configuration is saved, the " " disapear.
![image](https://github.com/sdesalve/hassio-addons/assets/133154466/8a0fa2ad-fc26-4a5d-88c2-0539c51d69d0)

**Comment by sdesalve** [comment]
it's very strange.

please make a screenshot of your YAML addon config

![image](https://github.com/sdesalve/hassio-addons/assets/9841662/723d4c25-9755-4572-bad1-150e39d0ab32)


try also to cut all config and "paste as plain text" (CTRL+SHIFT+V or mouse dx button and choose)

![image](https://github.com/sdesalve/hassio-addons/assets/9841662/071f565f-526e-4ef7-b322-a8761956662a)

**Comment by osmaterdca** [comment]
Here is the YAML config
![image](https://github.com/sdesalve/hassio-addons/assets/133154466/5622bab0-7679-4063-a321-7df463e118cd)

I cut then pasted as plain text, no change, same error in the log.

I tried to cut, then past in notepad, add the " " for the password, then copy from notepad and paste as plain text in the YAML config. No change the behavior is the same, the " " disapear when I click on save.

**Comment by osmaterdca** [comment]
One more detail : I try without any password (I remove the "password: 123abc" line in the YAML. When I save, the line reapear by it's own as this :
![image](https://github.com/sdesalve/hassio-addons/assets/133154466/eff869b8-e9ac-4115-ab5c-b7a191373d4c)

And after a try, the log show the same error :
![image](https://github.com/sdesalve/hassio-addons/assets/133154466/9b087eec-da5a-4a29-bf79-86a585277e8a)

**Comment by osmaterdca** [comment]
I found something
I removed the option : --notcp
I removed the password in the pabx
I let password : 123 in the config

It works as this. 
very strange

**Comment by sdesalve** [comment]
`pjsua_custom_options: '--no-tcp'`

you must use 2 minus characters (--)

**Comment by osmaterdca** [comment]
I used the copy paste function, but without "as plain text" during the first setup (before all our tests).
So, with 2 minus characters, all is working fine :) Thank you.

Last question, I used google translate :
![image](https://github.com/sdesalve/hassio-addons/assets/133154466/b27a6fa2-9555-4a58-8e2c-1bf0799fcc06)

But the text message is read in "english"  instead of french.
Do you have an idea ?

**Comment by sdesalve** [comment]
https://www.home-assistant.io/integrations/google_translate/#:~:text=Say%20to%20the%20media_player.floor%20device%20entity%20in,force%20soit%20avec%20toi.%22%0A%20%20language%3A%20%22fr%22

**Comment by osmaterdca** [comment]
Perfect ! thank you.
