### ISSUE TITLE
FritzBox! The call does not start

### ISSUE THREAD

**Issue by calas80** [sdesalve/hassio-addons#9]
Hi.
I used this beautiful addon on my raspberry and it worked well.
Over time I changed fritzbox and bought a nuc. I tried to do a test but now it doesn't work anymore.
Does anyone understand the problem?

**This is my configuration on the fritz:**
` Name: hassiotel`
  `Username: hassiotel`
  `Password: xxx`

**This is my configuration addon:**
`sip_parameters:`
  `caller_id_uri: 'sip:hassiotel@fritz.box:5060'`
  `realm: '*'`
  `username: hassiosip`
  `password: xxx`
`pjsua_custom_options: '--ip-addr=192.168.178.50'`

**This is my automation:**
      `  service: hassio.addon_stdin`
        `data_template:`
          `addon: 89275b70_dss_voip`
          `input: {"call_sip_uri":"sip:+393921220XXX@fritz.box:5060","message_tts":"Allarme attivo"}`

This is the log
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: DSS VoIP Notifier
 VoIP Notifier for HomeAssistant
-----------------------------------------------------------
 Add-on version: 3.3.2
 You are running the latest version of this add-on.
 System: HassOS 4.10  (amd64 / qemux86-64)
 Home Assistant Core: 0.111.0
 Home Assistant Supervisor: 227
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[Info] Starting addon...
PJSUA_CUSTOM_OPTIONS = '--ip-addr=192.168.178.50'
[Info] Listening for messages via stdin service call...
[Info] Received messages {"call_sip_uri": "sip:+393921220xxx@fritz.box:5060", "message_tts": "Allarme attivo"}
Converting audio file 'https://192.168.178.50:8123/api/tts_proxy/683a71af6a4ae8e785d9763ca154e4214ef152a6_it_-_google_translate.mp3'...
Audio succesfully converted...
Starting SIP Client and calling 'sip:+393921220xxx@fritz.box:5060'...
This call will be terminated after '50' seconds.
19:31:34.305         os_core_unix.c !pjlib 2.9 for POSIX initialized
19:31:34.305         sip_endpoint.c  .Creating endpoint instance...
19:31:34.306                  pjlib  .select() I/O Queue created (0x5590f4838c90)
19:31:34.306         sip_endpoint.c  .Module "mod-msg-print" registered
19:31:34.306        sip_transport.c  .Transport manager created.
19:31:34.306           pjsua_core.c  .PJSUA state changed: NULL --> CREATED
19:31:34.321           pjsua_core.c  .pjsua version 2.9 for Linux-5.4.44/x86_64 initialized
19:31:34.323            pjsua_app.c  .Turning sound device -99 -99 ON
19:31:34.323                 main.c  Ready: Success
19:31:36.369      tsx0x5590f4888588  ....Failed to send Request msg INVITE/cseq=1053 (tdta0x5590f48855e8)! err=70018 (gethostbyname() has returned error (PJ_ERESOLVE))
19:31:36.369            pjsua_app.c  .......Call 0 is DISCONNECTED [reason=502 (gethostbyname() has returned error (PJ_ERESOLVE))]
19:31:36.369     pjsua_app_common.c  .......
  [DISCONNCTD] To: sip:+393921220xxx@fritz.box

    Call time: 00h:00m:00s, 1st res in 2046 ms, conn in 0ms
>>>>
Account list:
  [ 0] <sip:192.168.178.50:5060>: does not register
       Online status: Online
  [ 1] <sip:192.168.178.50:5060;transport=TCP>: does not register
       Online status: Online
 *[ 2] sip:hassiotel@fritz.box:5060: does not register
       Online status: Online
Buddy list:
 [ 1] <?>  sip:+393921220xxx@fritz.box:5060
+=============================================================================+
|       Call Commands:         |   Buddy, IM & Presence:  |     Account:      |
|                              |                          |                   |
|  m  Make new call            | +b  Add new buddy       .| +a  Add new accnt |
|  M  Make multiple calls      | -b  Delete buddy         | -a  Delete accnt. |
|  a  Answer call              |  i  Send IM              | !a  Modify accnt. |
|  h  Hangup call  (ha=all)    |  s  Subscribe presence   | rr  (Re-)register |
|  H  Hold call                |  u  Unsubscribe presence | ru  Unregister    |
|  v  re-inVite (release hold) |  t  ToGgle Online status |  >  Cycle next ac.|
|  U  send UPDATE              |  T  Set online status    |  <  Cycle prev ac.|
| ],[ Select next/prev call    +--------------------------+-------------------+
|  x  Xfer call                |      Media Commands:     |  Status & Config: |
|  X  Xfer with Replaces       |                          |                   |
|  #  Send RFC 2833 DTMF       | cl  List ports           |  d  Dump status   |
|  *  Send DTMF with INFO      | cc  Connect port         | dd  Dump detailed |
| dq  Dump curr. call quality  | cd  Disconnect port      | dc  Dump config   |
|                              |  V  Adjust audio Volume  |  f  Save config   |
|  S  Send arbitrary REQUEST   | Cp  Codec priorities     |                   |
+-----------------------------------------------------------------------------+
|  q  QUIT   L  ReLoad   sleep MS   echo [0|1|txt]     n: detect NAT type     |
+=============================================================================+
You have 0 active call
>>> 19:31:36.370            pjsua_app.c  .Turning sound device -99 -99 OFF
No current call
[Info] Call ended...
[Info] Listening for messages via stdin service call...

**Comment by sdesalve** [comment]
Failed to send Request msg INVITE/cseq=1053 (tdta0x5590f48855e8)! err=70018 (gethostbyname() has returned error (PJ_ERESOLVE))



please try to call addon with this destination URI

sip:+393921220xxx@192.168.178.1:5060

192.168.178.1 should be your Fritz!Box IP address... Or use your box actual IP

**Comment by calas80** [comment]
> 
> 
> Failed to send Request msg INVITE/cseq=1053 (tdta0x5590f48855e8)! err=70018 (gethostbyname() has returned error (PJ_ERESOLVE))
> 
> please try to call addon with this destination URI
> 
> sip:+393921220xxx@192.168.178.1:5060
> 
> 192.168.178.1 should be your Fritz!Box IP address... Or use your box actual IP

Thank you for your answer! I was trying it right now. The log changes, but the call does not arrive

tarting SIP Client and calling 'sip:+393921220XXX@192.168.178.1:5060'...
This call will be terminated after '50' seconds.
19:50:24.662         os_core_unix.c !pjlib 2.9 for POSIX initialized
19:50:24.663         sip_endpoint.c  .Creating endpoint instance...
19:50:24.666                  pjlib  .select() I/O Queue created (0x55d252b58c90)
19:50:24.666         sip_endpoint.c  .Module "mod-msg-print" registered
19:50:24.666        sip_transport.c  .Transport manager created.
19:50:24.666           pjsua_core.c  .PJSUA state changed: NULL --> CREATED
19:50:24.688           pjsua_core.c  .pjsua version 2.9 for Linux-5.4.44/x86_64 initialized
19:50:24.689            pjsua_app.c  .Turning sound device -99 -99 ON
19:50:24.690                 main.c  Ready: Success
19:50:24.700            pjsua_app.c  .......Call 0 state changed to CALLING
>>>>
Account list:
  [ 0] <sip:192.168.178.50:5060>: does not register
       Online status: Online
  [ 1] <sip:192.168.178.50:5060;transport=TCP>: does not register
       Online status: Online
 *[ 2] sip:hassiotel@fritz.box:5060: does not register
       Online status: Online
Buddy list:
 [ 1] <?>  sip:+393921220XXX@192.168.178.1:5060
+=============================================================================+
|       Call Commands:         |   Buddy, IM & Presence:  |     Account:      |
|                              |                          |                   |
|  m  Make new call            | +b  Add new buddy       .| +a  Add new accnt |
|  M  Make multiple calls      | -b  Delete buddy         | -a  Delete accnt. |
|  a  Answer call              |  i  Send IM              | !a  Modify accnt. |
|  h  Hangup call  (ha=all)    |  s  Subscribe presence   | rr  (Re-)register |
|  H  Hold call                |  u  Unsubscribe presence | ru  Unregister    |
|  v  re-inVite (release hold) |  t  ToGgle Online status |  >  Cycle next ac.|
|  U  send UPDATE              |  T  Set online status    |  <  Cycle prev ac.|
| ],[ Select next/prev call    +--------------------------+-------------------+
|  x  Xfer call                |      Media Commands:     |  Status & Config: |
|  X  Xfer with Replaces       |                          |                   |
|  #  Send RFC 2833 DTMF       | cl  List ports           |  d  Dump status   |
|  *  Send DTMF with INFO      | cc  Connect port         | dd  Dump detailed |
| dq  Dump curr. call quality  | cd  Disconnect port      | dc  Dump config   |
|                              |  V  Adjust audio Volume  |  f  Save config   |
|  S  Send arbitrary REQUEST   | Cp  Codec priorities     |                   |
+-----------------------------------------------------------------------------+
|  q  QUIT   L  ReLoad   sleep MS   echo [0|1|txt]     n: detect NAT type     |
+=============================================================================+
You have 1 active call
Current call id=0 to sip:+393921220XXX@192.168.178.1:5060 [CALLING]
>>> 19:50:25.690            pjsua_app.c  .Turning sound device -99 -99 OFF
19:50:56.700            pjsua_app.c  ....Call 0 is DISCONNECTED [reason=408 (Request Timeout)]
19:50:56.700     pjsua_app_common.c  ....
  [DISCONNCTD] To: sip:+393921220XXX@192.168.178.1

    Call time: 00h:00m:00s, 1st res in 32010 ms, conn in 0ms
No current call
[Info] Call ended...
[Info] Listening for messages via stdin service call..

**Comment by calas80** [comment]
I just solved it thanks to the great help Salvatore De Salve.
1 - I redone the configurations on my fritzbox
2 - Write the new settings in the addon
**AND ESPECIALLY**
3 - Removed: 5060 from the configuration
