### ISSUE TITLE
DSS Notifier with google tts and fritzbox 7530

### ISSUE THREAD

**Issue by Ciqsky** [sdesalve/hassio-addons#91]
When I receive a phone call from my home number (I use a Fritzbox 7530 and a Raspberry Pi4) the TTS message is not always reproduced well. Let me explain better: if upon receiving the call on my phone number I answer immediately then the voice of the TTS message does not is played. If instead of responding immediately I wait 4/5 seconds it often works and the message is played. Have you already encountered this type of problem?
Can it be resolved in some way?
Thanks

**Comment by sdesalve** [comment]
Do you use this?

--ip-addr=RASPBERRY_IP_ADDRESS

**Comment by Ciqsky** [comment]
this my conf

caller_id_uri: sip:homeassistant@192.168.1.1:5060
realm: "*"
username: xxxxxx
password: xxxxxxx
sip_server_uri: sip:192.168.1.1:5060
--no-tcp --ip-addr=192.168.1.105


this is my script example

service: hassio.addon_stdin
data_template:
  input:
    call_sip_uri: sip:+xxxxxxxxxx@192.168.1.1:5060
    message_tts: Non posso attivare allarme, problema con un sensore
data:
  addon: xxxxxxx_dss_voip

**Comment by sdesalve** [comment]
Logs

**Comment by Ciqsky** [comment]
sip_parameters:
  caller_id_uri: sip:homeassistant@192.168.1.1:5060
  realm: "*"
  username: xxx
  password: xxx
  sip_server_uri: sip:192.168.1.1:5060
pjsua_custom_options: "--no-tcp --ip-addr=192.168.1.105"


addon config

**Comment by Ciqsky** [comment]
You have 1 active call
Current call id=0 to sip:xxxx@192.168.1.1:5060 [CALLING]
>>> 17:00:18.640        tsx0x7faef956d8  .......Temporary failure in sending Request msg INVITE/cseq=24205 (tdta0x7faef8eaa8), will try next server: Unsupported transport (PJSIP_EUNSUPTRANSPORT)
17:00:18.669            pjsua_app.c  .....Call 0 state changed to EARLY (183 Session Progress)
17:01:08.386     pjsua_app_common.c  ...
  [EARLY] To: sip:xxxx@192.168.1.1;tag=9EF2DAAB1C6321B2
    Call time: 00h:00m:00s, 1st res in 35 ms, conn in 0ms
    #0 audio G722 @16kHz, sendrecv, peer=192.168.1.1:7078
       SRTP status: Not active Crypto-suite: 
       RX pt=9, last update:00h:00m:00.001s ago
          total 2.0Kpkt 321.9KB (402.4KB +IP hdr) @avg=51.8Kbps/64.7Kbps
          pkt loss=0 (0.0%), discrd=0 (0.0%), dup=0 (0.0%), reord=0 (0.0%)
                (msec)    min     avg     max     last    dev
          loss period:   0.000   0.000   0.000   0.000   0.000
          jitter     :   0.000   0.023   0.625   0.000   0.062
       TX pt=9, ptime=20, last update:00h:00m:12.829s ago
          total 1.9Kpkt 309.7KB (387.2KB +IP hdr) @avg=49.8Kbps/62.3Kbps
          pkt loss=0 (0.0%), dup=0 (0.0%), reorder=0 (0.0%)
                (msec)    min     avg     max     last    dev 
          loss period:   0.000   0.000   0.000   0.000   0.000
          jitter     :   1.375   2.484   2.875   2.875   0.610
       RTT msec      :   0.717   0.805   0.946   0.778   0.086
17:01:08.387            pjsua_app.c  .Call 0 is DISCONNECTED [reason=487 (Request Terminated)]
>>> 17:01:08.904      sip_transaction.c  .....Unable to register CANCEL transaction (key exists)
17:01:08.904           pjsua_call.c  ...Failed to send end session message: Object already exists (PJ_EEXISTS) [status=70015]
17:01:09.386            pjsua_app.c  ..Turning sound device -99 -99 OFF
17:01:09.945                timer.c  .Dumping timer heap:
17:01:09.945                timer.c  .  Cur size: 1 entries, max: 3070
17:01:09.945                timer.c  .  Entries: 
17:01:09.945                timer.c  .    _id	Id	Elapsed	Source
17:01:09.945                timer.c  .    ----------------------------------
17:01:09.945                timer.c  .    4	1	3.959	../src/pjsua-lib/pjsua_call.c:2848
[Info] Call ended...
[Info] Listening for messages via stdin service call...

**Comment by sdesalve** [comment]
Full addon

Altrimenti non vedo se sta rilevando le opzioni

**Comment by sdesalve** [comment]
E comunque metti uno screenshot censurato della configurazione... Magari non l'hai messa bene

**Comment by Ciqsky** [comment]
[Info] Received messages {"call_sip_uri":"sip:+39xxx@192.168.1.1:5060","message_tts":"Non posso attivare allarme, problema con un sensore"}
Converting audio file 'http://192.168.1.105:8123/api/tts_proxy/0f1fcd1ded38411701c4934fe3b5527fdb3debb2_it_-_google_translate.mp3'...
Audio succesfully converted...
Starting SIP Client and calling 'sip:+39xxx@192.168.1.1:5060'...
This call will be terminated after '50' seconds.
17:00:18.542         os_core_unix.c !pjlib 2.11.1 for POSIX initialized
17:00:18.544         sip_endpoint.c  .Creating endpoint instance...
17:00:18.545                  pjlib  .select() I/O Queue created (0x7fafcfc100)
17:00:18.545         sip_endpoint.c  .Module "mod-msg-print" registered
17:00:18.545        sip_transport.c  .Transport manager created.
17:00:18.545           pjsua_core.c  .PJSUA state changed: NULL --> CREATED
17:00:18.584           pjsua_core.c  .pjsua version 2.11.1 for Linux-6.1.58/aarch64 initialized
17:00:18.633            pjsua_app.c  .Turning sound device -99 -99 ON
17:00:18.634                 main.c  Ready: Success
17:00:18.636            pjsua_app.c  .......Call 0 state changed to CALLING
>>>>
Account list:
  [ 0] <sip:192.168.1.105:5060>: does not register
       Online status: Online
 *[ 1] sip:homeassistant@192.168.1.1:5060: does not register
       Online status: Online
Buddy list:
 [ 1] <?>  sip:+39xxx@192.168.1.1:5060

+=============================================================================+
|       Call Commands:         |   Buddy, IM & Presence:  |     Account:      |
|                              |                          |                   |
|  m  Make new call            | +b  Add new buddy       .| +a  Add new accnt |
|  M  Make multiple calls      | -b  Delete buddy         | -a  Delete accnt. |
|  a  Answer call              |  i  Send IM              | !a  Modify accnt. |
|  h  Hangup call  (ha=all)    |  s  Subscribe presence   | rr  (Re-)register |
|  H  Hold call                |  u  Unsubscribe presence | ru  Unregister    |
|  v  re-inVite (release hold) |  t  ToGgle Online status |  >  Cycle next ac.|
|  U  send UPDATE              |  T  Set online status    |  <  Cycle prev ac.|
| ],[ Select next/prev call    +--------------------------+-------------------+
|  x  Xfer call                |      Media Commands:     |  Status & Config: |
|  X  Xfer with Replaces       |                          |                   |
|  #  Send RFC 2833 DTMF       | cl  List ports           |  d  Dump status   |
|  *  Send DTMF with INFO      | cc  Connect port         | dd  Dump detailed |
| dq  Dump curr. call quality  | cd  Disconnect port      | dc  Dump config   |
|                              |  V  Adjust audio Volume  |  f  Save config   |
|  S  Send arbitrary REQUEST   | Cp  Codec priorities     |                   |
+-----------------------------------------------------------------------------+
|  q  QUIT   L  ReLoad   sleep MS   echo [0|1|txt]     n: detect NAT type     |
+=============================================================================+
You have 1 active call
Current call id=0 to sip:+39xxx@192.168.1.1:5060 [CALLING]
>>> 17:00:18.640        tsx0x7faef956d8  .......Temporary failure in sending Request msg INVITE/cseq=24205 (tdta0x7faef8eaa8), will try next server: Unsupported transport (PJSIP_EUNSUPTRANSPORT)
17:00:18.669            pjsua_app.c  .....Call 0 state changed to EARLY (183 Session Progress)
17:01:08.386     pjsua_app_common.c  ...
  [EARLY] To: sip:+39xxx@192.168.1.1;tag=9EF2DAAB1C6321B2
    Call time: 00h:00m:00s, 1st res in 35 ms, conn in 0ms
    #0 audio G722 @16kHz, sendrecv, peer=192.168.1.1:7078
       SRTP status: Not active Crypto-suite: 
       RX pt=9, last update:00h:00m:00.001s ago
          total 2.0Kpkt 321.9KB (402.4KB +IP hdr) @avg=51.8Kbps/64.7Kbps
          pkt loss=0 (0.0%), discrd=0 (0.0%), dup=0 (0.0%), reord=0 (0.0%)
                (msec)    min     avg     max     last    dev
          loss period:   0.000   0.000   0.000   0.000   0.000
          jitter     :   0.000   0.023   0.625   0.000   0.062
       TX pt=9, ptime=20, last update:00h:00m:12.829s ago
          total 1.9Kpkt 309.7KB (387.2KB +IP hdr) @avg=49.8Kbps/62.3Kbps
          pkt loss=0 (0.0%), dup=0 (0.0%), reorder=0 (0.0%)
                (msec)    min     avg     max     last    dev 
          loss period:   0.000   0.000   0.000   0.000   0.000
          jitter     :   1.375   2.484   2.875   2.875   0.610
       RTT msec      :   0.717   0.805   0.946   0.778   0.086
17:01:08.387            pjsua_app.c  .Call 0 is DISCONNECTED [reason=487 (Request Terminated)]
>>> 17:01:08.904      sip_transaction.c  .....Unable to register CANCEL transaction (key exists)
17:01:08.904           pjsua_call.c  ...Failed to send end session message: Object already exists (PJ_EEXISTS) [status=70015]
17:01:09.386            pjsua_app.c  ..Turning sound device -99 -99 OFF
17:01:09.945                timer.c  .Dumping timer heap:
17:01:09.945                timer.c  .  Cur size: 1 entries, max: 3070
17:01:09.945                timer.c  .  Entries: 
17:01:09.945                timer.c  .    _id	Id	Elapsed	Source
17:01:09.945                timer.c  .    ----------------------------------
17:01:09.945                timer.c  .    4	1	3.959	../src/pjsua-lib/pjsua_call.c:2848
[Info] Call ended...
[Info] Listening for messages via stdin service call...

**Comment by Ciqsky** [comment]
questa è la mia configurazione dove ho al posto di xxx il mio numero di telefono

**Comment by Ciqsky** [comment]
sip_parameters:
  caller_id_uri: sip:homeassistant@192.168.1.1:5060
  realm: "*"
  username: homeassistant
  password: xxx
  sip_server_uri: sip:192.168.1.1:5060
pjsua_custom_options: "--no-tcp --ip-addr=192.168.1.105"

questa è la configurazione dove la password è la mia password di accesso e funziona perchè il telefono chiama

**Comment by Ciqsky** [comment]
service: hassio.addon_stdin
data_template:
  input:
    call_sip_uri: sip:+39xxx@192.168.1.1:5060
    message_tts: Non posso attivare allarme, problema con un sensore
data:
  addon: 89275b70_dss_voip


questo è lo script

**Comment by sdesalve** [comment]
1 metti screenshot = foto (censura i dati privati non mi interessano)
perché se hai messo le opzioni nel campo sbagliato qua perdiamo tempo con le prove e basta

2 FULL addon logs significa TUTTO il log... Dall'avvio alla conclusione della chiamata
perché se non mi mandi lo screenshot almeno vedo se vengono rilevate ste benedette opzioni

**Comment by sdesalve** [comment]
questo è uno screenshot:
![image](https://github.com/sdesalve/hassio-addons/assets/9841662/258a3000-6bfb-4e4b-ac7d-a8118e5eb245)

**Comment by sdesalve** [comment]
log:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing...
�[34m-----------------------------------------------------------�[0m
�[34m Add-on: DSS VoIP Notifier�[0m
�[34m VoIP Notifier for Home Assistant�[0m
�[34m-----------------------------------------------------------�[0m
�[34m Add-on version: 4.0.0�[0m
�[32m You are running the latest version of this add-on.�[0m
�[34m System: Home Assistant OS 10.5 (amd64 / qemux86-64)�[0m
�[34m Home Assistant Core: 2023.9.3�[0m
�[34m Home Assistant Supervisor: 2023.09.2�[0m
�[34m-----------------------------------------------------------�[0m
�[34m Please, share the above information when looking for help�[0m
�[34m or support in, e.g., GitHub, forums or the Discord chat.�[0m
�[34m-----------------------------------------------------------�[0m
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing...
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
�[32m[Info] Starting addon...�[0m
**### �[33mPJSUA_CUSTOM_OPTIONS = '--no-tcp'�[0m**

e questo mi interessa vedere se c'è

**Comment by Ciqsky** [comment]
![image](https://github.com/sdesalve/hassio-addons/assets/58590010/586dffc5-de00-4ade-99cd-48855fff7496)

**Comment by Ciqsky** [comment]
![image](https://github.com/sdesalve/hassio-addons/assets/58590010/83fe164c-0fd6-4b94-b8b4-2cab87feeccf)

**Comment by sdesalve** [comment]
Togli questa tanto non serve
sip_server_uri: sip:192.168.1.1:5060

controlla che sia disattivata questa opzione
![image](https://github.com/sdesalve/hassio-addons/assets/9841662/6810535c-7701-40b6-8dad-a1f497c58c03)

**Comment by Ciqsky** [comment]
E' già così

![image](https://github.com/sdesalve/hassio-addons/assets/58590010/5d8f3d6e-b678-43ea-b2dc-e29c1ffdd77c)

**Comment by sdesalve** [comment]
togli la registrazione tanto non ti serve chiamare Hassio e prova a vedere se il problema si è risolto.

se NO, 
Fai una chiamata e rispondi dopo 5 secondi
Fai una chiamata e rispondi subito

posta ENTRAMBI il log dall'avvio della chiamata in poi

**Comment by Ciqsky** [comment]
Tolto l'opzione e fa uguale

Test chiamata risposto subito

Add-on: DSS VoIP Notifier
 VoIP Notifier for Home Assistant
-----------------------------------------------------------
 Add-on version: 4.0.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.2  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2023.12.4
 Home Assistant Supervisor: 2023.12.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[Info] Starting addon...
PJSUA_CUSTOM_OPTIONS = '--no-tcp --ip-addr=192.168.1.105'
[Info] Listening for messages via stdin service call...
[Info] Received messages {"call_sip_uri":"sip:+39xxx@192.168.1.1:5060","message_tts":"Non posso attivare allarme, problema con un sensore"}
Converting audio file 'http://192.168.1.105:8123/api/tts_proxy/0f1fcd1ded38411701c4934fe3b5527fdb3debb2_it_-_google_translate.mp3'...
Audio succesfully converted...
Starting SIP Client and calling 'sip:+39xxx@192.168.1.1:5060'...
This call will be terminated after '50' seconds.
16:35:16.040         os_core_unix.c !pjlib 2.11.1 for POSIX initialized
16:35:16.042         sip_endpoint.c  .Creating endpoint instance...
16:35:16.043                  pjlib  .select() I/O Queue created (0x7f94609100)
16:35:16.043         sip_endpoint.c  .Module "mod-msg-print" registered
16:35:16.043        sip_transport.c  .Transport manager created.
16:35:16.043           pjsua_core.c  .PJSUA state changed: NULL --> CREATED
16:35:16.084           pjsua_core.c  .pjsua version 2.11.1 for Linux-6.1.58/aarch64 initialized
16:35:16.139            pjsua_app.c  .Turning sound device -99 -99 ON
16:35:16.139                 main.c  Ready: Success
16:35:16.141            pjsua_app.c  .......Call 0 state changed to CALLING
>>>>
Account list:
  [ 0] <sip:192.168.1.105:5060>: does not register
       Online status: Online
 *[ 1] sip:homeassistant@192.168.1.1:5060: does not register
       Online status: Online
Buddy list:
 [ 1] <?>  sip:+39xxx@192.168.1.1:5060

+=============================================================================+
|       Call Commands:         |   Buddy, IM & Presence:  |     Account:      |
|                              |                          |                   |
|  m  Make new call            | +b  Add new buddy       .| +a  Add new accnt |
|  M  Make multiple calls      | -b  Delete buddy         | -a  Delete accnt. |
|  a  Answer call              |  i  Send IM              | !a  Modify accnt. |
|  h  Hangup call  (ha=all)    |  s  Subscribe presence   | rr  (Re-)register |
|  H  Hold call                |  u  Unsubscribe presence | ru  Unregister    |
|  v  re-inVite (release hold) |  t  ToGgle Online status |  >  Cycle next ac.|
|  U  send UPDATE              |  T  Set online status    |  <  Cycle prev ac.|
| ],[ Select next/prev call    +--------------------------+-------------------+
|  x  Xfer call                |      Media Commands:     |  Status & Config: |
|  X  Xfer with Replaces       |                          |                   |
|  #  Send RFC 2833 DTMF       | cl  List ports           |  d  Dump status   |
|  *  Send DTMF with INFO      | cc  Connect port         | dd  Dump detailed |
| dq  Dump curr. call quality  | cd  Disconnect port      | dc  Dump config   |
|                              |  V  Adjust audio Volume  |  f  Save config   |
|  S  Send arbitrary REQUEST   | Cp  Codec priorities     |                   |
+-----------------------------------------------------------------------------+
|  q  QUIT   L  ReLoad   sleep MS   echo [0|1|txt]     n: detect NAT type     |
+=============================================================================+
You have 1 active call
Current call id=0 to sip:+39xxx@192.168.1.1:5060 [CALLING]
>>> 16:35:16.146        tsx0x7f938a26d8  .......Temporary failure in sending Request msg INVITE/cseq=15707 (tdta0x7f9389baa8), will try next server: Unsupported transport (PJSIP_EUNSUPTRANSPORT)
16:35:16.175            pjsua_app.c  .....Call 0 state changed to EARLY (183 Session Progress)
16:36:05.870     pjsua_app_common.c  ...
  [EARLY] To: sip:+39xxx@192.168.1.1;tag=C94549091172AD62
    Call time: 00h:00m:00s, 1st res in 36 ms, conn in 0ms
    #0 audio G722 @16kHz, sendrecv, peer=192.168.1.1:7080
       SRTP status: Not active Crypto-suite: 
       RX pt=9, last update:00h:00m:00.000s ago
          total 1.7Kpkt 287.9KB (359.8KB +IP hdr) @avg=46.3Kbps/57.9Kbps
          pkt loss=0 (0.0%), discrd=0 (0.0%), dup=0 (0.0%), reord=0 (0.0%)
                (msec)    min     avg     max     last    dev
          loss period:   0.000   0.000   0.000   0.000   0.000
          jitter     :   0.000   0.044   0.500   0.000   0.078
       TX pt=9, ptime=20, last update:00h:00m:17.918s ago
          total 1.9Kpkt 309.6KB (387.0KB +IP hdr) @avg=49.8Kbps/62.3Kbps
          pkt loss=0 (0.0%), dup=0 (0.0%), reorder=0 (0.0%)
                (msec)    min     avg     max     last    dev 
          loss period:   0.000   0.000   0.000   0.000   0.000
          jitter     :   1.125   2.125   2.875   2.875   0.577
       RTT msec      :   0.595   0.684   0.808   0.701   0.071
16:36:05.871            pjsua_app.c  .Call 0 is DISCONNECTED [reason=487 (Request Terminated)]
>>> 16:36:06.384      sip_transaction.c  .....Unable to register CANCEL transaction (key exists)
16:36:06.384           pjsua_call.c  ...Failed to send end session message: Object already exists (PJ_EEXISTS) [status=70015]
16:36:06.871            pjsua_app.c  ..Turning sound device -99 -99 OFF
16:36:07.700                timer.c  .Dumping timer heap:
16:36:07.700                timer.c  .  Cur size: 1 entries, max: 3070
16:36:07.700                timer.c  .  Entries: 
16:36:07.700                timer.c  .    _id	Id	Elapsed	Source
16:36:07.700                timer.c  .    ----------------------------------
16:36:07.700                timer.c  .    4	1	3.685	../src/pjsua-lib/pjsua_call.c:2848
[Info] Call ended...
[Info] Listening for messages via stdin service call...

Provate altre due volte la seconda dopo 15 secondi e non è andata buon fine (no audio), l'ultima dopo 5 secondi
 ho risposto e ho sentito l'audio. 

You have 1 active call
Current call id=0 to sip:+39xxx@192.168.1.1:5060 [CALLING]
>>> 16:39:29.157        tsx0x7f96bad6d8  .......Temporary failure in sending Request msg INVITE/cseq=27546 (tdta0x7f96ba6aa8), will try next server: Unsupported transport (PJSIP_EUNSUPTRANSPORT)
16:39:29.187            pjsua_app.c  .....Call 0 state changed to EARLY (183 Session Progress)
16:40:18.506     pjsua_app_common.c  .......
  [DISCONNCTD] To: sip:+39xxx@192.168.1.1;tag=4BDC2F032E58D8B1
    Call time: 00h:00m:00s, 1st res in 35 ms, conn in 0ms
    #0 audio G722 @16kHz, sendrecv, peer=192.168.1.1:7080
       SRTP status: Not active Crypto-suite: 
       RX pt=9, last update:00h:00m:00.000s ago
          total 2.4Kpkt 394.4KB (493.0KB +IP hdr) @avg=63.9Kbps/79.9Kbps
          pkt loss=0 (0.0%), discrd=0 (0.0%), dup=0 (0.0%), reord=0 (0.0%)
                (msec)    min     avg     max     last    dev
          loss period:   0.000   0.000   0.000   0.000   0.000
          jitter     :   0.000   0.047   0.750   0.000   0.084
       TX pt=9, ptime=20, last update:00h:00m:02.878s ago
          total 1.9Kpkt 306.5KB (383.2KB +IP hdr) @avg=49.7Kbps/62.1Kbps
          pkt loss=0 (0.0%), dup=0 (0.0%), reorder=0 (0.0%)
                (msec)    min     avg     max     last    dev 
          loss period:   0.000   0.000   0.000   0.000   0.000
          jitter     :   1.250   2.288   2.875   2.875   0.403
       RTT msec      :   0.564   0.747   1.571   0.579   0.280
16:40:18.507            pjsua_app.c  .....Call 0 is DISCONNECTED [reason=486 (Busy Here)]
No current call
>>> 16:40:19.506            pjsua_app.c  .Turning sound device -99 -99 OFF
16:40:21.009                timer.c  .Dumping timer heap:
16:40:21.009                timer.c  .  Cur size: 0 entries, max: 3070
[Info] Call ended...
[Info] Listening for messages via stdin service call...
[Info] Received messages {"call_sip_uri":"sip:+39xxx@192.168.1.1:5060","message_tts":"Non posso attivare allarme, problema con un sensore"}
Converting audio file 'http://192.168.1.105:8123/api/tts_proxy/0f1fcd1ded38411701c4934fe3b5527fdb3debb2_it_-_google_translate.mp3'...
Audio succesfully converted...
Starting SIP Client and calling 'sip:+39xxx@192.168.1.1:5060'...
This call will be terminated after '50' seconds.
16:40:22.328         os_core_unix.c !pjlib 2.11.1 for POSIX initialized
16:40:22.329         sip_endpoint.c  .Creating endpoint instance...
16:40:22.329                  pjlib  .select() I/O Queue created (0x7f92c6b100)
16:40:22.329         sip_endpoint.c  .Module "mod-msg-print" registered
16:40:22.329        sip_transport.c  .Transport manager created.
16:40:22.329           pjsua_core.c  .PJSUA state changed: NULL --> CREATED
16:40:22.357           pjsua_core.c  .pjsua version 2.11.1 for Linux-6.1.58/aarch64 initialized
16:40:22.366            pjsua_app.c  .Turning sound device -99 -99 ON
16:40:22.366                 main.c  Ready: Success
16:40:22.367            pjsua_app.c  .......Call 0 state changed to CALLING
>>>>
Account list:
  [ 0] <sip:192.168.1.105:5060>: does not register
       Online status: Online
 *[ 1] sip:homeassistant@192.168.1.1:5060: does not register
       Online status: Online
Buddy list:
 [ 1] <?>  sip:+39xxx@192.168.1.1:5060

+=============================================================================+
|       Call Commands:         |   Buddy, IM & Presence:  |     Account:      |
|                              |                          |                   |
|  m  Make new call            | +b  Add new buddy       .| +a  Add new accnt |
|  M  Make multiple calls      | -b  Delete buddy         | -a  Delete accnt. |
|  a  Answer call              |  i  Send IM              | !a  Modify accnt. |
|  h  Hangup call  (ha=all)    |  s  Subscribe presence   | rr  (Re-)register |
|  H  Hold call                |  u  Unsubscribe presence | ru  Unregister    |
|  v  re-inVite (release hold) |  t  ToGgle Online status |  >  Cycle next ac.|
|  U  send UPDATE              |  T  Set online status    |  <  Cycle prev ac.|
| ],[ Select next/prev call    +--------------------------+-------------------+
|  x  Xfer call                |      Media Commands:     |  Status & Config: |
|  X  Xfer with Replaces       |                          |                   |
|  #  Send RFC 2833 DTMF       | cl  List ports           |  d  Dump status   |
|  *  Send DTMF with INFO      | cc  Connect port         | dd  Dump detailed |
| dq  Dump curr. call quality  | cd  Disconnect port      | dc  Dump config   |
|                              |  V  Adjust audio Volume  |  f  Save config   |
|  S  Send arbitrary REQUEST   | Cp  Codec priorities     |                   |
+-----------------------------------------------------------------------------+
|  q  QUIT   L  ReLoad   sleep MS   echo [0|1|txt]     n: detect NAT type     |
+=============================================================================+
You have 1 active call
Current call id=0 to sip:+39xxx@192.168.1.1:5060 [CALLING]
>>> 16:40:22.372        tsx0x7f91f046d8  .......Temporary failure in sending Request msg INVITE/cseq=6971 (tdta0x7f91efdaa8), will try next server: Unsupported transport (PJSIP_EUNSUPTRANSPORT)
16:40:22.402            pjsua_app.c  .....Call 0 state changed to EARLY (183 Session Progress)
16:40:31.324            pjsua_app.c  .....Call 0 state changed to CONNECTING
16:40:31.325     pjsua_app_common.c  .......
  [CONNECTING] To: sip:+39xxx@192.168.1.1;tag=B4AD80A30BBB65F4
    Call time: 00h:00m:00s, 1st res in 36 ms, conn in 0ms
    #0 audio G722 @16kHz, sendrecv, peer=192.168.1.1:7078
       SRTP status: Not active Crypto-suite: 
       RX pt=9, last update:00h:00m:00.001s ago
          total 445pkt 71.2KB (89.0KB +IP hdr) @avg=63.8Kbps/79.7Kbps
          pkt loss=0 (0.0%), discrd=0 (0.0%), dup=0 (0.0%), reord=0 (0.0%)
                (msec)    min     avg     max     last    dev
          loss period:   0.000   0.000   0.000   0.000   0.000
          jitter     :   0.000   0.005   0.250   0.000   0.029
       TX pt=9, ptime=20, last update:00h:00m:02.437s ago
          total 363pkt 58.0KB (72.6KB +IP hdr) @avg=52.0Kbps/65.0Kbps
          pkt loss=0 (0.0%), dup=0 (0.0%), reorder=0 (0.0%)
                (msec)    min     avg     max     last    dev 
          loss period:   0.000   0.000   0.000   0.000   0.000
          jitter     :   1.375   1.375   1.375   1.375   0.000
       RTT msec      :   0.640   0.701   0.762   0.640   0.061

Non è che il problema è la generazione del file mp3?

**Comment by sdesalve** [comment]
> Non è che il problema è la generazione del file mp3?

se clicchi sui link dei file MP3 li riesci a sentire? Anche perché il file è sempre lo stesso

posti la configurazione del TTS?


```
# Text to speech
tts:
  - platform: google_translate
    service_name: google_translate_say
    language: 'it'
    cache: true
    cache_dir: /config/www/tts
    time_memory: 300
```

**Comment by Ciqsky** [comment]
tts:
  - platform: google_translate
    service_name: google_say
    #    cache: true
    #    cache_dir: /tmp/tts
    time_memory: 300
    language: "it"

**Comment by Ciqsky** [comment]
cache true e cache dir sono commentati da me

**Comment by sdesalve** [comment]
la cache evita che lo stesso file venga generato più volte. riattivala e controlla che la cartella esista... meglio se la metti sotto www

**Comment by Ciqsky** [comment]
Allora dopo la modifica 1a chiamata non è andata...la seconda ho aspettato 5/6 secondi è andata le sueccessive due sono andate rispondendo subito alla chiamata: il problema non è il notifier ma la generazione del file MP3. Mi chiedo se c'è un modo per velocizzarla anche perchè se dove impostare la generazione del messaggio in modo parametrico ci sarebbe quasi sempre problemi a meno di non aspettare che vengano generate tutte.....problema dell'RPI4?

**Comment by sdesalve** [comment]
Potrebbe essere la connessione internet lenta o, come dici te, la capacità di calcolo dell'RPi4

A sto punto, genera gli MP3 che ti servono, mettili in www e fagli riprodurre i file mp3 invece di generarli ogni volta

**Comment by Ciqsky** [comment]
Grazie per l'aiuto e BUON ANNO!

**Comment by LucaZiegler** [comment]
Hello @Ciqsky please write in english, we need also a solution. Thx

**Comment by sdesalve** [comment]
I've suggested to @Ciqsky to use MP3 instead  to generate it with TTS .

He hasn't replied if that has resolved this issue with rpi4
