### ISSUE TITLE
"Monocle API Authentication Error; invalid or missing token." (could there be an API change or something in similar?)

### ISSUE THREAD

**Issue by SmilyHM** [sdesalve/hassio-addons#93]
Hi! Just saw today, that the cam couldn't showed on my Echo-device. It worked without any problems in the past. I don't know, since when the auth fails. It's "DSS Monocle Gateway BETA" v0.16 on amd64 (generic x86-64).

**HomeAssistant**
Core 2024.1.6
Supervisor 2023.12.1
Operating System 11.4
Frontend 20240104.0

**Addon-Log**
`[Monocle Connecting]`
`Monocle API Authentication Error; invalid or missing token.`
`2024-02-02T12:08:47.268Z [ERROR] [Monocle Error] Unexpected server response: 401`
`[ '[Monocle Error]', 'Unexpected server response: 401' ]`
`[Monocle Disconnected]`
`[Monocle Reconnecting] ... in 51 seconds (attempt #10)`

Of course a token is set. To double-check I created a new token an replaced it in HA.

Need more Information? Just let me know :)

Thanks and best regards
Sascha

**Comment by sdesalve** [comment]
try to install dss_monocle-gateway-beta 16.0.1


401 error meaning unauthorized... try to generate another API key
