### ISSUE TITLE
Autonomation do not make a call

### ISSUE THREAD

**Issue by robitsrl** [sdesalve/hassio-addons#95]
Hello,
I have set up the addon with my fritz box and also tried with a pbx from yeastar.
In both case when i run the autonomation it's say run correctly but nothig append.
With the yeastar pbx i do not see also the homeassistant registration active.

that is the automation call

service: hassio.addon_stdin
data:
  addon: 89275b70_dss_voip
  input:
    call_sip_uri: sip:+39xxxxxxxx@fritz.box
    message_tts: Write here your message

that is the registry log

 Add-on: DSS VoIP Notifier
 VoIP Notifier for Home Assistant
-----------------------------------------------------------
 Add-on version: 4.0.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.2  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2024.1.0
 Home Assistant Supervisor: 2024.03.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[Info] Starting addon...
[Info] Listening for messages via stdin service call...

Do i miss something ?
Thanks

**Comment by sdesalve** [comment]
Your automation isn't working. It doesn't call addon

**Comment by robitsrl** [comment]
What's wrong with it ?
I tried also

**Comment by robitsrl** [comment]
- service: hassio.addon_stdin
      data_template:
        addon: 89275b70_dss_voiparm
        input: {"call_sip_uri":"sip:+39xxxxxxx@fritz.box","message_tts":"Write here your message"}

**Comment by sdesalve** [comment]
Do you have 89275b70_dss_voip or 89275b70_dss_voiparm?

[Info] Listening for messages via stdin service call...
After this, if there isn't anything addon is not called.

You need to check how call addon within automation. Google for that

**Comment by robitsrl** [comment]
First time i have installed the standard addon so the code was with 89275b70_dss_voip 
then i realized that i'm on a raspberry so i change add on and now i'm using the arm version.

after [Info] Listening for messages via stdin service call... 
i do not have anythig and if i run the script it seem the addon start again

**Comment by sdesalve** [comment]
Addon start again for some misconfiguration.

Do you have TTS correct configuration?

Please post
Config
addon-logs
And anything that can help me to understand

**Comment by robitsrl** [comment]
Hi,
TTS is setup with frontend and it's working, my apple Homepod can say words...

but after your post i added TTS configuration in yaml configuration and now calls are made but I can not hear anything.

my fritz box have a public subnet where there is only a firewall and HA is behind the firewall.

I then tried to change pjsua_custom_options:  first time I was using the HA lan ip address, then I have tried the outbound IP address that's the firewall one, and have tested aolso the 172.30.33.7

always no voice come. thats the log

14:49:10.236         os_core_unix.c !pjlib 2.9 for POSIX initialized
14:49:10.238         sip_endpoint.c  .Creating endpoint instance...
14:49:10.238                  pjlib  .select() I/O Queue created (0x55a803bc90)
14:49:10.238         sip_endpoint.c  .Module "mod-msg-print" registered
14:49:10.238        sip_transport.c  .Transport manager created.
14:49:10.238           pjsua_core.c  .PJSUA state changed: NULL --> CREATED
14:49:10.256           pjsua_core.c  .pjsua version 2.9 for Linux-6.1.58/aarch64 initialized
14:49:10.259            pjsua_app.c  .Turning sound device -99 -99 ON
14:49:10.260                 main.c  Ready: Success
14:49:10.266            pjsua_app.c  .......Call 0 state changed to CALLING
>>>>
Account list:
  [ 0] <sip:172.30.33.7:5060>: does not register
       Online status: Online
  [ 1] <sip:172.30.33.7:5060;transport=TCP>: does not register
       Online status: Online
 *[ 2] sip:homeassistant@fritz.box:5060: does not register
       Online status: Online
Buddy list:
 [ 1] <?>  sip:+393492548964@fritz.box

+=============================================================================+
|       Call Commands:         |   Buddy, IM & Presence:  |     Account:      |
|                              |                          |                   |
|  m  Make new call            | +b  Add new buddy       .| +a  Add new accnt |
|  M  Make multiple calls      | -b  Delete buddy         | -a  Delete accnt. |
|  a  Answer call              |  i  Send IM              | !a  Modify accnt. |
|  h  Hangup call  (ha=all)    |  s  Subscribe presence   | rr  (Re-)register |
|  H  Hold call                |  u  Unsubscribe presence | ru  Unregister    |
|  v  re-inVite (release hold) |  t  ToGgle Online status |  >  Cycle next ac.|
|  U  send UPDATE              |  T  Set online status    |  <  Cycle prev ac.|
| ],[ Select next/prev call    +--------------------------+-------------------+
|  x  Xfer call                |      Media Commands:     |  Status & Config: |
|  X  Xfer with Replaces       |                          |                   |
|  #  Send RFC 2833 DTMF       | cl  List ports           |  d  Dump status   |
|  *  Send DTMF with INFO      | cc  Connect port         | dd  Dump detailed |
| dq  Dump curr. call quality  | cd  Disconnect port      | dc  Dump config   |
|                              |  V  Adjust audio Volume  |  f  Save config   |
|  S  Send arbitrary REQUEST   | Cp  Codec priorities     |                   |
+-----------------------------------------------------------------------------+
|  q  QUIT   L  ReLoad   sleep MS   echo [0|1|txt]     n: detect NAT type     |
+=============================================================================+
You have 1 active call
Current call id=0 to sip:+393492548964@fritz.box [CALLING]


to avoid firewall issue i have an hardware pbx from yeastr in the lan but if tried to configre it i get NOT REGISTERED in the log

**Comment by sdesalve** [comment]
If phone ring, you pick-up call but you can't hear anything, you need to add raspberry pi address

https://github.com/sdesalve/hassio-addons/tree/master/dss_voipARM#a-fritzbox-with-voip-pbx

**Comment by robitsrl** [comment]
Ok thank' s now with the firewall address I have sound..
Any way to get it working also with the yeastar pbx ? any special configuration settings ?

**Comment by sdesalve** [comment]
> Any way to get it working also with the yeastar pbx ?

never used.

> any special configuration settings ?

will be always same option. you shoud try

**Comment by robitsrl** [comment]
tried but i get this:

[Info] Listening for messages via stdin service call...
[Info] Received messages {"call_sip_uri":"sip:+393492548964@pbx.chiusi","message_tts":"Write here your message"}
Converting audio file 'https://homeassistant.robit.biz/api/tts_proxy/3bb4cd06a7898fc0a33665f241cb48f2f2a192ac_it_-_google_translate.mp3'...
Audio succesfully converted...
Starting SIP Client and calling 'sip:+393492548964@pbx.chiusi'...
This call will be terminated after '50' seconds.
15:39:45.313         os_core_unix.c !pjlib 2.9 for POSIX initialized
./run: line 337: echo: write error: Broken pipe
./run: line 337: echo: write error: Broken pipe
./run: line 337:   404 Exit 1                  ( sleep $MAX_CALL_TIME_VALUE; echo h; sleep 0.5; echo q )
       405 Segmentation fault      (core dumped) | ( pjsua --app-log-level=3 --config-file '/share/dss_voiparm/dss_pjsua.conf' $CALL_SIP_URI_VALUE 2> /share/dss_voiparm/dss_pjsua.log )
[Error] pjsua Exit code: 139
[Info] Call ended...

**Comment by robitsrl** [comment]
aggiunta porta nella configurazione ora sembra tutto ok ma nessuna chiamata

[Info] Listening for messages via stdin service call...
[Info] Received messages {"call_sip_uri":"sip:+393492548964@pbx.chiusi","message_tts":"Write here your message"}
Converting audio file 'https://homeassistant.robit.biz/api/tts_proxy/3bb4cd06a7898fc0a33665f241cb48f2f2a192ac_it_-_google_translate.mp3'...
Audio succesfully converted...
Starting SIP Client and calling 'sip:+393492548964@pbx.chiusi'...
This call will be terminated after '50' seconds.
15:42:17.374         os_core_unix.c !pjlib 2.9 for POSIX initialized
15:42:17.375         sip_endpoint.c  .Creating endpoint instance...
15:42:17.376                  pjlib  .select() I/O Queue created (0x556ec9ac90)
15:42:17.376         sip_endpoint.c  .Module "mod-msg-print" registered
15:42:17.376        sip_transport.c  .Transport manager created.
15:42:17.376           pjsua_core.c  .PJSUA state changed: NULL --> CREATED
15:42:17.394           pjsua_core.c  .pjsua version 2.9 for Linux-6.1.58/aarch64 initialized
15:42:17.397            pjsua_app.c  .Turning sound device -99 -99 ON
15:42:17.398                 main.c  Ready: Success
15:42:17.403            pjsua_app.c  .......Call 0 state changed to CALLING
>>>>
Account list:
  [ 0] <sip:172.30.33.7:5060>: does not register
       Online status: Online
  [ 1] <sip:172.30.33.7:5060;transport=TCP>: does not register
       Online status: Online
 *[ 2] sip:1021@pbx.chiusi:5060: does not register
       Online status: Online
Buddy list:
 [ 1] <?>  sip:+393492548964@pbx.chiusi

+=============================================================================+
|       Call Commands:         |   Buddy, IM & Presence:  |     Account:      |
|                              |                          |                   |
|  m  Make new call            | +b  Add new buddy       .| +a  Add new accnt |
|  M  Make multiple calls      | -b  Delete buddy         | -a  Delete accnt. |
|  a  Answer call              |  i  Send IM              | !a  Modify accnt. |
|  h  Hangup call  (ha=all)    |  s  Subscribe presence   | rr  (Re-)register |
|  H  Hold call                |  u  Unsubscribe presence | ru  Unregister    |
|  v  re-inVite (release hold) |  t  ToGgle Online status |  >  Cycle next ac.|
|  U  send UPDATE              |  T  Set online status    |  <  Cycle prev ac.|
| ],[ Select next/prev call    +--------------------------+-------------------+
|  x  Xfer call                |      Media Commands:     |  Status & Config: |
|  X  Xfer with Replaces       |                          |                   |
|  #  Send RFC 2833 DTMF       | cl  List ports           |  d  Dump status   |
|  *  Send DTMF with INFO      | cc  Connect port         | dd  Dump detailed |
| dq  Dump curr. call quality  | cd  Disconnect port      | dc  Dump config   |
|                              |  V  Adjust audio Volume  |  f  Save config   |
|  S  Send arbitrary REQUEST   | Cp  Codec priorities     |                   |
+-----------------------------------------------------------------------------+
|  q  QUIT   L  ReLoad   sleep MS   echo [0|1|txt]     n: detect NAT type     |
+=============================================================================+
You have 1 active call
Current call id=0 to sip:+393492548964@pbx.chiusi [CALLING]

**Comment by robitsrl** [comment]
Hi,
I made many test in oreder to use a pbx from Yeastar (Asterisk)

if I use --no_tcp option i get this in the log: (password argoments is not valid)

8:28:47.819         os_core_unix.c !pjlib 2.9 for POSIX initialized
08:28:47.820         sip_endpoint.c  .Creating endpoint instance...
08:28:47.821                  pjlib  .select() I/O Queue created (0x5589b9ac90)
08:28:47.821         sip_endpoint.c  .Module "mod-msg-print" registered
08:28:47.821        sip_transport.c  .Transport manager created.
08:28:47.821           pjsua_core.c  .PJSUA state changed: NULL --> CREATED
08:28:47.821     pjsua_app_config.c  Argument "123456123456132456" is not valid. Use --help to see help
08:28:47.821           pjsua_core.c  Shutting down, flags=0...
08:28:47.821           pjsua_core.c  PJSUA state changed: CREATED --> CLOSING
08:28:47.821           pjsua_call.c  .Hangup all calls..
08:28:47.821          pjsua_media.c  .Call 0: deinitializing media..
08:28:47.821          pjsua_media.c  .Call 1: deinitializing media..
08:28:47.821          pjsua_media.c  .Call 2: deinitializing media..
08:28:47.821          pjsua_media.c  .Call 3: deinitializing media..
08:28:47.821           pjsua_pres.c  .Shutting down presence..
08:28:48.827           pjsua_core.c  .Destroying...
08:28:48.827          pjsua_media.c  .Shutting down media..
08:28:48.827         sip_endpoint.c  .Destroying endpoint instance..
08:28:48.827         sip_endpoint.c  .Module "mod-msg-print" unregistered
08:28:48.827        sip_transport.c  .Destroying transport manager
08:28:48.827         sip_endpoint.c  .Endpoint 0x5589b8ff08 destroyed
08:28:48.827           pjsua_core.c  .PJSUA state changed: CLOSING --> NULL
08:28:48.827           pjsua_core.c  .PJSUA destroyed...



if I not that parameter i get this connection refused:

Info] Received messages {"call_sip_uri":"sip:+393492548964@pbx.chiusi","message_tts":"Allarme abitazione via chiusi"}
Converting audio file 'https://homeassistant.robit.biz/api/tts_proxy/e71ed76ff45888c2f1291fe2f861cc523537c6cc_it_-_google_translate.mp3'...
Audio succesfully converted...
Starting SIP Client and calling 'sip:+393492548964@pbx.chiusi'...
This call will be terminated after '50' seconds.
08:29:33.707         os_core_unix.c !pjlib 2.9 for POSIX initialized
08:29:33.708         sip_endpoint.c  .Creating endpoint instance...
08:29:33.708                  pjlib  .select() I/O Queue created (0x55804a4c90)
08:29:33.708         sip_endpoint.c  .Module "mod-msg-print" registered
08:29:33.708        sip_transport.c  .Transport manager created.
08:29:33.708           pjsua_core.c  .PJSUA state changed: NULL --> CREATED
08:29:33.730           pjsua_core.c  .pjsua version 2.9 for Linux-6.1.58/aarch64 initialized
08:29:33.733            pjsua_app.c  .Turning sound device -99 -99 ON
08:29:33.733                 main.c  Ready: Success
08:29:33.737            pjsua_app.c  .......Call 0 state changed to CALLING
>>>>
Account list:
  [ 0] <sip:217.133.245.218:5060>: does not register
       Online status: Online
  [ 1] <sip:217.133.245.218:5060;transport=TCP>: does not register
       Online status: Online
 *[ 2] sip:homeassistant@pbx.chiusi:5060: does not register
       Online status: Online
Buddy list:
 [ 1] <?>  sip:+393492548964@pbx.chiusi

+=============================================================================+
|       Call Commands:         |   Buddy, IM & Presence:  |     Account:      |
|                              |                          |                   |
|  m  Make new call            | +b  Add new buddy       .| +a  Add new accnt |
|  M  Make multiple calls      | -b  Delete buddy         | -a  Delete accnt. |
|  a  Answer call              |  i  Send IM              | !a  Modify accnt. |
|  h  Hangup call  (ha=all)    |  s  Subscribe presence   | rr  (Re-)register |
|  H  Hold call                |  u  Unsubscribe presence | ru  Unregister    |
|  v  re-inVite (release hold) |  t  ToGgle Online status |  >  Cycle next ac.|
|  U  send UPDATE              |  T  Set online status    |  <  Cycle prev ac.|
| ],[ Select next/prev call    +--------------------------+-------------------+
|  x  Xfer call                |      Media Commands:     |  Status & Config: |
|  X  Xfer with Replaces       |                          |                   |
|  #  Send RFC 2833 DTMF       | cl  List ports           |  d  Dump status   |
|  *  Send DTMF with INFO      | cc  Connect port         | dd  Dump detailed |
| dq  Dump curr. call quality  | cd  Disconnect port      | dc  Dump config   |
|                              |  V  Adjust audio Volume  |  f  Save config   |
|  S  Send arbitrary REQUEST   | Cp  Codec priorities     |                   |
+-----------------------------------------------------------------------------+
|  q  QUIT   L  ReLoad   sleep MS   echo [0|1|txt]     n: detect NAT type     |
+=============================================================================+
You have 1 active call
Current call id=0 to sip:+393492548964@pbx.chiusi [CALLING]
>>> 08:29:33.744       tcpc0x55804f8f08  TCP connect() error: [code=120111]: Connection refused
08:29:33.744        tsx0x55804f8108  Temporary failure in sending Request msg INVITE/cseq=440 (tdta0x55804ef408), will try next server: Connection refused
08:29:33.744            pjsua_app.c  SIP TCP transport is disconnected from 192.168.202.150:5060: Connection refused [status=120111]
08:29:33.748            pjsua_app.c  .....Call 0 is DISCONNECTED [reason=401 (Unauthorized)]
08:29:33.748     pjsua_app_common.c  .....
  [DISCONNCTD] To: sip:+393492548964@pbx.chiusi
    Call time: 00h:00m:00s, 1st res in 15 ms, conn in 0ms
08:29:34.734            pjsua_app.c  .Turning sound device -99 -99 OFF
No current call
[Info] Call ended...


Any advice ?
Thanks

**Comment by sdesalve** [comment]
> Any advice ?

Yes. Double check syntax

It's not as you typed, its

`--no-tcp`

**Comment by robitsrl** [comment]
ok now this is the log:

 tsx0x55a6735228  .......Temporary failure in sending Request msg INVITE/cseq=30094 (tdta0x55a672c528), will try next server: Unsupported transport (PJSIP_EUNSUPTRANSPORT)
pjsua_app.c  .....Call 0 is DISCONNECTED [reason=401 (Unauthorized)]

**Comment by sdesalve** [comment]
Dice che user e password sono sbagliati.

Se metti il log e configurazione completi vedo se hai scritto bene l'opzione no tcp e se la sta rilevando...

Altrimenti non so cosa dirti

**Comment by robitsrl** [comment]
sip_parameters:
  caller_id_uri: sip:1021@192.168.202.150:5060
  realm: "*"
  username: "1021"
  password: Prova123456
pjsua_custom_options: "--no-tcp"



log

[Info] Starting addon...
PJSUA_CUSTOM_OPTIONS = '--no-tcp'
[Info] Listening for messages via stdin service call...
[Info] Received messages {"call_sip_uri":"sip:+393492548964@192.168.202.150","message_tts":"Allarme abitazione via chiusi"}
Converting audio file 'https://homeassistant.robit.biz/api/tts_proxy/e71ed76ff45888c2f1291fe2f861cc523537c6cc_it_-_google_translate.mp3'...
Audio succesfully converted...
Starting SIP Client and calling 'sip:+393492548964@192.168.202.150'...
This call will be terminated after '50' seconds.
10:34:36.907         os_core_unix.c !pjlib 2.9 for POSIX initialized
10:34:36.908         sip_endpoint.c  .Creating endpoint instance...
10:34:36.909                  pjlib  .select() I/O Queue created (0x55cf6a0c90)
10:34:36.909         sip_endpoint.c  .Module "mod-msg-print" registered
10:34:36.909        sip_transport.c  .Transport manager created.
10:34:36.909           pjsua_core.c  .PJSUA state changed: NULL --> CREATED
10:34:36.927           pjsua_core.c  .pjsua version 2.9 for Linux-6.1.58/aarch64 initialized
10:34:36.930            pjsua_app.c  .Turning sound device -99 -99 ON
10:34:36.931                 main.c  Ready: Success
10:34:36.932            pjsua_app.c  .......Call 0 state changed to CALLING
>>>>
Account list:
  [ 0] <sip:172.30.33.7:5060>: does not register
       Online status: Online
 *[ 1] sip:1021@192.168.202.150:5060: does not register
       Online status: Online
Buddy list:
 [ 1] <?>  sip:+393492548964@192.168.202.150

+=============================================================================+
|       Call Commands:         |   Buddy, IM & Presence:  |     Account:      |
|                              |                          |                   |
|  m  Make new call            | +b  Add new buddy       .| +a  Add new accnt |
|  M  Make multiple calls      | -b  Delete buddy         | -a  Delete accnt. |
|  a  Answer call              |  i  Send IM              | !a  Modify accnt. |
|  h  Hangup call  (ha=all)    |  s  Subscribe presence   | rr  (Re-)register |
|  H  Hold call                |  u  Unsubscribe presence | ru  Unregister    |
|  v  re-inVite (release hold) |  t  ToGgle Online status |  >  Cycle next ac.|
|  U  send UPDATE              |  T  Set online status    |  <  Cycle prev ac.|
| ],[ Select next/prev call    +--------------------------+-------------------+
|  x  Xfer call                |      Media Commands:     |  Status & Config: |
|  X  Xfer with Replaces       |                          |                   |
|  #  Send RFC 2833 DTMF       | cl  List ports           |  d  Dump status   |
|  *  Send DTMF with INFO      | cc  Connect port         | dd  Dump detailed |
| dq  Dump curr. call quality  | cd  Disconnect port      | dc  Dump config   |
|                              |  V  Adjust audio Volume  |  f  Save config   |
|  S  Send arbitrary REQUEST   | Cp  Codec priorities     |                   |
+-----------------------------------------------------------------------------+
|  q  QUIT   L  ReLoad   sleep MS   echo [0|1|txt]     n: detect NAT type     |
+=============================================================================+
You have 1 active call
Current call id=0 to sip:+393492548964@192.168.202.150 [CALLING]
>>> 10:34:36.938        tsx0x55cf6f3228  .......Temporary failure in sending Request msg INVITE/cseq=14994 (tdta0x55cf6ea528), will try next server: Unsupported transport (PJSIP_EUNSUPTRANSPORT)
10:34:36.942            pjsua_app.c  .....Call 0 is DISCONNECTED [reason=404 (Not Found)]
10:34:36.942     pjsua_app_common.c  .....
  [DISCONNCTD] To: sip:+393492548964@192.168.202.150
    Call time: 00h:00m:00s, 1st res in 11 ms, conn in 0ms
10:34:37.931            pjsua_app.c  .Turning sound device -99 -99 OFF
No current call

**Comment by sdesalve** [comment]
Cancella il tuo numero... Cancella URL hassio...

404 è strano. 

l'IP/porta del pbx quali sono? Li hai messi giusti?
