### ISSUE TITLE
Failed to install add-on: The command '/bin/ash -o pipefail -c apk add --no-cache openssl' returned a non-zero code: 8

### ISSUE THREAD

**Issue by stas1000** [sdesalve/hassio-addons#97]
I am unsure where the issue is but the add on for monocle can't be installed on my HA server. the error is:
Failed to install add-on: The command '/bin/ash -o pipefail -c apk add --no-cache openssl' returned a non-zero code: 8

**Comment by sdesalve** [comment]
You can only try ro restart host machine and retry.

It's HA that is unable to get openssl package from their repository

**Comment by stas1000** [comment]
i have kept restarting and trying but still the same error. It only seems to be the 4 addons from this repo though as others install. Is there anything else i can try on my end?

**Comment by sdesalve** [comment]
apk update
 apk add --no-cache wget
 apk add --no-cache curl
 apk add --no-cache libstdc++
 apk add --no-cache nano
 apk add --no-cache net-tools
 apk add --no-cache openssl
 apk add --no-cache ca-certificates

Try to run this within SSH terminal and post here errors

**Comment by stas1000** [comment]
there didn't seem to be any errors with the above commands in the supervisor or SSH logs but still not working unfortunately.
Supervisor

 ---> 83480b1b73da

Step 15/32 : RUN apk add --no-cache libstdc++


 ---> Using cache

 ---> 27d63a9ec87c

Step 16/32 : RUN apk add --no-cache nano


 ---> Using cache

 ---> 70f9a68f5723

Step 17/32 : RUN apk add --no-cache net-tools


 ---> Using cache

 ---> ada8bf3d2e25

Step 18/32 : RUN apk add --no-cache openssl


 ---> Running in 838a4ee04b2c

fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz

fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/x86_64/APKINDEX.tar.gz

ERROR: unable to select packages:

  libcrypto1.1-1.1.1s-r0:
    breaks: openssl-1.1.1w-r1[libcrypto1.1=1.1.1w-r1]
    satisfies: world[libcrypto1.1=1.1.1s-r0]
               openssl-1.1.1w-r1[so:libcrypto.so.1.1]
               wget-1.21.3-r0[so:libcrypto.so.1.1]
               ca-certificates-20220614-r0[so:libcrypto.so.1.1]
               libcurl-7.83.1-r4[so:libcrypto.so.1.1]
               apk-tools-2.12.9-r3[so:libcrypto.so.1.1]
               libssl1.1-1.1.1s-r0[so:libcrypto.so.1.1]
  libssl1.1-1.1.1s-r0:
    breaks: openssl-1.1.1w-r1[libssl1.1=1.1.1w-r1]
    satisfies: world[libssl1.1=1.1.1s-r0]
               openssl-1.1.1w-r1[so:libssl.so.1.1]
               wget-1.21.3-r0[so:libssl.so.1.1]
               libcurl-7.83.1-r4[so:libssl.so.1.1]
               apk-tools-2.12.9-r3[so:libssl.so.1.1]

 ---> Removed intermediate container 838a4ee04b2c

![image](https://github.com/sdesalve/hassio-addons/assets/22050639/2a3039b2-ee0b-4487-9ff2-aa1f5c5fe9fc)

![Uploading image.png…]()
