### ISSUE TITLE
The command '/bin/ash -o pipefail -c apk add --no-cache openssl' returned a non-zero code: 8

### ISSUE THREAD

**Issue by pmdeluca** [sdesalve/hassio-addons#98]
After clicking on Install, this is the message I am receiving on HAOS running on an x64 Intel computer.

I have no experience in Linux. Can you assist?

**Comment by sdesalve** [comment]
have you tried to restart computer?
hassio cannot install openssl package

**Comment by pmdeluca** [comment]
I have tried to restart and reinstall, same error. I don't know how to install openssl on haos, can't find an ad on for that. Any clues?

Thanks for your help!

**Comment by pmdeluca** [comment]
I have found this command and installed the openssl, restarted, but still get the same error.

[core-ssh ~]$ apk add openssl

![image](https://github.com/sdesalve/hassio-addons/assets/28710490/aa7e3725-75fc-4732-be0f-814a05f643df)

**Comment by sdesalve** [comment]
Purtroppo l'installazione deve essere fatta da Hassio all'interno del Container dive girerà l'addon. 
Se lo installi all'interno del container dove gira SSH al successivo riavvio non ci sarà più.
Hassio su qualche sistema, per qualche strana ragione non riesce ad installare delle comunissime librerie che sono usate in tantissimi addon.
L'unica è provare e riprovare riavviando

sorry

PS: non hai detto che addon stai installando e quale versione

**Comment by M-Armen** [comment]
I am running to the same issue, with same error message, my question is, could it be b/c haas already has the port 443 used to access the main page, could that be the issue?

**Comment by sdesalve** [comment]
I don't think. Should be some network issue and it's related to alpine apk add

**Comment by M-Armen** [comment]
is there manual steps that I can run in the terminal to install the addon maybe, so we can get verbose output to try to trouble shoot?

**Comment by sdesalve** [comment]
https://github.com/sdesalve/hassio-addons/blob/a5ac4a4b5bc4ae0160db1c9cfab7275debfd379d/dss_monocle-gateway-beta/Dockerfile#L28


you could try to install, temporarily, within a SSH prompt to get verbose output. at restart all apk will be deleted and it isn't same container where add-on will run.

have you tried both add-on versions?

**Comment by M-Armen** [comment]
Well, I got OK for all the steps for apk add, screenshot below.

[cid:b122ac79-ab27-443a-a801-f556d1c174eb]

Now, I am using the HA cloud, not sure if that could impact as well.
________________________________

**Comment by M-Armen** [comment]
I may have found the reason in the logs for the supervisor, is this related?



Step 18/33 : RUN apk add --no-cache openssl


 ---> Running in ea9f89783f3f

fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/main/aarch64/APKINDEX.tar.gz

fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/community/aarch64/APKINDEX.tar.gz

ERROR: unable to select packages:

  libcrypto3-3.0.7-r0:
    breaks: openssl-3.0.15-r0[libcrypto3=3.0.15-r0]
    satisfies: world[libcrypto3=3.0.7-r0]
               openssl-3.0.15-r0[so:libcrypto.so.3]
               wget-1.21.4-r0[so:libcrypto.so.3]
               ca-certificates-20220614-r2[so:libcrypto.so.3]
               libcurl-7.86.0-r1[so:libcrypto.so.3]
               apk-tools-2.12.10-r1[so:libcrypto.so.3]
               libssl3-3.0.7-r0[so:libcrypto.so.3]
  libssl3-3.0.7-r0:
    breaks: openssl-3.0.15-r0[libssl3=3.0.15-r0]
    satisfies: world[libssl3=3.0.7-r0]
               openssl-3.0.15-r0[so:libssl.so.3]
               wget-1.21.4-r0[so:libssl.so.3]
               libcurl-7.86.0-r1[so:libssl.so.3]
               apk-tools-2.12.10-r1[so:libssl.so.3]

 ---> Removed intermediate container ea9f89783f3f

**Comment by sdesalve** [comment]
try to install dss_monocle-gateway-beta 16.0.1

**Comment by M-Armen** [comment]
Sorry didn't mention earlier, I am installing this on HA Yellow, so I only have option for bets version. 

Based on the error above, how can we limit the choice  since the system stops with more then one choice, limit to main or community.

**Comment by sdesalve** [comment]
you should choose to install monocle add-on with beta in its name.

could you send me a screenshot of add-on available within this repository to be installed on your hassio?

**Comment by M-Armen** [comment]
sure, this is what shows when trying to add.

![image](https://github.com/user-attachments/assets/39c9d67b-979f-4b9c-af38-4f61a1d25d80)

**Comment by sdesalve** [comment]
have you tried to install this one?

![Screenshot_2024-09-17-20-31-38-694_com android chrome](https://github.com/user-attachments/assets/6fe749da-bc5a-4a67-b933-00582237ab9d)

**Comment by M-Armen** [comment]
Yes, thats the only one available for me, the other one is grayed out, not clickable, maybe is not showing weel on the picture.

**Comment by sdesalve** [comment]
have you tried to restart hassio or checked that available version is reported as 16.0.1?

**Comment by M-Armen** [comment]
Ok, I have successfully installed 16.0.1 with no issues, didn't make any changes on my end, I assume you made changes on your side correct? ))

thank you so much, now need to configure my UNIFI cameras and add to the site.
